// @generated by tools/generate_mq_mqi_registry.py; do not edit.
pub const MQ_RAW_LAYOUT_PROJECTION_SHA256: &str = "2f6d7c679543891ccc768f099963813d981871d2abd35fa7b49aa4e70732ae6a";
pub(super) const MAX_PREFIX: usize = 364;
pub(super) const COBOL_LONG_MIN: i32 = -999999999;
pub(super) const COBOL_LONG_MAX: i32 = 999999999;
const OD1_FIELDS: &[MqRawFieldDescriptor] = &[
    MqRawFieldDescriptor {
        name: "StrucId",
        kind: MqRawFieldKind::Characters,
        offset: 0,
        width: 4,
        initial: MqRawInitialValue::Identifier,
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Version",
        kind: MqRawFieldKind::Long,
        offset: 4,
        width: 4,
        initial: MqRawInitialValue::Long(1),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "ObjectType",
        kind: MqRawFieldKind::Long,
        offset: 8,
        width: 4,
        initial: MqRawInitialValue::Long(1),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "ObjectName",
        kind: MqRawFieldKind::Characters,
        offset: 12,
        width: 48,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::DynamicOpen,
    },
    MqRawFieldDescriptor {
        name: "ObjectQMgrName",
        kind: MqRawFieldKind::Characters,
        offset: 60,
        width: 48,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::DynamicOpen,
    },
    MqRawFieldDescriptor {
        name: "DynamicQName",
        kind: MqRawFieldKind::Characters,
        offset: 108,
        width: 48,
        initial: MqRawInitialValue::Environment,
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "AlternateUserId",
        kind: MqRawFieldKind::Characters,
        offset: 156,
        width: 12,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Input,
    },
];
const MD1_FIELDS: &[MqRawFieldDescriptor] = &[
    MqRawFieldDescriptor {
        name: "StrucId",
        kind: MqRawFieldKind::Characters,
        offset: 0,
        width: 4,
        initial: MqRawInitialValue::Identifier,
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Version",
        kind: MqRawFieldKind::Long,
        offset: 4,
        width: 4,
        initial: MqRawInitialValue::Long(1),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Report",
        kind: MqRawFieldKind::Long,
        offset: 8,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "MsgType",
        kind: MqRawFieldKind::Long,
        offset: 12,
        width: 4,
        initial: MqRawInitialValue::Long(8),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Expiry",
        kind: MqRawFieldKind::Long,
        offset: 16,
        width: 4,
        initial: MqRawInitialValue::Long(-1),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Feedback",
        kind: MqRawFieldKind::Long,
        offset: 20,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Encoding",
        kind: MqRawFieldKind::Long,
        offset: 24,
        width: 4,
        initial: MqRawInitialValue::Environment,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "CodedCharSetId",
        kind: MqRawFieldKind::Long,
        offset: 28,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Format",
        kind: MqRawFieldKind::Characters,
        offset: 32,
        width: 8,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Priority",
        kind: MqRawFieldKind::Long,
        offset: 40,
        width: 4,
        initial: MqRawInitialValue::Long(-1),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Persistence",
        kind: MqRawFieldKind::Long,
        offset: 44,
        width: 4,
        initial: MqRawInitialValue::Long(2),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "MsgId",
        kind: MqRawFieldKind::Bytes,
        offset: 48,
        width: 24,
        initial: MqRawInitialValue::Nulls,
        writeback: WritebackPolicy::GetPut,
    },
    MqRawFieldDescriptor {
        name: "CorrelId",
        kind: MqRawFieldKind::Bytes,
        offset: 72,
        width: 24,
        initial: MqRawInitialValue::Nulls,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "BackoutCount",
        kind: MqRawFieldKind::Long,
        offset: 96,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "ReplyToQ",
        kind: MqRawFieldKind::Characters,
        offset: 100,
        width: 48,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "ReplyToQMgr",
        kind: MqRawFieldKind::Characters,
        offset: 148,
        width: 48,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "UserIdentifier",
        kind: MqRawFieldKind::Characters,
        offset: 196,
        width: 12,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "AccountingToken",
        kind: MqRawFieldKind::Bytes,
        offset: 208,
        width: 32,
        initial: MqRawInitialValue::Nulls,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "ApplIdentityData",
        kind: MqRawFieldKind::Characters,
        offset: 240,
        width: 32,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "PutApplType",
        kind: MqRawFieldKind::Long,
        offset: 272,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "PutApplName",
        kind: MqRawFieldKind::Characters,
        offset: 276,
        width: 28,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "PutDate",
        kind: MqRawFieldKind::Characters,
        offset: 304,
        width: 8,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "PutTime",
        kind: MqRawFieldKind::Characters,
        offset: 312,
        width: 8,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "ApplOriginData",
        kind: MqRawFieldKind::Characters,
        offset: 320,
        width: 4,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
];
const MD2_FIELDS: &[MqRawFieldDescriptor] = &[
    MqRawFieldDescriptor {
        name: "StrucId",
        kind: MqRawFieldKind::Characters,
        offset: 0,
        width: 4,
        initial: MqRawInitialValue::Identifier,
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Version",
        kind: MqRawFieldKind::Long,
        offset: 4,
        width: 4,
        initial: MqRawInitialValue::Long(1),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Report",
        kind: MqRawFieldKind::Long,
        offset: 8,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "MsgType",
        kind: MqRawFieldKind::Long,
        offset: 12,
        width: 4,
        initial: MqRawInitialValue::Long(8),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Expiry",
        kind: MqRawFieldKind::Long,
        offset: 16,
        width: 4,
        initial: MqRawInitialValue::Long(-1),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Feedback",
        kind: MqRawFieldKind::Long,
        offset: 20,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Encoding",
        kind: MqRawFieldKind::Long,
        offset: 24,
        width: 4,
        initial: MqRawInitialValue::Environment,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "CodedCharSetId",
        kind: MqRawFieldKind::Long,
        offset: 28,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Format",
        kind: MqRawFieldKind::Characters,
        offset: 32,
        width: 8,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Priority",
        kind: MqRawFieldKind::Long,
        offset: 40,
        width: 4,
        initial: MqRawInitialValue::Long(-1),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Persistence",
        kind: MqRawFieldKind::Long,
        offset: 44,
        width: 4,
        initial: MqRawInitialValue::Long(2),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "MsgId",
        kind: MqRawFieldKind::Bytes,
        offset: 48,
        width: 24,
        initial: MqRawInitialValue::Nulls,
        writeback: WritebackPolicy::GetPut,
    },
    MqRawFieldDescriptor {
        name: "CorrelId",
        kind: MqRawFieldKind::Bytes,
        offset: 72,
        width: 24,
        initial: MqRawInitialValue::Nulls,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "BackoutCount",
        kind: MqRawFieldKind::Long,
        offset: 96,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "ReplyToQ",
        kind: MqRawFieldKind::Characters,
        offset: 100,
        width: 48,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "ReplyToQMgr",
        kind: MqRawFieldKind::Characters,
        offset: 148,
        width: 48,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "UserIdentifier",
        kind: MqRawFieldKind::Characters,
        offset: 196,
        width: 12,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "AccountingToken",
        kind: MqRawFieldKind::Bytes,
        offset: 208,
        width: 32,
        initial: MqRawInitialValue::Nulls,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "ApplIdentityData",
        kind: MqRawFieldKind::Characters,
        offset: 240,
        width: 32,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "PutApplType",
        kind: MqRawFieldKind::Long,
        offset: 272,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "PutApplName",
        kind: MqRawFieldKind::Characters,
        offset: 276,
        width: 28,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "PutDate",
        kind: MqRawFieldKind::Characters,
        offset: 304,
        width: 8,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "PutTime",
        kind: MqRawFieldKind::Characters,
        offset: 312,
        width: 8,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "ApplOriginData",
        kind: MqRawFieldKind::Characters,
        offset: 320,
        width: 4,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "GroupId",
        kind: MqRawFieldKind::Bytes,
        offset: 324,
        width: 24,
        initial: MqRawInitialValue::Nulls,
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "MsgSeqNumber",
        kind: MqRawFieldKind::Long,
        offset: 348,
        width: 4,
        initial: MqRawInitialValue::Long(1),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "Offset",
        kind: MqRawFieldKind::Long,
        offset: 352,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "MsgFlags",
        kind: MqRawFieldKind::Long,
        offset: 356,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Get,
    },
    MqRawFieldDescriptor {
        name: "OriginalLength",
        kind: MqRawFieldKind::Long,
        offset: 360,
        width: 4,
        initial: MqRawInitialValue::Long(-1),
        writeback: WritebackPolicy::Get,
    },
];
const GMO1_FIELDS: &[MqRawFieldDescriptor] = &[
    MqRawFieldDescriptor {
        name: "StrucId",
        kind: MqRawFieldKind::Characters,
        offset: 0,
        width: 4,
        initial: MqRawInitialValue::Identifier,
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Version",
        kind: MqRawFieldKind::Long,
        offset: 4,
        width: 4,
        initial: MqRawInitialValue::Long(1),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Options",
        kind: MqRawFieldKind::Long,
        offset: 8,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "WaitInterval",
        kind: MqRawFieldKind::Long,
        offset: 12,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Signal1",
        kind: MqRawFieldKind::SignalSlot,
        offset: 16,
        width: 4,
        initial: MqRawInitialValue::Environment,
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Signal2",
        kind: MqRawFieldKind::Long,
        offset: 20,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "ResolvedQName",
        kind: MqRawFieldKind::Characters,
        offset: 24,
        width: 48,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::Get,
    },
];
const PMO1_FIELDS: &[MqRawFieldDescriptor] = &[
    MqRawFieldDescriptor {
        name: "StrucId",
        kind: MqRawFieldKind::Characters,
        offset: 0,
        width: 4,
        initial: MqRawInitialValue::Identifier,
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Version",
        kind: MqRawFieldKind::Long,
        offset: 4,
        width: 4,
        initial: MqRawInitialValue::Long(1),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Options",
        kind: MqRawFieldKind::Long,
        offset: 8,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Timeout",
        kind: MqRawFieldKind::Long,
        offset: 12,
        width: 4,
        initial: MqRawInitialValue::Long(-1),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Context",
        kind: MqRawFieldKind::Alias,
        offset: 16,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "KnownDestCount",
        kind: MqRawFieldKind::Long,
        offset: 20,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::PutCountOther,
    },
    MqRawFieldDescriptor {
        name: "UnknownDestCount",
        kind: MqRawFieldKind::Long,
        offset: 24,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::PutCountOther,
    },
    MqRawFieldDescriptor {
        name: "InvalidDestCount",
        kind: MqRawFieldKind::Long,
        offset: 28,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::PutCountOther,
    },
    MqRawFieldDescriptor {
        name: "ResolvedQName",
        kind: MqRawFieldKind::Characters,
        offset: 32,
        width: 48,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::SingleQueuePut,
    },
    MqRawFieldDescriptor {
        name: "ResolvedQMgrName",
        kind: MqRawFieldKind::Characters,
        offset: 80,
        width: 48,
        initial: MqRawInitialValue::Blanks,
        writeback: WritebackPolicy::SingleQueuePut,
    },
];
const CNO1_FIELDS: &[MqRawFieldDescriptor] = &[
    MqRawFieldDescriptor {
        name: "StrucId",
        kind: MqRawFieldKind::Characters,
        offset: 0,
        width: 4,
        initial: MqRawInitialValue::Identifier,
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Version",
        kind: MqRawFieldKind::Long,
        offset: 4,
        width: 4,
        initial: MqRawInitialValue::Long(1),
        writeback: WritebackPolicy::Input,
    },
    MqRawFieldDescriptor {
        name: "Options",
        kind: MqRawFieldKind::Long,
        offset: 8,
        width: 4,
        initial: MqRawInitialValue::Long(0),
        writeback: WritebackPolicy::PendingOutput,
    },
];
pub(super) const LAYOUTS: &[MqRawLayoutDescriptor] = &[
    MqRawLayoutDescriptor {
        kind: MqRawLayoutKind::Od1,
        version: 1,
        prefix_bytes: 168,
        ascii_identifier: *b"OD  ",
        cp037_identifier: [214, 196, 64, 64],
        fields: OD1_FIELDS,
    },
    MqRawLayoutDescriptor {
        kind: MqRawLayoutKind::Md1,
        version: 1,
        prefix_bytes: 324,
        ascii_identifier: *b"MD  ",
        cp037_identifier: [212, 196, 64, 64],
        fields: MD1_FIELDS,
    },
    MqRawLayoutDescriptor {
        kind: MqRawLayoutKind::Md2,
        version: 2,
        prefix_bytes: 364,
        ascii_identifier: *b"MD  ",
        cp037_identifier: [212, 196, 64, 64],
        fields: MD2_FIELDS,
    },
    MqRawLayoutDescriptor {
        kind: MqRawLayoutKind::Gmo1,
        version: 1,
        prefix_bytes: 72,
        ascii_identifier: *b"GMO ",
        cp037_identifier: [199, 212, 214, 64],
        fields: GMO1_FIELDS,
    },
    MqRawLayoutDescriptor {
        kind: MqRawLayoutKind::Pmo1,
        version: 1,
        prefix_bytes: 128,
        ascii_identifier: *b"PMO ",
        cp037_identifier: [215, 212, 214, 64],
        fields: PMO1_FIELDS,
    },
    MqRawLayoutDescriptor {
        kind: MqRawLayoutKind::Cno1,
        version: 1,
        prefix_bytes: 12,
        ascii_identifier: *b"CNO ",
        cp037_identifier: [195, 213, 214, 64],
        fields: CNO1_FIELDS,
    },
];
pub(super) const MQCNO_ACCOUNTING_MQI_DISABLED: i32 = 8192;
pub(super) const MQCNO_ACCOUNTING_MQI_ENABLED: i32 = 4096;
pub(super) const MQCNO_ACCOUNTING_Q_DISABLED: i32 = 32768;
pub(super) const MQCNO_ACCOUNTING_Q_ENABLED: i32 = 16384;
pub(super) const MQCNO_ACTIVITY_TRACE_DISABLED: i32 = 268435456;
pub(super) const MQCNO_ACTIVITY_TRACE_ENABLED: i32 = 134217728;
pub(super) const MQCNO_ALL_CONVS_SHARE: i32 = 262144;
pub(super) const MQCNO_CD_FOR_OUTPUT_ONLY: i32 = 524288;
pub(super) const MQCNO_CLIENT_BINDING: i32 = 2048;
pub(super) const MQCNO_FASTPATH_BINDING: i32 = 1;
pub(super) const MQCNO_HANDLE_SHARE_BLOCK: i32 = 64;
pub(super) const MQCNO_HANDLE_SHARE_NONE: i32 = 32;
pub(super) const MQCNO_HANDLE_SHARE_NO_BLOCK: i32 = 128;
pub(super) const MQCNO_ISOLATED_BINDING: i32 = 512;
pub(super) const MQCNO_LOCAL_BINDING: i32 = 1024;
pub(super) const MQCNO_NONE: i32 = 0;
pub(super) const MQCNO_NO_CONV_SHARING: i32 = 65536;
pub(super) const MQCNO_RECONNECT: i32 = 16777216;
pub(super) const MQCNO_RECONNECT_AS_DEF: i32 = 0;
pub(super) const MQCNO_RECONNECT_DISABLED: i32 = 33554432;
pub(super) const MQCNO_RECONNECT_Q_MGR: i32 = 67108864;
pub(super) const MQCNO_RESTRICT_CONN_TAG_QSG: i32 = 16;
pub(super) const MQCNO_RESTRICT_CONN_TAG_Q_MGR: i32 = 8;
pub(super) const MQCNO_SERIALIZE_CONN_TAG_QSG: i32 = 4;
pub(super) const MQCNO_SERIALIZE_CONN_TAG_Q_MGR: i32 = 2;
pub(super) const MQCNO_SHARED_BINDING: i32 = 256;
pub(super) const MQCNO_STANDARD_BINDING: i32 = 0;
pub(super) const MQCNO_USE_CD_SELECTION: i32 = 1048576;
pub(super) const MQCNO_VERSION_1: i32 = 1;
pub(super) const MQCNO_KNOWN: i32 = MQCNO_ACCOUNTING_MQI_DISABLED
    | MQCNO_ACCOUNTING_MQI_ENABLED
    | MQCNO_ACCOUNTING_Q_DISABLED
    | MQCNO_ACCOUNTING_Q_ENABLED
    | MQCNO_ACTIVITY_TRACE_DISABLED
    | MQCNO_ACTIVITY_TRACE_ENABLED
    | MQCNO_ALL_CONVS_SHARE
    | MQCNO_CD_FOR_OUTPUT_ONLY
    | MQCNO_CLIENT_BINDING
    | MQCNO_FASTPATH_BINDING
    | MQCNO_HANDLE_SHARE_BLOCK
    | MQCNO_HANDLE_SHARE_NONE
    | MQCNO_HANDLE_SHARE_NO_BLOCK
    | MQCNO_ISOLATED_BINDING
    | MQCNO_LOCAL_BINDING
    | MQCNO_NONE
    | MQCNO_NO_CONV_SHARING
    | MQCNO_RECONNECT
    | MQCNO_RECONNECT_AS_DEF
    | MQCNO_RECONNECT_DISABLED
    | MQCNO_RECONNECT_Q_MGR
    | MQCNO_RESTRICT_CONN_TAG_QSG
    | MQCNO_RESTRICT_CONN_TAG_Q_MGR
    | MQCNO_SERIALIZE_CONN_TAG_QSG
    | MQCNO_SERIALIZE_CONN_TAG_Q_MGR
    | MQCNO_SHARED_BINDING
    | MQCNO_STANDARD_BINDING
    | MQCNO_USE_CD_SELECTION;
pub(super) const MQCNO_ADMITTED: &[i32] = &[MQCNO_NONE, MQCNO_HANDLE_SHARE_NONE];
pub(super) const MQCNO_NUMERIC_IDENTITIES: &[(&str, i32)] = &[
    ("MQCNO_ACCOUNTING_MQI_DISABLED", MQCNO_ACCOUNTING_MQI_DISABLED),
    ("MQCNO_ACCOUNTING_MQI_ENABLED", MQCNO_ACCOUNTING_MQI_ENABLED),
    ("MQCNO_ACCOUNTING_Q_DISABLED", MQCNO_ACCOUNTING_Q_DISABLED),
    ("MQCNO_ACCOUNTING_Q_ENABLED", MQCNO_ACCOUNTING_Q_ENABLED),
    ("MQCNO_ACTIVITY_TRACE_DISABLED", MQCNO_ACTIVITY_TRACE_DISABLED),
    ("MQCNO_ACTIVITY_TRACE_ENABLED", MQCNO_ACTIVITY_TRACE_ENABLED),
    ("MQCNO_ALL_CONVS_SHARE", MQCNO_ALL_CONVS_SHARE),
    ("MQCNO_CD_FOR_OUTPUT_ONLY", MQCNO_CD_FOR_OUTPUT_ONLY),
    ("MQCNO_CLIENT_BINDING", MQCNO_CLIENT_BINDING),
    ("MQCNO_FASTPATH_BINDING", MQCNO_FASTPATH_BINDING),
    ("MQCNO_HANDLE_SHARE_BLOCK", MQCNO_HANDLE_SHARE_BLOCK),
    ("MQCNO_HANDLE_SHARE_NONE", MQCNO_HANDLE_SHARE_NONE),
    ("MQCNO_HANDLE_SHARE_NO_BLOCK", MQCNO_HANDLE_SHARE_NO_BLOCK),
    ("MQCNO_ISOLATED_BINDING", MQCNO_ISOLATED_BINDING),
    ("MQCNO_LOCAL_BINDING", MQCNO_LOCAL_BINDING),
    ("MQCNO_NONE", MQCNO_NONE),
    ("MQCNO_NO_CONV_SHARING", MQCNO_NO_CONV_SHARING),
    ("MQCNO_RECONNECT", MQCNO_RECONNECT),
    ("MQCNO_RECONNECT_AS_DEF", MQCNO_RECONNECT_AS_DEF),
    ("MQCNO_RECONNECT_DISABLED", MQCNO_RECONNECT_DISABLED),
    ("MQCNO_RECONNECT_Q_MGR", MQCNO_RECONNECT_Q_MGR),
    ("MQCNO_RESTRICT_CONN_TAG_QSG", MQCNO_RESTRICT_CONN_TAG_QSG),
    ("MQCNO_RESTRICT_CONN_TAG_Q_MGR", MQCNO_RESTRICT_CONN_TAG_Q_MGR),
    ("MQCNO_SERIALIZE_CONN_TAG_QSG", MQCNO_SERIALIZE_CONN_TAG_QSG),
    ("MQCNO_SERIALIZE_CONN_TAG_Q_MGR", MQCNO_SERIALIZE_CONN_TAG_Q_MGR),
    ("MQCNO_SHARED_BINDING", MQCNO_SHARED_BINDING),
    ("MQCNO_STANDARD_BINDING", MQCNO_STANDARD_BINDING),
    ("MQCNO_USE_CD_SELECTION", MQCNO_USE_CD_SELECTION),
    ("MQCNO_VERSION_1", MQCNO_VERSION_1),
];
