// @generated by tools/generate_mq_mqi_registry.py; do not edit.
/// Reviewed owned reconciliation digest; not vendor ABI or execution evidence.
pub const MQ_RAW_PROPERTY_PROJECTION_SHA256: &str = "b156a6932351bb44c108e15d30a8d3ad4a7a465662762238c715596f7207f791";
pub(super) const MAX_GROUP_BYTES: usize = 65536;
pub(super) const MAX_BATCH_PLANS: usize = 8;
const CHARVNULLSLOT4ASCIINORMAL_FIELDS: &[MqRawPropertyField] = &[
    MqRawPropertyField {
        name: "VSPtr",
        kind: MqRawPropertyFieldKind::NullSlot,
        offset: 0,
        width: 4,
        defined_standard_output: false,
    },
    MqRawPropertyField {
        name: "VSOffset",
        kind: MqRawPropertyFieldKind::Long,
        offset: 4,
        width: 4,
        defined_standard_output: false,
    },
    MqRawPropertyField {
        name: "VSBufSize",
        kind: MqRawPropertyFieldKind::Long,
        offset: 8,
        width: 4,
        defined_standard_output: false,
    },
    MqRawPropertyField {
        name: "VSLength",
        kind: MqRawPropertyFieldKind::Long,
        offset: 12,
        width: 4,
        defined_standard_output: true,
    },
    MqRawPropertyField {
        name: "VSCCSID",
        kind: MqRawPropertyFieldKind::Long,
        offset: 16,
        width: 4,
        defined_standard_output: true,
    },
];
const IMPO1NULLSLOT4ASCIINORMAL_FIELDS: &[MqRawPropertyField] = &[
    MqRawPropertyField {
        name: "StrucId",
        kind: MqRawPropertyFieldKind::Characters,
        offset: 0,
        width: 4,
        defined_standard_output: false,
    },
    MqRawPropertyField {
        name: "Version",
        kind: MqRawPropertyFieldKind::Long,
        offset: 4,
        width: 4,
        defined_standard_output: false,
    },
    MqRawPropertyField {
        name: "Options",
        kind: MqRawPropertyFieldKind::Long,
        offset: 8,
        width: 4,
        defined_standard_output: false,
    },
    MqRawPropertyField {
        name: "RequestedEncoding",
        kind: MqRawPropertyFieldKind::Long,
        offset: 12,
        width: 4,
        defined_standard_output: false,
    },
    MqRawPropertyField {
        name: "RequestedCCSID",
        kind: MqRawPropertyFieldKind::Long,
        offset: 16,
        width: 4,
        defined_standard_output: false,
    },
    MqRawPropertyField {
        name: "ReturnedEncoding",
        kind: MqRawPropertyFieldKind::Long,
        offset: 20,
        width: 4,
        defined_standard_output: true,
    },
    MqRawPropertyField {
        name: "ReturnedCCSID",
        kind: MqRawPropertyFieldKind::Long,
        offset: 24,
        width: 4,
        defined_standard_output: true,
    },
    MqRawPropertyField {
        name: "Reserved1",
        kind: MqRawPropertyFieldKind::Characters,
        offset: 28,
        width: 4,
        defined_standard_output: false,
    },
    MqRawPropertyField {
        name: "ReturnedName.VSPtr",
        kind: MqRawPropertyFieldKind::NullSlot,
        offset: 32,
        width: 4,
        defined_standard_output: false,
    },
    MqRawPropertyField {
        name: "ReturnedName.VSOffset",
        kind: MqRawPropertyFieldKind::Long,
        offset: 36,
        width: 4,
        defined_standard_output: false,
    },
    MqRawPropertyField {
        name: "ReturnedName.VSBufSize",
        kind: MqRawPropertyFieldKind::Long,
        offset: 40,
        width: 4,
        defined_standard_output: false,
    },
    MqRawPropertyField {
        name: "ReturnedName.VSLength",
        kind: MqRawPropertyFieldKind::Long,
        offset: 44,
        width: 4,
        defined_standard_output: true,
    },
    MqRawPropertyField {
        name: "ReturnedName.VSCCSID",
        kind: MqRawPropertyFieldKind::Long,
        offset: 48,
        width: 4,
        defined_standard_output: true,
    },
    MqRawPropertyField {
        name: "TypeString",
        kind: MqRawPropertyFieldKind::Characters,
        offset: 52,
        width: 8,
        defined_standard_output: false,
    },
];
pub(super) const LAYOUTS: &[MqRawPropertyLayout] = &[
    MqRawPropertyLayout {
        kind: MqRawPropertyKind::CharvNullSlot4AsciiNormal,
        prefix_bytes: 20,
        identifier: None,
        version: None,
        fields: CHARVNULLSLOT4ASCIINORMAL_FIELDS,
    },
    MqRawPropertyLayout {
        kind: MqRawPropertyKind::Impo1NullSlot4AsciiNormal,
        prefix_bytes: 60,
        identifier: Some(*b"IMPO"),
        version: Some(1),
        fields: IMPO1NULLSLOT4ASCIINORMAL_FIELDS,
    },
];
