[package]
name = "mainframe-env-conformance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
mainframe-env-coverage.workspace = true
mainframe-env-source.workspace = true
mainframe-env-diagnostics.workspace = true
mainframe-env-encoding.workspace = true
mainframe-env-ir.workspace = true
mainframe-env-compiler-api.workspace = true
mainframe-env-execution-api.workspace = true
mainframe-env-host-api.workspace = true
mainframe-env-compiler.workspace = true
mainframe-env-interpreter.workspace = true
mainframe-env-application.workspace = true
mainframe-env-batch.workspace = true
mainframe-env-cics = { workspace = true, features = ["fault-injection"] }
mainframe-env-dataset.workspace = true
mainframe-env-db2.workspace = true
mainframe-env-racf.workspace = true
mainframe-env-server.workspace = true
mainframe-env-ims.workspace = true
mainframe-env-mq.workspace = true
mainframe-env-store.workspace = true
mainframe-env-store-api.workspace = true
axum.workspace = true
base64.workspace = true
ring.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tower.workspace = true

[dev-dependencies]
proptest.workspace = true
