//! Projection of the reviewed call-site matrix; catalog names remain sourced from 0.2.

use super::*;

const RULES_PATH: &str = "conformance/0.14/ims/call-applicability-rules.json";
const SCHEMA_PATH: &str = "conformance/0.14/schemas/ims-call-applicability.schema.json";
const PROGRAMMING_MANIFEST: &str =
    "conformance/0.14/manifests/ims-programming-contracts-topics.json";
const DATABASE_MANIFEST: &str = "conformance/0.14/manifests/ims-database-contracts-topics.json";

pub(super) fn render(root: &Path) -> TaskResult<Vec<u8>> {
    let rules_path = root.join(RULES_PATH);
    let rules = json(&rules_path)?;
    validate_schema_instance(&json(&root.join(SCHEMA_PATH))?, &rules, &rules_path)?;
    require(
        rules["schema_version"] == "mainframe-env.ims-call-applicability@1"
            && rules["target_version"] == "0.14.0"
            && rules["baseline_id"] == BASELINE,
        "IMS call applicability identity drifted",
    )?;
    let catalog_path = root.join(SOURCE_PATH);
    let catalog = json(&catalog_path)?;
    let rows = array(&catalog["units"][0], "rows", &catalog_path)?;
    require(
        rows.len() == 25,
        "IMS applicability requires exactly 25 official rows",
    )?;

    let mut pinned_topics = BTreeMap::new();
    for manifest_path in [PROGRAMMING_MANIFEST, DATABASE_MANIFEST] {
        let path = root.join(manifest_path);
        let manifest = json(&path)?;
        for topic in array(&manifest, "topics", &path)? {
            pinned_topics.insert(
                text(topic, "topic_path", &path)?.to_string(),
                text(topic, "sha256", &path)?.to_string(),
            );
        }
    }
    let topic_aliases = rules["source_topics"]
        .as_object()
        .ok_or("IMS applicability source_topics must be an object")?;
    require(
        topic_aliases.len() == 11,
        "IMS applicability topic scope drifted",
    )?;
    for (alias, topic) in topic_aliases {
        let path = topic
            .as_str()
            .ok_or_else(|| format!("IMS applicability topic {alias} is not a string"))?;
        require(
            pinned_topics.contains_key(path),
            &format!("IMS applicability topic {alias} is not in a verified manifest"),
        )?;
    }
    let profiles = rules["profiles"]
        .as_object()
        .ok_or("IMS applicability profiles must be an object")?;
    require(
        profiles.len() == 25,
        "IMS applicability profile count drifted",
    )?;
    let families = array(&rules, "families", &rules_path)?;
    require(
        families.len() == 25,
        "IMS applicability must cover 25 families",
    )?;

    let mut source = String::from("// @generated by `cargo xtask ims-catalog`; do not edit.\n");
    source.push_str(
        "// Call-site validation only; no executed, recovered, or differential credit.\n\n",
    );
    source.push_str(&format!(
        "pub const IMS_CALL_APPLICABILITY_RULES_SHA256: &str = {:?};\n",
        format!("sha256:{}", file_digest(&rules_path)?)
    ));
    source.push_str("pub const IMS_CALL_APPLICABILITY: &[ImsCallApplicabilityDescriptor] = &[\n");
    let mut used_profiles = BTreeSet::new();
    for (index, family) in families.iter().enumerate() {
        let entry = family
            .as_array()
            .ok_or("IMS applicability family must be [ordinal, profiles]")?;
        require(
            entry.len() == 2,
            "IMS applicability family tuple width drifted",
        )?;
        let ordinal = index + 1;
        require(
            entry[0].as_u64() == Some(ordinal as u64),
            &format!("IMS applicability family {ordinal} is out of order"),
        )?;
        let row = &rows[index];
        let official_row = text(row, "id", &catalog_path)?;
        require(
            official_row == format!("{BASELINE}:dli-call-families:{ordinal:04}"),
            "IMS applicability catalog row drifted",
        )?;
        let call_label = text(row, "label", &catalog_path)?
            .split_once(" call")
            .ok_or("IMS applicability call label is malformed")?
            .0;
        let command_label = text(row, "source_locator", &catalog_path)?
            .split_once(";command:")
            .ok_or("IMS applicability command locator is malformed")?
            .1
            .split_once(" command")
            .or_else(|| {
                text(row, "source_locator", &catalog_path)
                    .ok()?
                    .split_once(";command:")?
                    .1
                    .split_once(" call")
            })
            .ok_or("IMS applicability command label is malformed")?
            .0;
        let calls = names(call_label, official_row)?;
        let commands = names(command_label, official_row)?;
        source.push_str(&format!(
            "ImsCallApplicabilityDescriptor {{ ordinal: {ordinal}, official_row: {official_row:?}, call_names: {}, command_names: {}, executed: false, variants: &[\n",
            str_slice(&calls),
            str_slice(&commands)
        ));
        let profile_names = entry[1]
            .as_array()
            .ok_or("IMS applicability family profiles must be an array")?;
        require(
            !profile_names.is_empty(),
            "IMS applicability family has no profiles",
        )?;
        let mut local_profiles = BTreeSet::new();
        for name in profile_names {
            let name = name.as_str().ok_or("IMS profile name is not a string")?;
            require(
                local_profiles.insert(name),
                "IMS applicability family repeats a profile",
            )?;
            let profile = profiles
                .get(name)
                .ok_or_else(|| format!("IMS applicability profile {name} is missing"))?;
            used_profiles.insert(name);
            let context = class(&rules, "context_classes", profile, "contexts")?;
            let organizations = class(&rules, "organization_classes", profile, "organizations")?;
            let options = class(&rules, "option_classes", profile, "options")?;
            let ssa = class(&rules, "ssa_classes", profile, "ssa")?;
            let pcb = text(profile, "pcb", &rules_path)?;
            require(
                matches!(pcb, "none" | "database" | "gsam" | "io" | "alternate"),
                &format!("IMS applicability profile {name} has an invalid PCB kind"),
            )?;
            let names = optional_strings(profile.get("names"))?;
            require(
                names
                    .iter()
                    .all(|name| calls.contains(name) || commands.contains(name)),
                &format!("IMS applicability profile {name} has a name outside its family"),
            )?;
            let sources = strings(array(profile, "sources", &rules_path)?)?;
            require(
                !sources.is_empty(),
                "IMS applicability profile has no source",
            )?;
            let mut source_paths = Vec::new();
            for alias in sources {
                let topic = topic_aliases
                    .get(&alias)
                    .and_then(Value::as_str)
                    .ok_or_else(|| format!("IMS applicability source alias {alias} is missing"))?;
                source_paths.push(topic.to_string());
            }
            let context_expr = enum_slice(&context, context_variant)?;
            let option_expr = enum_slice(&options, option_variant)?;
            let ssa_expr = enum_slice(&ssa, ssa_variant)?;
            let pcb_expr = if pcb == "none" {
                "None".to_string()
            } else {
                format!("Some(ImsPcbKind::{})", pcb_variant(pcb)?)
            };
            source.push_str(&format!(
                "ImsCallVariant {{ profile: {name:?}, contexts: &{context_expr}, pcb_kind: {pcb_expr}, organizations: {}, processing_options: &{option_expr}, ssa_forms: &{ssa_expr}, names: {}, source_topics: {} }},\n",
                str_slice(&organizations),
                str_slice(&names),
                str_slice(&source_paths)
            ));
        }
        source.push_str("] },\n");
    }
    require(
        used_profiles.len() == profiles.len(),
        "IMS applicability has unused profiles",
    )?;
    source.push_str("];\n\nimpl ImsApplicabilityProblem {\n");
    source.push_str("pub const fn code(self) -> &'static str { match self {\n");
    let diagnostics = array(&rules, "diagnostics", &rules_path)?;
    require(
        diagnostics.len() == 9,
        "IMS applicability diagnostic count drifted",
    )?;
    let mut seen = BTreeSet::new();
    for (index, diagnostic) in diagnostics.iter().enumerate() {
        let fields = diagnostic
            .as_array()
            .ok_or("IMS applicability diagnostic must be a tuple")?;
        require(
            fields.len() == 3,
            "IMS applicability diagnostic width drifted",
        )?;
        let variant = fields[0]
            .as_str()
            .ok_or("IMS diagnostic variant is not a string")?;
        let code = fields[1]
            .as_str()
            .ok_or("IMS diagnostic code is not a string")?;
        let message = fields[2]
            .as_str()
            .ok_or("IMS diagnostic message is not a string")?;
        require(
            seen.insert(variant) && code == format!("IMS1401-{:03}", index + 1),
            "IMS applicability diagnostic identities drifted",
        )?;
        source.push_str(&format!("Self::{variant} => {code:?},\n"));
        require(!message.is_empty(), "IMS diagnostic message is empty")?;
    }
    source.push_str("} }\npub const fn message(self) -> &'static str { match self {\n");
    for diagnostic in diagnostics {
        let fields = diagnostic
            .as_array()
            .ok_or("IMS diagnostic is not an array")?;
        source.push_str(&format!(
            "Self::{} => {:?},\n",
            fields[0].as_str().ok_or("IMS diagnostic variant missing")?,
            fields[2].as_str().ok_or("IMS diagnostic message missing")?
        ));
    }
    source.push_str("} }\n}\n");
    format_generated_rust(source)
}

fn class(rules: &Value, section: &str, profile: &Value, key: &str) -> TaskResult<Vec<String>> {
    let name = profile[key]
        .as_str()
        .ok_or_else(|| format!("IMS profile {key} class is missing"))?;
    let members = rules[section][name]
        .as_array()
        .ok_or_else(|| format!("IMS {section} class {name} is missing"))?;
    strings(members)
}

fn strings(values: &[Value]) -> TaskResult<Vec<String>> {
    values
        .iter()
        .map(|value| {
            value
                .as_str()
                .map(str::to_string)
                .ok_or_else(|| "IMS applicability class contains a non-string".to_string())
        })
        .collect()
}

fn optional_strings(value: Option<&Value>) -> TaskResult<Vec<String>> {
    value
        .map(|value| {
            value
                .as_array()
                .ok_or_else(|| "IMS applicability names are not an array".to_string())
                .and_then(|values| strings(values))
        })
        .unwrap_or_else(|| Ok(Vec::new()))
}

fn str_slice(values: &[String]) -> String {
    format!(
        "&[{}]",
        values
            .iter()
            .map(|value| format!("{value:?}"))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn enum_slice(
    values: &[String],
    mapper: fn(&str) -> TaskResult<&'static str>,
) -> TaskResult<String> {
    Ok(format!(
        "[{}]",
        values
            .iter()
            .map(|value| mapper(value).map(str::to_string))
            .collect::<TaskResult<Vec<_>>>()?
            .join(", ")
    ))
}

fn context_variant(value: &str) -> TaskResult<&'static str> {
    match value {
        "db-dc" => Ok("ImsExecutionContext::DbDc"),
        "dbctl" => Ok("ImsExecutionContext::Dbctl"),
        "dcctl" => Ok("ImsExecutionContext::Dcctl"),
        "db-batch" => Ok("ImsExecutionContext::DbBatch"),
        "tm-batch" => Ok("ImsExecutionContext::TmBatch"),
        _ => Err(format!("unknown IMS execution context {value}")),
    }
}

fn pcb_variant(value: &str) -> TaskResult<&'static str> {
    match value {
        "database" => Ok("Database"),
        "gsam" => Ok("Gsam"),
        "io" => Ok("Io"),
        "alternate" => Ok("Alternate"),
        _ => Err(format!("unknown IMS PCB kind {value}")),
    }
}

fn option_variant(value: &str) -> TaskResult<&'static str> {
    match value {
        "read" => Ok("ImsProcessingOptionClass::Read"),
        "replace" => Ok("ImsProcessingOptionClass::Replace"),
        "insert" => Ok("ImsProcessingOptionClass::Insert"),
        "delete" => Ok("ImsProcessingOptionClass::Delete"),
        "all" => Ok("ImsProcessingOptionClass::All"),
        "read-without-integrity" => Ok("ImsProcessingOptionClass::ReadWithoutIntegrity"),
        _ => Err(format!("unknown IMS processing option class {value}")),
    }
}

fn ssa_variant(value: &str) -> TaskResult<&'static str> {
    match value {
        "absent" => Ok("ImsSsaForm::Absent"),
        "unqualified" => Ok("ImsSsaForm::Unqualified"),
        "qualified" => Ok("ImsSsaForm::Qualified"),
        "path" => Ok("ImsSsaForm::Path"),
        "subset-pointer" => Ok("ImsSsaForm::SubsetPointer"),
        "concatenated-key" => Ok("ImsSsaForm::ConcatenatedKey"),
        "record-search-argument" => Ok("ImsSsaForm::RecordSearchArgument"),
        _ => Err(format!("unknown IMS SSA form {value}")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reviewed_projection_closes_all_rows_and_stable_diagnostics() {
        let root = repository_root().unwrap();
        let source = String::from_utf8(render(&root).unwrap()).unwrap();
        assert_eq!(
            source.matches("ImsCallApplicabilityDescriptor {").count(),
            25
        );
        assert!(source.contains("IMS1401-001"));
        assert!(source.contains("IMS1401-009"));
        assert!(source.contains("ImsSsaForm::RecordSearchArgument"));
    }

    #[test]
    fn unknown_equivalence_classes_fail_closed() {
        assert!(context_variant("online").is_err());
        assert!(option_variant("unknown").is_err());
        assert!(ssa_variant("unknown").is_err());
    }
}
