[package]
name = "mainframe-env-batch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mainframe-env-application.workspace = true
mainframe-env-execution-api.workspace = true
mainframe-env-diagnostics.workspace = true
mainframe-env-encoding.workspace = true
mainframe-env-host-api.workspace = true
mainframe-env-source.workspace = true
mainframe-env-store-api.workspace = true
rowan.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
mainframe-env-dataset.workspace = true
mainframe-env-spool.workspace = true
jsonschema.workspace = true
mainframe-env-store = { path = "../../stores/mainframe-env-store" }
