[package]
name = "mainframe-env-batch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mainframe-env-execution-api.workspace = true
mainframe-env-host-api.workspace = true
mainframe-env-store-api.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
mainframe-env-store = { path = "../../stores/mainframe-env-store" }
