[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
base64.workspace = true
clap.workspace = true
flate2.workspace = true
in_toto_attestation.workspace = true
mainframe-env-conformance.workspace = true
mainframe-env-coverage.workspace = true
mainframe-env-ir.workspace = true
jsonschema.workspace = true
serde_json.workspace = true
sha2.workspace = true
toml.workspace = true
protobuf-json-mapping.workspace = true
ring.workspace = true

[dev-dependencies]
mainframe-env-compiler.workspace = true
mainframe-env-compiler-api.workspace = true
mainframe-env-execution-api.workspace = true
mainframe-env-interpreter.workspace = true
mainframe-env-source.workspace = true
