// @generated by tools/generate_mq_mqi_registry.py; do not edit.
/// Exact reviewed private property projection; no execution credit.
pub const MQ_PROPERTY_PROFILE_SHA256: &str = "8da951d82502333755eee8f45447c2c17f699bbe436e93d3bde1c57a6d60dfd4";
pub(super) const MQCMHO_CURRENT_VERSION: i32 = 1;
pub(super) const MQCMHO_DEFAULT_VALIDATION: i32 = 0;
pub(super) const MQCMHO_NONE: i32 = 0;
pub(super) const MQCMHO_NO_VALIDATION: i32 = 1;
pub(super) const MQCMHO_VALIDATE: i32 = 2;
pub(super) const MQCMHO_VERSION_1: i32 = 1;
pub(super) const MQCOPY_ALL: i32 = 1;
pub(super) const MQCOPY_DEFAULT: i32 = 22;
pub(super) const MQCOPY_FORWARD: i32 = 2;
pub(super) const MQCOPY_NONE: i32 = 0;
pub(super) const MQCOPY_PUBLISH: i32 = 4;
pub(super) const MQCOPY_REPLY: i32 = 8;
pub(super) const MQCOPY_REPORT: i32 = 16;
pub(super) const MQDMHO_CURRENT_VERSION: i32 = 1;
pub(super) const MQDMHO_NONE: i32 = 0;
pub(super) const MQDMHO_VERSION_1: i32 = 1;
pub(super) const MQDMPO_CURRENT_VERSION: i32 = 1;
pub(super) const MQDMPO_DEL_FIRST: i32 = 0;
pub(super) const MQDMPO_DEL_PROP_UNDER_CURSOR: i32 = 1;
pub(super) const MQDMPO_NONE: i32 = 0;
pub(super) const MQDMPO_VERSION_1: i32 = 1;
pub(super) const MQENC_DECIMAL_MASK: i32 = 240;
pub(super) const MQENC_DECIMAL_NORMAL: i32 = 16;
pub(super) const MQENC_DECIMAL_REVERSED: i32 = 32;
pub(super) const MQENC_DECIMAL_UNDEFINED: i32 = 0;
pub(super) const MQENC_FLOAT_IEEE_NORMAL: i32 = 256;
pub(super) const MQENC_FLOAT_IEEE_REVERSED: i32 = 512;
pub(super) const MQENC_FLOAT_MASK: i32 = 3840;
pub(super) const MQENC_FLOAT_S390: i32 = 768;
pub(super) const MQENC_FLOAT_TNS: i32 = 1024;
pub(super) const MQENC_FLOAT_UNDEFINED: i32 = 0;
pub(super) const MQENC_INTEGER_MASK: i32 = 15;
pub(super) const MQENC_INTEGER_NORMAL: i32 = 1;
pub(super) const MQENC_INTEGER_REVERSED: i32 = 2;
pub(super) const MQENC_INTEGER_UNDEFINED: i32 = 0;
pub(super) const MQENC_NATIVE_ZOS: i32 = 785;
pub(super) const MQENC_RESERVED_MASK: i32 = -4096;
pub(super) const MQIMPO_CONVERT_TYPE: i32 = 2;
pub(super) const MQIMPO_CONVERT_VALUE: i32 = 32;
pub(super) const MQIMPO_CURRENT_VERSION: i32 = 1;
pub(super) const MQIMPO_INQ_FIRST: i32 = 0;
pub(super) const MQIMPO_INQ_NEXT: i32 = 8;
pub(super) const MQIMPO_INQ_PROP_UNDER_CURSOR: i32 = 16;
pub(super) const MQIMPO_NONE: i32 = 0;
pub(super) const MQIMPO_QUERY_LENGTH: i32 = 4;
pub(super) const MQIMPO_VERSION_1: i32 = 1;
pub(super) const MQPD_ACCEPT_UNSUP_IF_XMIT_MASK: i32 = 1047552;
pub(super) const MQPD_ACCEPT_UNSUP_MASK: i32 = 1023;
pub(super) const MQPD_CURRENT_VERSION: i32 = 1;
pub(super) const MQPD_NONE: i32 = 0;
pub(super) const MQPD_NO_CONTEXT: i32 = 0;
pub(super) const MQPD_REJECT_UNSUP_MASK: i32 = -1048576;
pub(super) const MQPD_SUPPORT_OPTIONAL: i32 = 1;
pub(super) const MQPD_SUPPORT_REQUIRED: i32 = 1048576;
pub(super) const MQPD_SUPPORT_REQUIRED_IF_LOCAL: i32 = 1024;
pub(super) const MQPD_USER_CONTEXT: i32 = 1;
pub(super) const MQPD_VERSION_1: i32 = 1;
pub(super) const MQSMPO_APPEND_PROPERTY: i32 = 4;
pub(super) const MQSMPO_CURRENT_VERSION: i32 = 1;
pub(super) const MQSMPO_NONE: i32 = 0;
pub(super) const MQSMPO_SET_FIRST: i32 = 0;
pub(super) const MQSMPO_SET_PROP_AFTER_CURSOR: i32 = 2;
pub(super) const MQSMPO_SET_PROP_BEFORE_CURSOR: i32 = 8;
pub(super) const MQSMPO_SET_PROP_UNDER_CURSOR: i32 = 1;
pub(super) const MQSMPO_VERSION_1: i32 = 1;
pub(super) const MQTYPE_AS_SET: i32 = 0;
pub(super) const MQTYPE_BOOLEAN: i32 = 4;
pub(super) const MQTYPE_BYTE_STRING: i32 = 8;
pub(super) const MQTYPE_FLOAT32: i32 = 256;
pub(super) const MQTYPE_FLOAT64: i32 = 512;
pub(super) const MQTYPE_INT16: i32 = 32;
pub(super) const MQTYPE_INT32: i32 = 64;
pub(super) const MQTYPE_INT64: i32 = 128;
pub(super) const MQTYPE_INT8: i32 = 16;
pub(super) const MQTYPE_LONG: i32 = 64;
pub(super) const MQTYPE_NULL: i32 = 2;
pub(super) const MQTYPE_STRING: i32 = 1024;
pub(super) const NUMERIC_IDENTITIES: &[MqPropertyNumericFact] = &[
    MqPropertyNumericFact { symbol: "MQCMHO_CURRENT_VERSION", value: MQCMHO_CURRENT_VERSION },
    MqPropertyNumericFact { symbol: "MQCMHO_DEFAULT_VALIDATION", value: MQCMHO_DEFAULT_VALIDATION },
    MqPropertyNumericFact { symbol: "MQCMHO_NONE", value: MQCMHO_NONE },
    MqPropertyNumericFact { symbol: "MQCMHO_NO_VALIDATION", value: MQCMHO_NO_VALIDATION },
    MqPropertyNumericFact { symbol: "MQCMHO_VALIDATE", value: MQCMHO_VALIDATE },
    MqPropertyNumericFact { symbol: "MQCMHO_VERSION_1", value: MQCMHO_VERSION_1 },
    MqPropertyNumericFact { symbol: "MQCOPY_ALL", value: MQCOPY_ALL },
    MqPropertyNumericFact { symbol: "MQCOPY_DEFAULT", value: MQCOPY_DEFAULT },
    MqPropertyNumericFact { symbol: "MQCOPY_FORWARD", value: MQCOPY_FORWARD },
    MqPropertyNumericFact { symbol: "MQCOPY_NONE", value: MQCOPY_NONE },
    MqPropertyNumericFact { symbol: "MQCOPY_PUBLISH", value: MQCOPY_PUBLISH },
    MqPropertyNumericFact { symbol: "MQCOPY_REPLY", value: MQCOPY_REPLY },
    MqPropertyNumericFact { symbol: "MQCOPY_REPORT", value: MQCOPY_REPORT },
    MqPropertyNumericFact { symbol: "MQDMHO_CURRENT_VERSION", value: MQDMHO_CURRENT_VERSION },
    MqPropertyNumericFact { symbol: "MQDMHO_NONE", value: MQDMHO_NONE },
    MqPropertyNumericFact { symbol: "MQDMHO_VERSION_1", value: MQDMHO_VERSION_1 },
    MqPropertyNumericFact { symbol: "MQDMPO_CURRENT_VERSION", value: MQDMPO_CURRENT_VERSION },
    MqPropertyNumericFact { symbol: "MQDMPO_DEL_FIRST", value: MQDMPO_DEL_FIRST },
    MqPropertyNumericFact { symbol: "MQDMPO_DEL_PROP_UNDER_CURSOR", value: MQDMPO_DEL_PROP_UNDER_CURSOR },
    MqPropertyNumericFact { symbol: "MQDMPO_NONE", value: MQDMPO_NONE },
    MqPropertyNumericFact { symbol: "MQDMPO_VERSION_1", value: MQDMPO_VERSION_1 },
    MqPropertyNumericFact { symbol: "MQENC_DECIMAL_MASK", value: MQENC_DECIMAL_MASK },
    MqPropertyNumericFact { symbol: "MQENC_DECIMAL_NORMAL", value: MQENC_DECIMAL_NORMAL },
    MqPropertyNumericFact { symbol: "MQENC_DECIMAL_REVERSED", value: MQENC_DECIMAL_REVERSED },
    MqPropertyNumericFact { symbol: "MQENC_DECIMAL_UNDEFINED", value: MQENC_DECIMAL_UNDEFINED },
    MqPropertyNumericFact { symbol: "MQENC_FLOAT_IEEE_NORMAL", value: MQENC_FLOAT_IEEE_NORMAL },
    MqPropertyNumericFact { symbol: "MQENC_FLOAT_IEEE_REVERSED", value: MQENC_FLOAT_IEEE_REVERSED },
    MqPropertyNumericFact { symbol: "MQENC_FLOAT_MASK", value: MQENC_FLOAT_MASK },
    MqPropertyNumericFact { symbol: "MQENC_FLOAT_S390", value: MQENC_FLOAT_S390 },
    MqPropertyNumericFact { symbol: "MQENC_FLOAT_TNS", value: MQENC_FLOAT_TNS },
    MqPropertyNumericFact { symbol: "MQENC_FLOAT_UNDEFINED", value: MQENC_FLOAT_UNDEFINED },
    MqPropertyNumericFact { symbol: "MQENC_INTEGER_MASK", value: MQENC_INTEGER_MASK },
    MqPropertyNumericFact { symbol: "MQENC_INTEGER_NORMAL", value: MQENC_INTEGER_NORMAL },
    MqPropertyNumericFact { symbol: "MQENC_INTEGER_REVERSED", value: MQENC_INTEGER_REVERSED },
    MqPropertyNumericFact { symbol: "MQENC_INTEGER_UNDEFINED", value: MQENC_INTEGER_UNDEFINED },
    MqPropertyNumericFact { symbol: "MQENC_NATIVE_ZOS", value: MQENC_NATIVE_ZOS },
    MqPropertyNumericFact { symbol: "MQENC_RESERVED_MASK", value: MQENC_RESERVED_MASK },
    MqPropertyNumericFact { symbol: "MQIMPO_CONVERT_TYPE", value: MQIMPO_CONVERT_TYPE },
    MqPropertyNumericFact { symbol: "MQIMPO_CONVERT_VALUE", value: MQIMPO_CONVERT_VALUE },
    MqPropertyNumericFact { symbol: "MQIMPO_CURRENT_VERSION", value: MQIMPO_CURRENT_VERSION },
    MqPropertyNumericFact { symbol: "MQIMPO_INQ_FIRST", value: MQIMPO_INQ_FIRST },
    MqPropertyNumericFact { symbol: "MQIMPO_INQ_NEXT", value: MQIMPO_INQ_NEXT },
    MqPropertyNumericFact { symbol: "MQIMPO_INQ_PROP_UNDER_CURSOR", value: MQIMPO_INQ_PROP_UNDER_CURSOR },
    MqPropertyNumericFact { symbol: "MQIMPO_NONE", value: MQIMPO_NONE },
    MqPropertyNumericFact { symbol: "MQIMPO_QUERY_LENGTH", value: MQIMPO_QUERY_LENGTH },
    MqPropertyNumericFact { symbol: "MQIMPO_VERSION_1", value: MQIMPO_VERSION_1 },
    MqPropertyNumericFact { symbol: "MQPD_ACCEPT_UNSUP_IF_XMIT_MASK", value: MQPD_ACCEPT_UNSUP_IF_XMIT_MASK },
    MqPropertyNumericFact { symbol: "MQPD_ACCEPT_UNSUP_MASK", value: MQPD_ACCEPT_UNSUP_MASK },
    MqPropertyNumericFact { symbol: "MQPD_CURRENT_VERSION", value: MQPD_CURRENT_VERSION },
    MqPropertyNumericFact { symbol: "MQPD_NONE", value: MQPD_NONE },
    MqPropertyNumericFact { symbol: "MQPD_NO_CONTEXT", value: MQPD_NO_CONTEXT },
    MqPropertyNumericFact { symbol: "MQPD_REJECT_UNSUP_MASK", value: MQPD_REJECT_UNSUP_MASK },
    MqPropertyNumericFact { symbol: "MQPD_SUPPORT_OPTIONAL", value: MQPD_SUPPORT_OPTIONAL },
    MqPropertyNumericFact { symbol: "MQPD_SUPPORT_REQUIRED", value: MQPD_SUPPORT_REQUIRED },
    MqPropertyNumericFact { symbol: "MQPD_SUPPORT_REQUIRED_IF_LOCAL", value: MQPD_SUPPORT_REQUIRED_IF_LOCAL },
    MqPropertyNumericFact { symbol: "MQPD_USER_CONTEXT", value: MQPD_USER_CONTEXT },
    MqPropertyNumericFact { symbol: "MQPD_VERSION_1", value: MQPD_VERSION_1 },
    MqPropertyNumericFact { symbol: "MQSMPO_APPEND_PROPERTY", value: MQSMPO_APPEND_PROPERTY },
    MqPropertyNumericFact { symbol: "MQSMPO_CURRENT_VERSION", value: MQSMPO_CURRENT_VERSION },
    MqPropertyNumericFact { symbol: "MQSMPO_NONE", value: MQSMPO_NONE },
    MqPropertyNumericFact { symbol: "MQSMPO_SET_FIRST", value: MQSMPO_SET_FIRST },
    MqPropertyNumericFact { symbol: "MQSMPO_SET_PROP_AFTER_CURSOR", value: MQSMPO_SET_PROP_AFTER_CURSOR },
    MqPropertyNumericFact { symbol: "MQSMPO_SET_PROP_BEFORE_CURSOR", value: MQSMPO_SET_PROP_BEFORE_CURSOR },
    MqPropertyNumericFact { symbol: "MQSMPO_SET_PROP_UNDER_CURSOR", value: MQSMPO_SET_PROP_UNDER_CURSOR },
    MqPropertyNumericFact { symbol: "MQSMPO_VERSION_1", value: MQSMPO_VERSION_1 },
    MqPropertyNumericFact { symbol: "MQTYPE_AS_SET", value: MQTYPE_AS_SET },
    MqPropertyNumericFact { symbol: "MQTYPE_BOOLEAN", value: MQTYPE_BOOLEAN },
    MqPropertyNumericFact { symbol: "MQTYPE_BYTE_STRING", value: MQTYPE_BYTE_STRING },
    MqPropertyNumericFact { symbol: "MQTYPE_FLOAT32", value: MQTYPE_FLOAT32 },
    MqPropertyNumericFact { symbol: "MQTYPE_FLOAT64", value: MQTYPE_FLOAT64 },
    MqPropertyNumericFact { symbol: "MQTYPE_INT16", value: MQTYPE_INT16 },
    MqPropertyNumericFact { symbol: "MQTYPE_INT32", value: MQTYPE_INT32 },
    MqPropertyNumericFact { symbol: "MQTYPE_INT64", value: MQTYPE_INT64 },
    MqPropertyNumericFact { symbol: "MQTYPE_INT8", value: MQTYPE_INT8 },
    MqPropertyNumericFact { symbol: "MQTYPE_LONG", value: MQTYPE_LONG },
    MqPropertyNumericFact { symbol: "MQTYPE_NULL", value: MQTYPE_NULL },
    MqPropertyNumericFact { symbol: "MQTYPE_STRING", value: MQTYPE_STRING },
];
pub(super) fn value_width(kind: MqPropertyType) -> Option<usize> {
    match kind {
        MqPropertyType::Boolean => Some(4),
        MqPropertyType::ByteString => None,
        MqPropertyType::Int8 => Some(1),
        MqPropertyType::Int16 => Some(2),
        MqPropertyType::Int32 => Some(4),
        MqPropertyType::Int64 => Some(8),
        MqPropertyType::Float32 => Some(4),
        MqPropertyType::Float64 => Some(8),
        MqPropertyType::String => None,
        MqPropertyType::Null => Some(0),
    }
}
pub(super) const MQCMHO_STRUC_ID: [u8; 4] = *b"CMHO";
pub(super) const MQDMHO_STRUC_ID: [u8; 4] = *b"DMHO";
pub(super) const MQDMPO_STRUC_ID: [u8; 4] = *b"DMPO";
pub(super) const MQIMPO_STRUC_ID: [u8; 4] = *b"IMPO";
pub(super) const MQPD_STRUC_ID: [u8; 4] = *b"PD  ";
pub(super) const MQSMPO_STRUC_ID: [u8; 4] = *b"SMPO";
pub(super) const PROPERTY_UTF8_CCSID: i32 = 1208;
pub(super) const MD_FIELDS: &[MqPropertyMdField] = &[
    MqPropertyMdField { name: "Report", kind: MqPropertyType::Int32, width: 4 },
    MqPropertyMdField { name: "MsgType", kind: MqPropertyType::Int32, width: 4 },
    MqPropertyMdField { name: "Expiry", kind: MqPropertyType::Int32, width: 4 },
    MqPropertyMdField { name: "Feedback", kind: MqPropertyType::Int32, width: 4 },
    MqPropertyMdField { name: "Encoding", kind: MqPropertyType::Int32, width: 4 },
    MqPropertyMdField { name: "CodedCharSetId", kind: MqPropertyType::Int32, width: 4 },
    MqPropertyMdField { name: "Format", kind: MqPropertyType::String, width: 8 },
    MqPropertyMdField { name: "Priority", kind: MqPropertyType::Int32, width: 4 },
    MqPropertyMdField { name: "Persistence", kind: MqPropertyType::Int32, width: 4 },
    MqPropertyMdField { name: "MsgId", kind: MqPropertyType::ByteString, width: 24 },
    MqPropertyMdField { name: "CorrelId", kind: MqPropertyType::ByteString, width: 24 },
    MqPropertyMdField { name: "BackoutCount", kind: MqPropertyType::Int32, width: 4 },
    MqPropertyMdField { name: "ReplyToQ", kind: MqPropertyType::String, width: 48 },
    MqPropertyMdField { name: "ReplyToQMgr", kind: MqPropertyType::String, width: 48 },
    MqPropertyMdField { name: "UserIdentifier", kind: MqPropertyType::String, width: 12 },
    MqPropertyMdField { name: "AccountingToken", kind: MqPropertyType::ByteString, width: 32 },
    MqPropertyMdField { name: "ApplIdentityData", kind: MqPropertyType::String, width: 32 },
    MqPropertyMdField { name: "PutApplType", kind: MqPropertyType::Int32, width: 4 },
    MqPropertyMdField { name: "PutApplName", kind: MqPropertyType::String, width: 28 },
    MqPropertyMdField { name: "PutDate", kind: MqPropertyType::String, width: 8 },
    MqPropertyMdField { name: "PutTime", kind: MqPropertyType::String, width: 8 },
    MqPropertyMdField { name: "ApplOriginData", kind: MqPropertyType::String, width: 4 },
];
pub(super) fn initial_md() -> crate::mq_md_value::MqMdValue {
    crate::mq_md_value::MqMdValue::V1 {
        characters: crate::mq_md_value::MqMdCharacterEncoding::AsciiCompatible,
        fields: crate::mq_md_value::MqMdFields {
            struc_id: *b"MD  ",
            report: 0,
            msg_type: 8,
            expiry: -1,
            feedback: 0,
            encoding: MQENC_NATIVE_ZOS,
            coded_char_set_id: 0,
            format: [b' '; 8],
            priority: -1,
            persistence: 2,
            msg_id: [0; 24],
            correl_id: [0; 24],
            backout_count: 0,
            reply_to_q: [b' '; 48],
            reply_to_q_mgr: [b' '; 48],
            user_identifier: [b' '; 12],
            accounting_token: [0; 32],
            appl_identity_data: [b' '; 32],
            put_appl_type: 0,
            put_appl_name: [b' '; 28],
            put_date: [b' '; 8],
            put_time: [b' '; 8],
            appl_origin_data: [b' '; 4],
        },
    }
}
pub(super) fn md_bytes(md: &crate::mq_md_value::MqMdValue, name: &str) -> Option<Vec<u8>> {
    let fields=md.fields();
    Some(match name {
        "Report" => fields.report.to_be_bytes().to_vec(),
        "MsgType" => fields.msg_type.to_be_bytes().to_vec(),
        "Expiry" => fields.expiry.to_be_bytes().to_vec(),
        "Feedback" => fields.feedback.to_be_bytes().to_vec(),
        "Encoding" => fields.encoding.to_be_bytes().to_vec(),
        "CodedCharSetId" => fields.coded_char_set_id.to_be_bytes().to_vec(),
        "Format" => fields.format.to_vec(),
        "Priority" => fields.priority.to_be_bytes().to_vec(),
        "Persistence" => fields.persistence.to_be_bytes().to_vec(),
        "MsgId" => fields.msg_id.to_vec(),
        "CorrelId" => fields.correl_id.to_vec(),
        "BackoutCount" => fields.backout_count.to_be_bytes().to_vec(),
        "ReplyToQ" => fields.reply_to_q.to_vec(),
        "ReplyToQMgr" => fields.reply_to_q_mgr.to_vec(),
        "UserIdentifier" => fields.user_identifier.to_vec(),
        "AccountingToken" => fields.accounting_token.to_vec(),
        "ApplIdentityData" => fields.appl_identity_data.to_vec(),
        "PutApplType" => fields.put_appl_type.to_be_bytes().to_vec(),
        "PutApplName" => fields.put_appl_name.to_vec(),
        "PutDate" => fields.put_date.to_vec(),
        "PutTime" => fields.put_time.to_vec(),
        "ApplOriginData" => fields.appl_origin_data.to_vec(),
        _ => return None,
    })
}
pub(super) fn set_md_bytes(md: &mut crate::mq_md_value::MqMdValue, name: &str, bytes: &[u8]) -> Result<(), MqPropertyProblem> {
    let crate::mq_md_value::MqMdValue::V1 { fields, .. } = md else { return Err(MqPropertyProblem::Unsupported); };
    match name {
        "Report" if bytes.len()==4 => { fields.report=i32::from_be_bytes(bytes.try_into().map_err(|_| MqPropertyProblem::Value)?); },
        "MsgType" if bytes.len()==4 => { fields.msg_type=i32::from_be_bytes(bytes.try_into().map_err(|_| MqPropertyProblem::Value)?); },
        "Expiry" if bytes.len()==4 => { fields.expiry=i32::from_be_bytes(bytes.try_into().map_err(|_| MqPropertyProblem::Value)?); },
        "Feedback" if bytes.len()==4 => { fields.feedback=i32::from_be_bytes(bytes.try_into().map_err(|_| MqPropertyProblem::Value)?); },
        "Encoding" if bytes.len()==4 => { fields.encoding=i32::from_be_bytes(bytes.try_into().map_err(|_| MqPropertyProblem::Value)?); },
        "CodedCharSetId" if bytes.len()==4 => { fields.coded_char_set_id=i32::from_be_bytes(bytes.try_into().map_err(|_| MqPropertyProblem::Value)?); },
        "Format" if bytes.len()==8 => { fields.format.copy_from_slice(bytes); },
        "Priority" if bytes.len()==4 => { fields.priority=i32::from_be_bytes(bytes.try_into().map_err(|_| MqPropertyProblem::Value)?); },
        "Persistence" if bytes.len()==4 => { fields.persistence=i32::from_be_bytes(bytes.try_into().map_err(|_| MqPropertyProblem::Value)?); },
        "MsgId" if bytes.len()==24 => { fields.msg_id.copy_from_slice(bytes); },
        "CorrelId" if bytes.len()==24 => { fields.correl_id.copy_from_slice(bytes); },
        "BackoutCount" if bytes.len()==4 => { fields.backout_count=i32::from_be_bytes(bytes.try_into().map_err(|_| MqPropertyProblem::Value)?); },
        "ReplyToQ" if bytes.len()==48 => { fields.reply_to_q.copy_from_slice(bytes); },
        "ReplyToQMgr" if bytes.len()==48 => { fields.reply_to_q_mgr.copy_from_slice(bytes); },
        "UserIdentifier" if bytes.len()==12 => { fields.user_identifier.copy_from_slice(bytes); },
        "AccountingToken" if bytes.len()==32 => { fields.accounting_token.copy_from_slice(bytes); },
        "ApplIdentityData" if bytes.len()==32 => { fields.appl_identity_data.copy_from_slice(bytes); },
        "PutApplType" if bytes.len()==4 => { fields.put_appl_type=i32::from_be_bytes(bytes.try_into().map_err(|_| MqPropertyProblem::Value)?); },
        "PutApplName" if bytes.len()==28 => { fields.put_appl_name.copy_from_slice(bytes); },
        "PutDate" if bytes.len()==8 => { fields.put_date.copy_from_slice(bytes); },
        "PutTime" if bytes.len()==8 => { fields.put_time.copy_from_slice(bytes); },
        "ApplOriginData" if bytes.len()==4 => { fields.appl_origin_data.copy_from_slice(bytes); },
        _ => return Err(MqPropertyProblem::Value),
    }
    Ok(())
}
