use super::*;

/// Complete registry for the bounded typed CICS executable pilot.
pub const CICS_EXECUTABLE_DESCRIPTORS: [CicsExecutableDescriptor; 106] = [
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Deq,
        namespace: "cics.task",
        name: "deq",
        major: 1,
        effects: DEQ_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Enq,
        namespace: "cics.task",
        name: "enq",
        major: 1,
        effects: ENQ_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Read,
        namespace: "cics.file",
        name: "read",
        major: 1,
        effects: READ_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Rewrite,
        namespace: "cics.file",
        name: "rewrite",
        major: 1,
        effects: REWRITE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Syncpoint,
        namespace: "cics.recovery",
        name: "syncpoint",
        major: 1,
        effects: SYNCPOINT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ChangeTask,
        namespace: "cics.task",
        name: "change-task",
        major: 1,
        effects: CHANGE_TASK_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Suspend,
        namespace: "cics.task",
        name: "suspend",
        major: 1,
        effects: SUSPEND_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SetAssociationUserCorrData,
        namespace: "cics.task",
        name: "set-association-usercorrdata",
        major: 1,
        effects: SET_ASSOCIATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::AddressSet,
        namespace: "cics.task",
        name: "address-set",
        major: 1,
        effects: ADDRESS_SET_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::PopHandle,
        namespace: "cics.task",
        name: "pop-handle",
        major: 1,
        effects: HANDLE_STACK_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::PushHandle,
        namespace: "cics.task",
        name: "push-handle",
        major: 1,
        effects: HANDLE_STACK_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::IgnoreCondition,
        namespace: "cics.task",
        name: "ignore-condition",
        major: 1,
        effects: IGNORE_CONDITION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::HandleCondition,
        namespace: "cics.task",
        name: "handle-condition",
        major: 1,
        effects: IGNORE_CONDITION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::HandleAid,
        namespace: "cics.task",
        name: "handle-aid",
        major: 1,
        effects: IGNORE_CONDITION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::AsktimeEib,
        namespace: "cics.time",
        name: "asktime-eib",
        major: 1,
        effects: ASKTIME_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Asktime,
        namespace: "cics.time",
        name: "asktime",
        major: 1,
        effects: ASKTIME_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::FormatTime,
        namespace: "cics.time",
        name: "format-time",
        major: 1,
        effects: FORMAT_TIME_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Abend,
        namespace: "cics.task",
        name: "abend",
        major: 1,
        effects: ABEND_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::HandleAbend,
        namespace: "cics.task",
        name: "handle-abend",
        major: 1,
        effects: IGNORE_CONDITION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Link,
        namespace: "cics.program",
        name: "link",
        major: 1,
        effects: CONTROL_TRANSFER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Xctl,
        namespace: "cics.program",
        name: "xctl",
        major: 1,
        effects: CONTROL_TRANSFER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Return,
        namespace: "cics.task",
        name: "return",
        major: 1,
        effects: CONTROL_TRANSFER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::StartBrowse,
        namespace: "cics.file",
        name: "start-browse",
        major: 1,
        effects: READ_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ReadNext,
        namespace: "cics.file",
        name: "read-next",
        major: 1,
        effects: READ_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ReadPrev,
        namespace: "cics.file",
        name: "read-prev",
        major: 1,
        effects: READ_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::EndBrowse,
        namespace: "cics.file",
        name: "end-browse",
        major: 1,
        effects: READ_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Delete,
        namespace: "cics.file",
        name: "delete",
        major: 1,
        effects: REWRITE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Write,
        namespace: "cics.file",
        name: "write",
        major: 1,
        effects: REWRITE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WriteTransientData,
        namespace: "cics.queue",
        name: "write-transient-data",
        major: 1,
        effects: QUEUE_WRITE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ReceiveMap,
        namespace: "cics.terminal",
        name: "receive-map",
        major: 1,
        effects: TERMINAL_RECEIVE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SendMap,
        namespace: "cics.terminal",
        name: "send-map",
        major: 1,
        effects: TERMINAL_SEND_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SendText,
        namespace: "cics.terminal",
        name: "send-text",
        major: 1,
        effects: TERMINAL_SEND_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Assign,
        namespace: "cics.task",
        name: "assign",
        major: 1,
        effects: ASSIGN_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::PurgeMessage,
        namespace: "cics.terminal",
        name: "purge-message",
        major: 1,
        effects: PURGE_MESSAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Start,
        namespace: "cics.interval",
        name: "start",
        major: 1,
        effects: START_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Retrieve,
        namespace: "cics.task",
        name: "retrieve",
        major: 1,
        effects: RETRIEVE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Cancel,
        namespace: "cics.interval",
        name: "cancel",
        major: 1,
        effects: CANCEL_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Delay,
        namespace: "cics.interval",
        name: "delay",
        major: 1,
        effects: DELAY_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DeleteTransientData,
        namespace: "cics.queue",
        name: "delete-transient-data",
        major: 1,
        effects: QUEUE_WRITE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Getmain,
        namespace: "cics.storage",
        name: "getmain",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Freemain,
        namespace: "cics.storage",
        name: "freemain",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DeleteTemporaryStorage,
        namespace: "cics.queue",
        name: "delete-temporary-storage",
        major: 1,
        effects: QUEUE_WRITE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Address,
        namespace: "cics.task",
        name: "address",
        major: 1,
        effects: ADDRESS_SET_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ReadTransientData,
        namespace: "cics.queue",
        name: "read-transient-data",
        major: 1,
        effects: QUEUE_WRITE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ReadTemporaryStorage,
        namespace: "cics.queue",
        name: "read-temporary-storage",
        major: 1,
        effects: QUEUE_WRITE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WaitEvent,
        namespace: "cics.task",
        name: "wait-event",
        major: 1,
        effects: WAIT_EVENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WaitExternal,
        namespace: "cics.task",
        name: "wait-external",
        major: 1,
        effects: WAIT_EVENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WriteTemporaryStorage,
        namespace: "cics.queue",
        name: "write-temporary-storage",
        major: 1,
        effects: TEMPORARY_QUEUE_WRITE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::InvokeApplication,
        namespace: "cics.program",
        name: "invoke-application",
        major: 1,
        effects: CONTROL_TRANSFER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Load,
        namespace: "cics.program",
        name: "load",
        major: 1,
        effects: CONTROL_TRANSFER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Release,
        namespace: "cics.program",
        name: "release",
        major: 1,
        effects: CONTROL_TRANSFER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DocumentCreate,
        namespace: "cics.document",
        name: "create",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DocumentDelete,
        namespace: "cics.document",
        name: "delete",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DocumentInsert,
        namespace: "cics.document",
        name: "insert",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DocumentRetrieve,
        namespace: "cics.document",
        name: "retrieve",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DocumentSet,
        namespace: "cics.document",
        name: "set",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::TransformDataToJson,
        namespace: "cics.transform",
        name: "data-to-json",
        major: 1,
        effects: TRANSFORM_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::TransformDataToXml,
        namespace: "cics.transform",
        name: "data-to-xml",
        major: 1,
        effects: TRANSFORM_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::TransformJsonToData,
        namespace: "cics.transform",
        name: "json-to-data",
        major: 1,
        effects: TRANSFORM_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::TransformXmlToData,
        namespace: "cics.transform",
        name: "xml-to-data",
        major: 1,
        effects: TRANSFORM_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WaitJournalName,
        namespace: "cics.journal",
        name: "wait-journal-name",
        major: 1,
        effects: JOURNAL_WAIT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WaitJournalNum,
        namespace: "cics.journal",
        name: "wait-journal-num",
        major: 1,
        effects: JOURNAL_WAIT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WriteJournalName,
        namespace: "cics.journal",
        name: "write-journal-name",
        major: 1,
        effects: JOURNAL_WAIT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WriteJournalNum,
        namespace: "cics.journal",
        name: "write-journal-num",
        major: 1,
        effects: JOURNAL_WAIT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ResetBrowse,
        namespace: "cics.file",
        name: "reset-browse",
        major: 1,
        effects: READ_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Unlock,
        namespace: "cics.file",
        name: "unlock",
        major: 1,
        effects: READ_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Getmain64,
        namespace: "cics.storage",
        name: "getmain64",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Freemain64,
        namespace: "cics.storage",
        name: "freemain64",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SpoolClose,
        namespace: "cics.spool",
        name: "close",
        major: 1,
        effects: SPOOL_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SpoolOpenInput,
        namespace: "cics.spool",
        name: "open-input",
        major: 1,
        effects: SPOOL_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SpoolOpenOutput,
        namespace: "cics.spool",
        name: "open-output",
        major: 1,
        effects: SPOOL_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SpoolRead,
        namespace: "cics.spool",
        name: "read",
        major: 1,
        effects: SPOOL_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SpoolWrite,
        namespace: "cics.spool",
        name: "write",
        major: 1,
        effects: SPOOL_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::InvokeService,
        namespace: "cics.web-service",
        name: "invokeservice",
        major: 1,
        effects: WEB_SERVICE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SoapFaultAdd,
        namespace: "cics.web-service",
        name: "soapfaultadd",
        major: 1,
        effects: WEB_SERVICE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SoapFaultCreate,
        namespace: "cics.web-service",
        name: "soapfaultcreate",
        major: 1,
        effects: WEB_SERVICE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SoapFaultDelete,
        namespace: "cics.web-service",
        name: "soapfaultdelete",
        major: 1,
        effects: WEB_SERVICE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WsaContextBuild,
        namespace: "cics.web-service",
        name: "wsacontextbuild",
        major: 1,
        effects: WEB_SERVICE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WsaContextDelete,
        namespace: "cics.web-service",
        name: "wsacontextdelete",
        major: 1,
        effects: WEB_SERVICE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WsaContextGet,
        namespace: "cics.web-service",
        name: "wsacontextget",
        major: 1,
        effects: WEB_SERVICE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WsaEprCreate,
        namespace: "cics.web-service",
        name: "wsaeprcreate",
        major: 1,
        effects: WEB_SERVICE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DefineCounter,
        namespace: "cics.counter",
        name: "define-counter",
        major: 1,
        effects: COUNTER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DefineDCounter,
        namespace: "cics.counter",
        name: "define-dcounter",
        major: 1,
        effects: COUNTER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DeleteCounter,
        namespace: "cics.counter",
        name: "delete-counter",
        major: 1,
        effects: COUNTER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DeleteDCounter,
        namespace: "cics.counter",
        name: "delete-dcounter",
        major: 1,
        effects: COUNTER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::GetCounter,
        namespace: "cics.counter",
        name: "get-counter",
        major: 1,
        effects: COUNTER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::GetDCounter,
        namespace: "cics.counter",
        name: "get-dcounter",
        major: 1,
        effects: COUNTER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::QueryCounter,
        namespace: "cics.counter",
        name: "query-counter",
        major: 1,
        effects: COUNTER_QUERY_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::QueryDCounter,
        namespace: "cics.counter",
        name: "query-dcounter",
        major: 1,
        effects: COUNTER_QUERY_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::RewindCounter,
        namespace: "cics.counter",
        name: "rewind-counter",
        major: 1,
        effects: COUNTER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::RewindDCounter,
        namespace: "cics.counter",
        name: "rewind-dcounter",
        major: 1,
        effects: COUNTER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::UpdateCounter,
        namespace: "cics.counter",
        name: "update-counter",
        major: 1,
        effects: COUNTER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::UpdateDCounter,
        namespace: "cics.counter",
        name: "update-dcounter",
        major: 1,
        effects: COUNTER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DefineInputEvent,
        namespace: "cics.event",
        name: "define-input-event",
        major: 1,
        effects: EVENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DefineCompositeEvent,
        namespace: "cics.event",
        name: "define-composite-event",
        major: 1,
        effects: EVENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::AddSubevent,
        namespace: "cics.event",
        name: "add-subevent",
        major: 1,
        effects: EVENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::RemoveSubevent,
        namespace: "cics.event",
        name: "remove-subevent",
        major: 1,
        effects: EVENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DeleteEvent,
        namespace: "cics.event",
        name: "delete-event",
        major: 1,
        effects: EVENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::CheckTimer,
        namespace: "cics.event",
        name: "check-timer",
        major: 1,
        effects: EVENT_TIMER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DefineTimer,
        namespace: "cics.event",
        name: "define-timer",
        major: 1,
        effects: EVENT_TIMER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::DeleteTimer,
        namespace: "cics.event",
        name: "delete-timer",
        major: 1,
        effects: EVENT_TIMER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ForceTimer,
        namespace: "cics.event",
        name: "force-timer",
        major: 1,
        effects: EVENT_TIMER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::RetrieveReattachEvent,
        namespace: "cics.event",
        name: "retrieve-reattach-event",
        major: 1,
        effects: EVENT_TIMER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::RetrieveSubevent,
        namespace: "cics.event",
        name: "retrieve-subevent",
        major: 1,
        effects: EVENT_TIMER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::TestEvent,
        namespace: "cics.event",
        name: "test-event",
        major: 1,
        effects: EVENT_TIMER_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SignalEvent,
        namespace: "cics.event",
        name: "signal-event",
        major: 1,
        effects: EVENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
];
