use super::{
    CicsAssignOutput, CicsOperandName, CicsOutputName, CicsPlanCodecProblem, CicsPlanOperation,
    CicsPlanOption,
};

const ASSIGN_OUTPUT_TAG_BASE: u8 = 13;

pub(super) const fn operation_tag(value: CicsPlanOperation) -> u8 {
    match value {
        CicsPlanOperation::Read => 0,
        CicsPlanOperation::Rewrite => 1,
        CicsPlanOperation::Syncpoint => 2,
        CicsPlanOperation::Deq => 3,
        CicsPlanOperation::Enq => 4,
        CicsPlanOperation::ChangeTask => 5,
        CicsPlanOperation::Suspend => 6,
        CicsPlanOperation::SetAssociationUserCorrData => 7,
        CicsPlanOperation::AddressSet => 8,
        CicsPlanOperation::PopHandle => 9,
        CicsPlanOperation::PushHandle => 10,
        CicsPlanOperation::IgnoreCondition => 11,
        CicsPlanOperation::HandleCondition => 12,
        CicsPlanOperation::HandleAid => 13,
        CicsPlanOperation::AsktimeEib => 14,
        CicsPlanOperation::Asktime => 15,
        CicsPlanOperation::FormatTime => 16,
        CicsPlanOperation::Abend => 17,
        CicsPlanOperation::HandleAbend => 18,
        CicsPlanOperation::Link => 19,
        CicsPlanOperation::Xctl => 20,
        CicsPlanOperation::Return => 21,
        CicsPlanOperation::StartBrowse => 22,
        CicsPlanOperation::ReadNext => 23,
        CicsPlanOperation::ReadPrev => 24,
        CicsPlanOperation::EndBrowse => 25,
        CicsPlanOperation::Delete => 26,
        CicsPlanOperation::Write => 27,
        CicsPlanOperation::WriteTransientData => 28,
        CicsPlanOperation::ReceiveMap => 29,
        CicsPlanOperation::SendMap => 30,
        CicsPlanOperation::SendText => 31,
        CicsPlanOperation::Assign => 32,
        CicsPlanOperation::PurgeMessage => 33,
        CicsPlanOperation::Start => 34,
        CicsPlanOperation::Retrieve => 35,
        CicsPlanOperation::Cancel => 36,
        CicsPlanOperation::Delay => 37,
    }
}

pub(super) fn operation_from_tag(value: u8) -> Result<CicsPlanOperation, CicsPlanCodecProblem> {
    match value {
        0 => Ok(CicsPlanOperation::Read),
        1 => Ok(CicsPlanOperation::Rewrite),
        2 => Ok(CicsPlanOperation::Syncpoint),
        3 => Ok(CicsPlanOperation::Deq),
        4 => Ok(CicsPlanOperation::Enq),
        5 => Ok(CicsPlanOperation::ChangeTask),
        6 => Ok(CicsPlanOperation::Suspend),
        7 => Ok(CicsPlanOperation::SetAssociationUserCorrData),
        8 => Ok(CicsPlanOperation::AddressSet),
        9 => Ok(CicsPlanOperation::PopHandle),
        10 => Ok(CicsPlanOperation::PushHandle),
        11 => Ok(CicsPlanOperation::IgnoreCondition),
        12 => Ok(CicsPlanOperation::HandleCondition),
        13 => Ok(CicsPlanOperation::HandleAid),
        14 => Ok(CicsPlanOperation::AsktimeEib),
        15 => Ok(CicsPlanOperation::Asktime),
        16 => Ok(CicsPlanOperation::FormatTime),
        17 => Ok(CicsPlanOperation::Abend),
        18 => Ok(CicsPlanOperation::HandleAbend),
        19 => Ok(CicsPlanOperation::Link),
        20 => Ok(CicsPlanOperation::Xctl),
        21 => Ok(CicsPlanOperation::Return),
        22 => Ok(CicsPlanOperation::StartBrowse),
        23 => Ok(CicsPlanOperation::ReadNext),
        24 => Ok(CicsPlanOperation::ReadPrev),
        25 => Ok(CicsPlanOperation::EndBrowse),
        26 => Ok(CicsPlanOperation::Delete),
        27 => Ok(CicsPlanOperation::Write),
        28 => Ok(CicsPlanOperation::WriteTransientData),
        29 => Ok(CicsPlanOperation::ReceiveMap),
        30 => Ok(CicsPlanOperation::SendMap),
        31 => Ok(CicsPlanOperation::SendText),
        32 => Ok(CicsPlanOperation::Assign),
        33 => Ok(CicsPlanOperation::PurgeMessage),
        34 => Ok(CicsPlanOperation::Start),
        35 => Ok(CicsPlanOperation::Retrieve),
        36 => Ok(CicsPlanOperation::Cancel),
        37 => Ok(CicsPlanOperation::Delay),
        _ => Err(CicsPlanCodecProblem::Malformed),
    }
}

pub(super) const fn operand_tag(value: CicsOperandName) -> u8 {
    match value {
        CicsOperandName::File => 0,
        CicsOperandName::Dataset => 1,
        CicsOperandName::From => 2,
        CicsOperandName::Ridfld => 3,
        CicsOperandName::Resource => 4,
        CicsOperandName::Length => 5,
        CicsOperandName::MaxLifetime => 6,
        CicsOperandName::Priority => 7,
        CicsOperandName::UserCorrData => 8,
        CicsOperandName::SetAddress => 9,
        CicsOperandName::SetPointer => 10,
        CicsOperandName::UsingAddress => 11,
        CicsOperandName::UsingPointer => 12,
        CicsOperandName::Conditions => 13,
        CicsOperandName::Aids => 14,
        CicsOperandName::Abstime => 15,
        CicsOperandName::DateSep => 16,
        CicsOperandName::TimeSep => 17,
        CicsOperandName::Abcode => 18,
        CicsOperandName::Label => 19,
        CicsOperandName::Program => 20,
        CicsOperandName::Commarea => 21,
        CicsOperandName::TransId => 22,
        CicsOperandName::Queue => 23,
        CicsOperandName::Map => 24,
        CicsOperandName::Mapset => 25,
        CicsOperandName::KeyLength => 26,
        CicsOperandName::ReqId => 27,
        CicsOperandName::Interval => 28,
        CicsOperandName::StartTime => 29,
        CicsOperandName::ReturnTransId => 30,
        CicsOperandName::ReturnTermId => 31,
        CicsOperandName::UserId => 32,
    }
}

pub(super) fn operand_from_tag(value: u8) -> Result<CicsOperandName, CicsPlanCodecProblem> {
    match value {
        0 => Ok(CicsOperandName::File),
        1 => Ok(CicsOperandName::Dataset),
        2 => Ok(CicsOperandName::From),
        3 => Ok(CicsOperandName::Ridfld),
        4 => Ok(CicsOperandName::Resource),
        5 => Ok(CicsOperandName::Length),
        6 => Ok(CicsOperandName::MaxLifetime),
        7 => Ok(CicsOperandName::Priority),
        8 => Ok(CicsOperandName::UserCorrData),
        9 => Ok(CicsOperandName::SetAddress),
        10 => Ok(CicsOperandName::SetPointer),
        11 => Ok(CicsOperandName::UsingAddress),
        12 => Ok(CicsOperandName::UsingPointer),
        13 => Ok(CicsOperandName::Conditions),
        14 => Ok(CicsOperandName::Aids),
        15 => Ok(CicsOperandName::Abstime),
        16 => Ok(CicsOperandName::DateSep),
        17 => Ok(CicsOperandName::TimeSep),
        18 => Ok(CicsOperandName::Abcode),
        19 => Ok(CicsOperandName::Label),
        20 => Ok(CicsOperandName::Program),
        21 => Ok(CicsOperandName::Commarea),
        22 => Ok(CicsOperandName::TransId),
        23 => Ok(CicsOperandName::Queue),
        24 => Ok(CicsOperandName::Map),
        25 => Ok(CicsOperandName::Mapset),
        26 => Ok(CicsOperandName::KeyLength),
        27 => Ok(CicsOperandName::ReqId),
        28 => Ok(CicsOperandName::Interval),
        29 => Ok(CicsOperandName::StartTime),
        30 => Ok(CicsOperandName::ReturnTransId),
        31 => Ok(CicsOperandName::ReturnTermId),
        32 => Ok(CicsOperandName::UserId),
        _ => Err(CicsPlanCodecProblem::Malformed),
    }
}

pub(super) const fn option_tag(value: CicsPlanOption) -> u8 {
    match value {
        CicsPlanOption::Update => 0,
        CicsPlanOption::Rollback => 1,
        CicsPlanOption::NoHandle => 2,
        CicsPlanOption::Task => 3,
        CicsPlanOption::Uow => 4,
        CicsPlanOption::NoSuspend => 5,
        CicsPlanOption::Cancel => 6,
        CicsPlanOption::NoDump => 7,
        CicsPlanOption::Reset => 8,
        CicsPlanOption::Erase => 9,
        CicsPlanOption::Cursor => 10,
        CicsPlanOption::DateSep => 11,
        CicsPlanOption::TimeSep => 12,
        CicsPlanOption::FreeKb => 13,
        CicsPlanOption::Gteq => 14,
        CicsPlanOption::Fmh => 15,
        CicsPlanOption::Protect => 16,
        CicsPlanOption::Wait => 17,
    }
}

pub(super) fn option_from_tag(value: u8) -> Result<CicsPlanOption, CicsPlanCodecProblem> {
    match value {
        0 => Ok(CicsPlanOption::Update),
        1 => Ok(CicsPlanOption::Rollback),
        2 => Ok(CicsPlanOption::NoHandle),
        3 => Ok(CicsPlanOption::Task),
        4 => Ok(CicsPlanOption::Uow),
        5 => Ok(CicsPlanOption::NoSuspend),
        6 => Ok(CicsPlanOption::Cancel),
        7 => Ok(CicsPlanOption::NoDump),
        8 => Ok(CicsPlanOption::Reset),
        9 => Ok(CicsPlanOption::Erase),
        10 => Ok(CicsPlanOption::Cursor),
        11 => Ok(CicsPlanOption::DateSep),
        12 => Ok(CicsPlanOption::TimeSep),
        13 => Ok(CicsPlanOption::FreeKb),
        14 => Ok(CicsPlanOption::Gteq),
        15 => Ok(CicsPlanOption::Fmh),
        16 => Ok(CicsPlanOption::Protect),
        17 => Ok(CicsPlanOption::Wait),
        _ => Err(CicsPlanCodecProblem::Malformed),
    }
}

pub(super) const fn output_tag(value: CicsOutputName) -> u8 {
    match value {
        CicsOutputName::Into => 0,
        CicsOutputName::Resp => 1,
        CicsOutputName::Resp2 => 2,
        CicsOutputName::Abstime => 3,
        CicsOutputName::Milliseconds => 4,
        CicsOutputName::Mmddyy => 5,
        CicsOutputName::Mmddyyyy => 6,
        CicsOutputName::Time => 7,
        CicsOutputName::Yyddd => 8,
        CicsOutputName::Yymmdd => 9,
        CicsOutputName::Yyyymmdd => 10,
        CicsOutputName::Commarea => 11,
        CicsOutputName::Ridfld => 12,
        CicsOutputName::Assign(output) => ASSIGN_OUTPUT_TAG_BASE + output.tag(),
        CicsOutputName::Length => 91,
        CicsOutputName::ReturnTransId => 92,
        CicsOutputName::ReturnTermId => 93,
        CicsOutputName::Queue => 94,
        CicsOutputName::SetPointer => 95,
    }
}

pub(super) fn output_from_tag(value: u8) -> Result<CicsOutputName, CicsPlanCodecProblem> {
    match value {
        0 => Ok(CicsOutputName::Into),
        1 => Ok(CicsOutputName::Resp),
        2 => Ok(CicsOutputName::Resp2),
        3 => Ok(CicsOutputName::Abstime),
        4 => Ok(CicsOutputName::Milliseconds),
        5 => Ok(CicsOutputName::Mmddyy),
        6 => Ok(CicsOutputName::Mmddyyyy),
        7 => Ok(CicsOutputName::Time),
        8 => Ok(CicsOutputName::Yyddd),
        9 => Ok(CicsOutputName::Yymmdd),
        10 => Ok(CicsOutputName::Yyyymmdd),
        11 => Ok(CicsOutputName::Commarea),
        12 => Ok(CicsOutputName::Ridfld),
        91 => Ok(CicsOutputName::Length),
        92 => Ok(CicsOutputName::ReturnTransId),
        93 => Ok(CicsOutputName::ReturnTermId),
        94 => Ok(CicsOutputName::Queue),
        95 => Ok(CicsOutputName::SetPointer),
        value => CicsAssignOutput::from_tag(
            value
                .checked_sub(ASSIGN_OUTPUT_TAG_BASE)
                .ok_or(CicsPlanCodecProblem::Malformed)?,
        )
        .map(CicsOutputName::Assign)
        .ok_or(CicsPlanCodecProblem::Malformed),
    }
}
