use super::{
    CicsAssignOutput, CicsOperandName, CicsOutputName, CicsPlanCodecProblem, CicsPlanOperation,
    CicsPlanOption,
};

const ASSIGN_OUTPUT_TAG_BASE: u8 = 13;
const ASSIGN_OUTPUT_LEGACY_COUNT: u8 = 78;
const ASSIGN_OUTPUT_EXTENSION_TAG_BASE: u8 = 96;

#[cfg(test)]
pub(super) const TRANSFORM_OPERATION_TAGS: std::ops::RangeInclusive<u8> = 68..=71;
#[cfg(test)]
pub(super) const TRANSFORM_OPERAND_TAGS: std::ops::RangeInclusive<u8> = 153..=171;
#[cfg(test)]
pub(super) const TRANSFORM_OPTION_TAGS: std::ops::RangeInclusive<u8> = 96..=107;
#[cfg(test)]
pub(super) const TRANSFORM_OUTPUT_TAGS: std::ops::RangeInclusive<u8> = 224..=231;

pub(super) const fn operation_tag(value: CicsPlanOperation) -> u8 {
    match value {
        CicsPlanOperation::Read => 0,
        CicsPlanOperation::Rewrite => 1,
        CicsPlanOperation::Syncpoint => 2,
        CicsPlanOperation::Deq => 3,
        CicsPlanOperation::Enq => 4,
        CicsPlanOperation::ChangeTask => 5,
        CicsPlanOperation::Suspend => 6,
        CicsPlanOperation::SetAssociationUserCorrData => 7,
        CicsPlanOperation::AddressSet => 8,
        CicsPlanOperation::PopHandle => 9,
        CicsPlanOperation::PushHandle => 10,
        CicsPlanOperation::IgnoreCondition => 11,
        CicsPlanOperation::HandleCondition => 12,
        CicsPlanOperation::HandleAid => 13,
        CicsPlanOperation::AsktimeEib => 14,
        CicsPlanOperation::Asktime => 15,
        CicsPlanOperation::FormatTime => 16,
        CicsPlanOperation::Abend => 17,
        CicsPlanOperation::HandleAbend => 18,
        CicsPlanOperation::Link => 19,
        CicsPlanOperation::Xctl => 20,
        CicsPlanOperation::Return => 21,
        CicsPlanOperation::StartBrowse => 22,
        CicsPlanOperation::ResetBrowse => 74,
        CicsPlanOperation::Unlock => 75,
        CicsPlanOperation::ReadNext => 23,
        CicsPlanOperation::ReadPrev => 24,
        CicsPlanOperation::EndBrowse => 25,
        CicsPlanOperation::Delete => 26,
        CicsPlanOperation::Write => 27,
        CicsPlanOperation::WriteTransientData => 28,
        CicsPlanOperation::ReceiveMap => 29,
        CicsPlanOperation::SendMap => 30,
        CicsPlanOperation::SendText => 31,
        CicsPlanOperation::Assign => 32,
        CicsPlanOperation::PurgeMessage => 33,
        CicsPlanOperation::Start => 34,
        CicsPlanOperation::Retrieve => 35,
        CicsPlanOperation::Cancel => 36,
        CicsPlanOperation::Delay => 37,
        CicsPlanOperation::DeleteTransientData => 38,
        CicsPlanOperation::Getmain => 39,
        CicsPlanOperation::Freemain => 40,
        CicsPlanOperation::Getmain64 => 72,
        CicsPlanOperation::Freemain64 => 73,
        CicsPlanOperation::DeleteTemporaryStorage => 41,
        CicsPlanOperation::Address => 42,
        CicsPlanOperation::ReadTransientData => 51,
        CicsPlanOperation::WaitEvent => 43,
        CicsPlanOperation::WaitExternal => 44,
        CicsPlanOperation::ReadTemporaryStorage => 49,
        CicsPlanOperation::WriteTemporaryStorage => 50,
        CicsPlanOperation::InvokeApplication => 46,
        CicsPlanOperation::Load => 47,
        CicsPlanOperation::Release => 48,
        CicsPlanOperation::DocumentCreate => 63,
        CicsPlanOperation::DocumentDelete => 64,
        CicsPlanOperation::DocumentInsert => 65,
        CicsPlanOperation::DocumentRetrieve => 66,
        CicsPlanOperation::DocumentSet => 67,
        CicsPlanOperation::TransformDataToJson => 68,
        CicsPlanOperation::TransformDataToXml => 69,
        CicsPlanOperation::TransformJsonToData => 70,
        CicsPlanOperation::TransformXmlToData => 71,
        CicsPlanOperation::WaitJournalName => 54,
        CicsPlanOperation::WaitJournalNum => 55,
        CicsPlanOperation::WriteJournalName => 56,
        CicsPlanOperation::WriteJournalNum => 57,
    }
}

pub(super) fn operation_from_tag(value: u8) -> Result<CicsPlanOperation, CicsPlanCodecProblem> {
    match value {
        0 => Ok(CicsPlanOperation::Read),
        1 => Ok(CicsPlanOperation::Rewrite),
        2 => Ok(CicsPlanOperation::Syncpoint),
        3 => Ok(CicsPlanOperation::Deq),
        4 => Ok(CicsPlanOperation::Enq),
        5 => Ok(CicsPlanOperation::ChangeTask),
        6 => Ok(CicsPlanOperation::Suspend),
        7 => Ok(CicsPlanOperation::SetAssociationUserCorrData),
        8 => Ok(CicsPlanOperation::AddressSet),
        9 => Ok(CicsPlanOperation::PopHandle),
        10 => Ok(CicsPlanOperation::PushHandle),
        11 => Ok(CicsPlanOperation::IgnoreCondition),
        12 => Ok(CicsPlanOperation::HandleCondition),
        13 => Ok(CicsPlanOperation::HandleAid),
        14 => Ok(CicsPlanOperation::AsktimeEib),
        15 => Ok(CicsPlanOperation::Asktime),
        16 => Ok(CicsPlanOperation::FormatTime),
        17 => Ok(CicsPlanOperation::Abend),
        18 => Ok(CicsPlanOperation::HandleAbend),
        19 => Ok(CicsPlanOperation::Link),
        20 => Ok(CicsPlanOperation::Xctl),
        21 => Ok(CicsPlanOperation::Return),
        22 => Ok(CicsPlanOperation::StartBrowse),
        74 => Ok(CicsPlanOperation::ResetBrowse),
        75 => Ok(CicsPlanOperation::Unlock),
        23 => Ok(CicsPlanOperation::ReadNext),
        24 => Ok(CicsPlanOperation::ReadPrev),
        25 => Ok(CicsPlanOperation::EndBrowse),
        26 => Ok(CicsPlanOperation::Delete),
        27 => Ok(CicsPlanOperation::Write),
        28 => Ok(CicsPlanOperation::WriteTransientData),
        29 => Ok(CicsPlanOperation::ReceiveMap),
        30 => Ok(CicsPlanOperation::SendMap),
        31 => Ok(CicsPlanOperation::SendText),
        32 => Ok(CicsPlanOperation::Assign),
        33 => Ok(CicsPlanOperation::PurgeMessage),
        34 => Ok(CicsPlanOperation::Start),
        35 => Ok(CicsPlanOperation::Retrieve),
        36 => Ok(CicsPlanOperation::Cancel),
        37 => Ok(CicsPlanOperation::Delay),
        38 => Ok(CicsPlanOperation::DeleteTransientData),
        39 => Ok(CicsPlanOperation::Getmain),
        40 => Ok(CicsPlanOperation::Freemain),
        72 => Ok(CicsPlanOperation::Getmain64),
        73 => Ok(CicsPlanOperation::Freemain64),
        41 => Ok(CicsPlanOperation::DeleteTemporaryStorage),
        42 => Ok(CicsPlanOperation::Address),
        51 => Ok(CicsPlanOperation::ReadTransientData),
        43 => Ok(CicsPlanOperation::WaitEvent),
        44 => Ok(CicsPlanOperation::WaitExternal),
        49 => Ok(CicsPlanOperation::ReadTemporaryStorage),
        50 => Ok(CicsPlanOperation::WriteTemporaryStorage),
        46 => Ok(CicsPlanOperation::InvokeApplication),
        47 => Ok(CicsPlanOperation::Load),
        48 => Ok(CicsPlanOperation::Release),
        63 => Ok(CicsPlanOperation::DocumentCreate),
        64 => Ok(CicsPlanOperation::DocumentDelete),
        65 => Ok(CicsPlanOperation::DocumentInsert),
        66 => Ok(CicsPlanOperation::DocumentRetrieve),
        67 => Ok(CicsPlanOperation::DocumentSet),
        68 => Ok(CicsPlanOperation::TransformDataToJson),
        69 => Ok(CicsPlanOperation::TransformDataToXml),
        70 => Ok(CicsPlanOperation::TransformJsonToData),
        71 => Ok(CicsPlanOperation::TransformXmlToData),
        54 => Ok(CicsPlanOperation::WaitJournalName),
        55 => Ok(CicsPlanOperation::WaitJournalNum),
        56 => Ok(CicsPlanOperation::WriteJournalName),
        57 => Ok(CicsPlanOperation::WriteJournalNum),
        _ => Err(CicsPlanCodecProblem::Malformed),
    }
}

pub(super) const fn operand_tag(value: CicsOperandName) -> u8 {
    match value {
        CicsOperandName::File => 0,
        CicsOperandName::Dataset => 1,
        CicsOperandName::From => 2,
        CicsOperandName::Ridfld => 3,
        CicsOperandName::Resource => 4,
        CicsOperandName::Length => 5,
        CicsOperandName::MaxLifetime => 6,
        CicsOperandName::Priority => 7,
        CicsOperandName::UserCorrData => 8,
        CicsOperandName::SetAddress => 9,
        CicsOperandName::SetPointer => 10,
        CicsOperandName::UsingAddress => 11,
        CicsOperandName::UsingPointer => 12,
        CicsOperandName::Conditions => 13,
        CicsOperandName::Aids => 14,
        CicsOperandName::Abstime => 15,
        CicsOperandName::DateSep => 16,
        CicsOperandName::TimeSep => 17,
        CicsOperandName::Abcode => 18,
        CicsOperandName::Label => 19,
        CicsOperandName::Program => 20,
        CicsOperandName::Commarea => 21,
        CicsOperandName::TransId => 22,
        CicsOperandName::Queue => 23,
        CicsOperandName::Map => 24,
        CicsOperandName::Mapset => 25,
        CicsOperandName::KeyLength => 26,
        CicsOperandName::ReqId => 27,
        CicsOperandName::Interval => 28,
        CicsOperandName::StartTime => 29,
        CicsOperandName::ReturnTransId => 30,
        CicsOperandName::ReturnTermId => 31,
        CicsOperandName::UserId => 32,
        CicsOperandName::Hours => 33,
        CicsOperandName::Minutes => 34,
        CicsOperandName::Seconds => 35,
        CicsOperandName::Milliseconds => 36,
        CicsOperandName::DataLength => 37,
        CicsOperandName::TermId => 38,
        CicsOperandName::Flength => 39,
        CicsOperandName::InitImage => 40,
        CicsOperandName::DataPointer => 41,
        CicsOperandName::DataArea => 42,
        CicsOperandName::Qname => 43,
        CicsOperandName::SysId => 44,
        CicsOperandName::CommareaPointer => 45,
        CicsOperandName::EventControlAddress => 46,
        CicsOperandName::WaitName => 47,
        CicsOperandName::EcbList => 48,
        CicsOperandName::NumEvents => 49,
        CicsOperandName::Purgeability => 50,
        CicsOperandName::Item => 70,
        CicsOperandName::Application => 56,
        CicsOperandName::Platform => 57,
        CicsOperandName::ApplicationOperation => 58,
        CicsOperandName::MajorVersion => 59,
        CicsOperandName::MinorVersion => 60,
        CicsOperandName::Channel => 61,
        CicsOperandName::LoadSet => 62,
        CicsOperandName::Entry => 63,
        CicsOperandName::LoadLength => 64,
        CicsOperandName::LoadFlength => 65,
        CicsOperandName::DocumentToken => 132,
        CicsOperandName::Text => 133,
        CicsOperandName::Binary => 134,
        CicsOperandName::FromDocument => 135,
        CicsOperandName::Template => 136,
        CicsOperandName::SymbolList => 137,
        CicsOperandName::ListLength => 138,
        CicsOperandName::Delimiter => 139,
        CicsOperandName::HostCodePage => 140,
        CicsOperandName::Bookmark => 141,
        CicsOperandName::Symbol => 142,
        CicsOperandName::AtBookmark => 143,
        CicsOperandName::ToBookmark => 144,
        CicsOperandName::MaximumLength => 145,
        CicsOperandName::CharacterSet => 146,
        CicsOperandName::SymbolValue => 147,
        CicsOperandName::InContainer => 153,
        CicsOperandName::OutContainer => 154,
        CicsOperandName::Transformer => 155,
        CicsOperandName::DataContainer => 156,
        CicsOperandName::XmlContainer => 157,
        CicsOperandName::XmlTransform => 158,
        CicsOperandName::NsContainer => 159,
        CicsOperandName::ElementName => 160,
        CicsOperandName::ElementNameLength => 161,
        CicsOperandName::ElementNamespace => 162,
        CicsOperandName::ElementNamespaceLength => 163,
        CicsOperandName::TypeName => 164,
        CicsOperandName::TypeNameLength => 165,
        CicsOperandName::TypeNamespace => 166,
        CicsOperandName::TypeNamespaceLength => 167,
        CicsOperandName::JournalName => 96,
        CicsOperandName::JournalReqId => 97,
        CicsOperandName::JournalNum => 98,
        CicsOperandName::JournalTypeId => 99,
        CicsOperandName::JournalFrom => 100,
        CicsOperandName::JournalFlength => 101,
        CicsOperandName::JournalPrefix => 102,
        CicsOperandName::JournalPfxLeng => 103,
        CicsOperandName::Token => 182,
        CicsOperandName::Flength64 => 172,
        CicsOperandName::Location64 => 173,
        CicsOperandName::Abi64 => 174,
        CicsOperandName::DataPointer64 => 175,
        CicsOperandName::DataArea64 => 176,
    }
}

pub(super) fn operand_from_tag(value: u8) -> Result<CicsOperandName, CicsPlanCodecProblem> {
    match value {
        0 => Ok(CicsOperandName::File),
        1 => Ok(CicsOperandName::Dataset),
        2 => Ok(CicsOperandName::From),
        3 => Ok(CicsOperandName::Ridfld),
        4 => Ok(CicsOperandName::Resource),
        5 => Ok(CicsOperandName::Length),
        6 => Ok(CicsOperandName::MaxLifetime),
        7 => Ok(CicsOperandName::Priority),
        8 => Ok(CicsOperandName::UserCorrData),
        9 => Ok(CicsOperandName::SetAddress),
        10 => Ok(CicsOperandName::SetPointer),
        11 => Ok(CicsOperandName::UsingAddress),
        12 => Ok(CicsOperandName::UsingPointer),
        13 => Ok(CicsOperandName::Conditions),
        14 => Ok(CicsOperandName::Aids),
        15 => Ok(CicsOperandName::Abstime),
        16 => Ok(CicsOperandName::DateSep),
        17 => Ok(CicsOperandName::TimeSep),
        18 => Ok(CicsOperandName::Abcode),
        19 => Ok(CicsOperandName::Label),
        20 => Ok(CicsOperandName::Program),
        21 => Ok(CicsOperandName::Commarea),
        22 => Ok(CicsOperandName::TransId),
        23 => Ok(CicsOperandName::Queue),
        24 => Ok(CicsOperandName::Map),
        25 => Ok(CicsOperandName::Mapset),
        26 => Ok(CicsOperandName::KeyLength),
        27 => Ok(CicsOperandName::ReqId),
        28 => Ok(CicsOperandName::Interval),
        29 => Ok(CicsOperandName::StartTime),
        30 => Ok(CicsOperandName::ReturnTransId),
        31 => Ok(CicsOperandName::ReturnTermId),
        32 => Ok(CicsOperandName::UserId),
        33 => Ok(CicsOperandName::Hours),
        34 => Ok(CicsOperandName::Minutes),
        35 => Ok(CicsOperandName::Seconds),
        36 => Ok(CicsOperandName::Milliseconds),
        37 => Ok(CicsOperandName::DataLength),
        38 => Ok(CicsOperandName::TermId),
        39 => Ok(CicsOperandName::Flength),
        40 => Ok(CicsOperandName::InitImage),
        41 => Ok(CicsOperandName::DataPointer),
        42 => Ok(CicsOperandName::DataArea),
        43 => Ok(CicsOperandName::Qname),
        44 => Ok(CicsOperandName::SysId),
        45 => Ok(CicsOperandName::CommareaPointer),
        46 => Ok(CicsOperandName::EventControlAddress),
        47 => Ok(CicsOperandName::WaitName),
        48 => Ok(CicsOperandName::EcbList),
        49 => Ok(CicsOperandName::NumEvents),
        50 => Ok(CicsOperandName::Purgeability),
        70 => Ok(CicsOperandName::Item),
        56 => Ok(CicsOperandName::Application),
        57 => Ok(CicsOperandName::Platform),
        58 => Ok(CicsOperandName::ApplicationOperation),
        59 => Ok(CicsOperandName::MajorVersion),
        60 => Ok(CicsOperandName::MinorVersion),
        61 => Ok(CicsOperandName::Channel),
        62 => Ok(CicsOperandName::LoadSet),
        63 => Ok(CicsOperandName::Entry),
        64 => Ok(CicsOperandName::LoadLength),
        65 => Ok(CicsOperandName::LoadFlength),
        132 => Ok(CicsOperandName::DocumentToken),
        133 => Ok(CicsOperandName::Text),
        134 => Ok(CicsOperandName::Binary),
        135 => Ok(CicsOperandName::FromDocument),
        136 => Ok(CicsOperandName::Template),
        137 => Ok(CicsOperandName::SymbolList),
        138 => Ok(CicsOperandName::ListLength),
        139 => Ok(CicsOperandName::Delimiter),
        140 => Ok(CicsOperandName::HostCodePage),
        141 => Ok(CicsOperandName::Bookmark),
        142 => Ok(CicsOperandName::Symbol),
        143 => Ok(CicsOperandName::AtBookmark),
        144 => Ok(CicsOperandName::ToBookmark),
        145 => Ok(CicsOperandName::MaximumLength),
        146 => Ok(CicsOperandName::CharacterSet),
        147 => Ok(CicsOperandName::SymbolValue),
        153 => Ok(CicsOperandName::InContainer),
        154 => Ok(CicsOperandName::OutContainer),
        155 => Ok(CicsOperandName::Transformer),
        156 => Ok(CicsOperandName::DataContainer),
        157 => Ok(CicsOperandName::XmlContainer),
        158 => Ok(CicsOperandName::XmlTransform),
        159 => Ok(CicsOperandName::NsContainer),
        160 => Ok(CicsOperandName::ElementName),
        161 => Ok(CicsOperandName::ElementNameLength),
        162 => Ok(CicsOperandName::ElementNamespace),
        163 => Ok(CicsOperandName::ElementNamespaceLength),
        164 => Ok(CicsOperandName::TypeName),
        165 => Ok(CicsOperandName::TypeNameLength),
        166 => Ok(CicsOperandName::TypeNamespace),
        167 => Ok(CicsOperandName::TypeNamespaceLength),
        96 => Ok(CicsOperandName::JournalName),
        97 => Ok(CicsOperandName::JournalReqId),
        98 => Ok(CicsOperandName::JournalNum),
        99 => Ok(CicsOperandName::JournalTypeId),
        100 => Ok(CicsOperandName::JournalFrom),
        101 => Ok(CicsOperandName::JournalFlength),
        102 => Ok(CicsOperandName::JournalPrefix),
        103 => Ok(CicsOperandName::JournalPfxLeng),
        182 => Ok(CicsOperandName::Token),
        172 => Ok(CicsOperandName::Flength64),
        173 => Ok(CicsOperandName::Location64),
        174 => Ok(CicsOperandName::Abi64),
        175 => Ok(CicsOperandName::DataPointer64),
        176 => Ok(CicsOperandName::DataArea64),
        _ => Err(CicsPlanCodecProblem::Malformed),
    }
}

pub(super) const fn option_tag(value: CicsPlanOption) -> u8 {
    match value {
        CicsPlanOption::Update => 0,
        CicsPlanOption::Rollback => 1,
        CicsPlanOption::NoHandle => 2,
        CicsPlanOption::Task => 3,
        CicsPlanOption::Uow => 4,
        CicsPlanOption::NoSuspend => 5,
        CicsPlanOption::Cancel => 6,
        CicsPlanOption::NoDump => 7,
        CicsPlanOption::Reset => 8,
        CicsPlanOption::Erase => 9,
        CicsPlanOption::Cursor => 10,
        CicsPlanOption::DateSep => 11,
        CicsPlanOption::TimeSep => 12,
        CicsPlanOption::FreeKb => 13,
        CicsPlanOption::Gteq => 14,
        CicsPlanOption::Fmh => 15,
        CicsPlanOption::Protect => 16,
        CicsPlanOption::Wait => 17,
        CicsPlanOption::After => 18,
        CicsPlanOption::At => 19,
        CicsPlanOption::For => 20,
        CicsPlanOption::Until => 21,
        CicsPlanOption::NoCheck => 22,
        CicsPlanOption::MapOnly => 23,
        CicsPlanOption::DataOnly => 24,
        CicsPlanOption::Generic => 25,
        CicsPlanOption::Equal => 26,
        CicsPlanOption::Terminal => 27,
        CicsPlanOption::Purgeable => 28,
        CicsPlanOption::NotPurgeable => 29,
        CicsPlanOption::Next => 44,
        CicsPlanOption::RewriteTemporary => 45,
        CicsPlanOption::Auxiliary => 46,
        CicsPlanOption::Main => 47,
        CicsPlanOption::ExactMatch => 36,
        CicsPlanOption::Minimum => 37,
        CicsPlanOption::Hold => 38,
        CicsPlanOption::Unescaped => 84,
        CicsPlanOption::DocumentDataOnly => 85,
        CicsPlanOption::CicsDataKey64 => 108,
        CicsPlanOption::UserDataKey64 => 109,
        CicsPlanOption::Shared64 => 110,
        CicsPlanOption::Executable64 => 111,
    }
}

pub(super) fn option_from_tag(value: u8) -> Result<CicsPlanOption, CicsPlanCodecProblem> {
    match value {
        0 => Ok(CicsPlanOption::Update),
        1 => Ok(CicsPlanOption::Rollback),
        2 => Ok(CicsPlanOption::NoHandle),
        3 => Ok(CicsPlanOption::Task),
        4 => Ok(CicsPlanOption::Uow),
        5 => Ok(CicsPlanOption::NoSuspend),
        6 => Ok(CicsPlanOption::Cancel),
        7 => Ok(CicsPlanOption::NoDump),
        8 => Ok(CicsPlanOption::Reset),
        9 => Ok(CicsPlanOption::Erase),
        10 => Ok(CicsPlanOption::Cursor),
        11 => Ok(CicsPlanOption::DateSep),
        12 => Ok(CicsPlanOption::TimeSep),
        13 => Ok(CicsPlanOption::FreeKb),
        14 => Ok(CicsPlanOption::Gteq),
        15 => Ok(CicsPlanOption::Fmh),
        16 => Ok(CicsPlanOption::Protect),
        17 => Ok(CicsPlanOption::Wait),
        18 => Ok(CicsPlanOption::After),
        19 => Ok(CicsPlanOption::At),
        20 => Ok(CicsPlanOption::For),
        21 => Ok(CicsPlanOption::Until),
        22 => Ok(CicsPlanOption::NoCheck),
        23 => Ok(CicsPlanOption::MapOnly),
        24 => Ok(CicsPlanOption::DataOnly),
        25 => Ok(CicsPlanOption::Generic),
        26 => Ok(CicsPlanOption::Equal),
        27 => Ok(CicsPlanOption::Terminal),
        28 => Ok(CicsPlanOption::Purgeable),
        29 => Ok(CicsPlanOption::NotPurgeable),
        44 => Ok(CicsPlanOption::Next),
        45 => Ok(CicsPlanOption::RewriteTemporary),
        46 => Ok(CicsPlanOption::Auxiliary),
        47 => Ok(CicsPlanOption::Main),
        36 => Ok(CicsPlanOption::ExactMatch),
        37 => Ok(CicsPlanOption::Minimum),
        38 => Ok(CicsPlanOption::Hold),
        84 => Ok(CicsPlanOption::Unescaped),
        85 => Ok(CicsPlanOption::DocumentDataOnly),
        108 => Ok(CicsPlanOption::CicsDataKey64),
        109 => Ok(CicsPlanOption::UserDataKey64),
        110 => Ok(CicsPlanOption::Shared64),
        111 => Ok(CicsPlanOption::Executable64),
        _ => Err(CicsPlanCodecProblem::Malformed),
    }
}

pub(super) const fn output_tag(value: CicsOutputName) -> u8 {
    match value {
        CicsOutputName::Into => 0,
        CicsOutputName::Resp => 1,
        CicsOutputName::Resp2 => 2,
        CicsOutputName::Abstime => 3,
        CicsOutputName::Milliseconds => 4,
        CicsOutputName::Mmddyy => 5,
        CicsOutputName::Mmddyyyy => 6,
        CicsOutputName::Time => 7,
        CicsOutputName::Yyddd => 8,
        CicsOutputName::Yymmdd => 9,
        CicsOutputName::Yyyymmdd => 10,
        CicsOutputName::Commarea => 11,
        CicsOutputName::Ridfld => 12,
        CicsOutputName::Token => 240,
        CicsOutputName::Assign(output) => {
            let tag = output.tag();
            if tag < ASSIGN_OUTPUT_LEGACY_COUNT {
                ASSIGN_OUTPUT_TAG_BASE + tag
            } else {
                ASSIGN_OUTPUT_EXTENSION_TAG_BASE + (tag - ASSIGN_OUTPUT_LEGACY_COUNT)
            }
        }
        CicsOutputName::Length => 91,
        CicsOutputName::ReturnTransId => 92,
        CicsOutputName::ReturnTermId => 93,
        CicsOutputName::Queue => 94,
        CicsOutputName::SetPointer => 95,
        CicsOutputName::NumItems => 200,
        CicsOutputName::DocumentToken => 216,
        CicsOutputName::DocumentSize => 217,
        CicsOutputName::ElementName => 224,
        CicsOutputName::ElementNameLength => 225,
        CicsOutputName::ElementNamespace => 226,
        CicsOutputName::ElementNamespaceLength => 227,
        CicsOutputName::TypeName => 228,
        CicsOutputName::TypeNameLength => 229,
        CicsOutputName::TypeNamespace => 230,
        CicsOutputName::TypeNamespaceLength => 231,
        CicsOutputName::JournalReqId => 201,
        CicsOutputName::SetPointer64 => 232,
    }
}

pub(super) fn output_from_tag(value: u8) -> Result<CicsOutputName, CicsPlanCodecProblem> {
    match value {
        0 => Ok(CicsOutputName::Into),
        1 => Ok(CicsOutputName::Resp),
        2 => Ok(CicsOutputName::Resp2),
        3 => Ok(CicsOutputName::Abstime),
        4 => Ok(CicsOutputName::Milliseconds),
        5 => Ok(CicsOutputName::Mmddyy),
        6 => Ok(CicsOutputName::Mmddyyyy),
        7 => Ok(CicsOutputName::Time),
        8 => Ok(CicsOutputName::Yyddd),
        9 => Ok(CicsOutputName::Yymmdd),
        10 => Ok(CicsOutputName::Yyyymmdd),
        11 => Ok(CicsOutputName::Commarea),
        12 => Ok(CicsOutputName::Ridfld),
        240 => Ok(CicsOutputName::Token),
        91 => Ok(CicsOutputName::Length),
        92 => Ok(CicsOutputName::ReturnTransId),
        93 => Ok(CicsOutputName::ReturnTermId),
        94 => Ok(CicsOutputName::Queue),
        95 => Ok(CicsOutputName::SetPointer),
        200 => Ok(CicsOutputName::NumItems),
        216 => Ok(CicsOutputName::DocumentToken),
        217 => Ok(CicsOutputName::DocumentSize),
        224 => Ok(CicsOutputName::ElementName),
        225 => Ok(CicsOutputName::ElementNameLength),
        226 => Ok(CicsOutputName::ElementNamespace),
        227 => Ok(CicsOutputName::ElementNamespaceLength),
        228 => Ok(CicsOutputName::TypeName),
        229 => Ok(CicsOutputName::TypeNameLength),
        230 => Ok(CicsOutputName::TypeNamespace),
        231 => Ok(CicsOutputName::TypeNamespaceLength),
        201 => Ok(CicsOutputName::JournalReqId),
        232 => Ok(CicsOutputName::SetPointer64),
        13..=90 => CicsAssignOutput::from_tag(value - ASSIGN_OUTPUT_TAG_BASE)
            .map(CicsOutputName::Assign)
            .ok_or(CicsPlanCodecProblem::Malformed),
        // Reserved non-ASSIGN journal outputs must remain ahead of the
        // open-ended ASSIGN extension decoder.
        202..=207 => Err(CicsPlanCodecProblem::Malformed),
        96..=200 | 208..=u8::MAX => value
            .checked_sub(ASSIGN_OUTPUT_EXTENSION_TAG_BASE)
            .and_then(|tag| tag.checked_add(ASSIGN_OUTPUT_LEGACY_COUNT))
            .and_then(CicsAssignOutput::from_tag)
            .map(CicsOutputName::Assign)
            .ok_or(CicsPlanCodecProblem::Malformed),
    }
}
