use mainframe_env_host_api::CicsOperation;
use mainframe_env_ir::{
    CicsAssignOutput, CicsOperandName, CicsOutputName, CicsPlanOperation, CicsPlanOption,
};

pub(super) const fn counter_shape(operation: Option<CicsPlanOperation>) -> Option<(usize, bool)> {
    match operation {
        Some(
            CicsPlanOperation::DefineCounter
            | CicsPlanOperation::DeleteCounter
            | CicsPlanOperation::GetCounter
            | CicsPlanOperation::QueryCounter
            | CicsPlanOperation::RewindCounter
            | CicsPlanOperation::UpdateCounter,
        ) => Some((4, true)),
        Some(
            CicsPlanOperation::DefineDCounter
            | CicsPlanOperation::DeleteDCounter
            | CicsPlanOperation::GetDCounter
            | CicsPlanOperation::QueryDCounter
            | CicsPlanOperation::RewindDCounter
            | CicsPlanOperation::UpdateDCounter,
        ) => Some((8, false)),
        _ => None,
    }
}

#[derive(Clone, Copy)]
pub(super) enum SlotUse {
    Input,
    HalfwordInput,
    FullwordInput,
    CounterNumber,
    AbcodeInput,
    ProgramNameInput,
    AbstimeInput,
    SeparatorInput,
    Output,
    AbstimeOutput,
    FormatTextOutput(usize),
    MillisecondsOutput,
    NumericOutput,
    HalfwordOutput,
    FullwordOutput,
    PointerInput,
    PointerOutput,
    Pointer64Output,
    Pointer64Input,
    DataArea64Input,
    AddressInput,
    AddressOutput,
    AssignOutput(CicsAssignOutput),
    SpoolTokenInput,
    SpoolTokenOutput,
    SpoolUserIdInput,
    SpoolClassInput,
    SpoolNodeInput,
    SpoolRecordLengthInput,
    SpoolOutDescrInput,
    SpoolMaxFlengthInput,
    SpoolToFlengthOutput,
    MonitorDataInput,
    DumpIdOutput,
}

pub(super) const fn input_slot_use(name: CicsOperandName) -> SlotUse {
    match name {
        CicsOperandName::Abcode => SlotUse::AbcodeInput,
        CicsOperandName::Program => SlotUse::ProgramNameInput,
        CicsOperandName::Abstime => SlotUse::AbstimeInput,
        CicsOperandName::MajorVersion | CicsOperandName::MinorVersion => SlotUse::FullwordInput,
        CicsOperandName::DateSep | CicsOperandName::TimeSep => SlotUse::SeparatorInput,
        CicsOperandName::DestIdLength
        | CicsOperandName::Subaddress
        | CicsOperandName::VolumeLength
        | CicsOperandName::NumRec
        | CicsOperandName::KeyNumber => SlotUse::HalfwordInput,
        CicsOperandName::KeyLength => SlotUse::Input,
        CicsOperandName::Flength
        | CicsOperandName::ElementNameLength
        | CicsOperandName::ElementNamespaceLength
        | CicsOperandName::TypeNameLength
        | CicsOperandName::TypeNamespaceLength
        | CicsOperandName::JournalReqId => SlotUse::FullwordInput,
        CicsOperandName::JournalFlength => SlotUse::FullwordInput,
        CicsOperandName::SignalFromLength => SlotUse::FullwordInput,
        CicsOperandName::JournalPfxLeng => SlotUse::HalfwordInput,
        CicsOperandName::Token => SlotUse::FullwordInput,
        CicsOperandName::Flength64 => SlotUse::FullwordInput,
        CicsOperandName::ScopeLen
        | CicsOperandName::FaultCodeLen
        | CicsOperandName::FaultStrLen
        | CicsOperandName::RoleLength
        | CicsOperandName::FaultActLen
        | CicsOperandName::DetailLength
        | CicsOperandName::FromCcsid
        | CicsOperandName::SubcodeLen
        | CicsOperandName::RelatesIndex
        | CicsOperandName::EprLength
        | CicsOperandName::IntoCcsid
        | CicsOperandName::RefParmsLen
        | CicsOperandName::MetadataLen => SlotUse::FullwordInput,
        CicsOperandName::DataPointer => SlotUse::PointerInput,
        CicsOperandName::DataPointer64 => SlotUse::Pointer64Input,
        CicsOperandName::DataArea => SlotUse::Input,
        CicsOperandName::DataArea64 => SlotUse::DataArea64Input,
        CicsOperandName::EventControlAddress => SlotUse::PointerInput,
        CicsOperandName::EcbList => SlotUse::PointerInput,
        CicsOperandName::NumEvents | CicsOperandName::Purgeability => SlotUse::FullwordInput,
        CicsOperandName::Item => SlotUse::HalfwordInput,
        CicsOperandName::LoadSet | CicsOperandName::Entry => SlotUse::PointerOutput,
        CicsOperandName::LoadLength => SlotUse::HalfwordOutput,
        CicsOperandName::LoadFlength => SlotUse::FullwordOutput,
        CicsOperandName::ListLength | CicsOperandName::MaximumLength => SlotUse::FullwordInput,
        CicsOperandName::DocumentToken
        | CicsOperandName::Text
        | CicsOperandName::Binary
        | CicsOperandName::FromDocument
        | CicsOperandName::Template
        | CicsOperandName::SymbolList
        | CicsOperandName::Delimiter
        | CicsOperandName::HostCodePage
        | CicsOperandName::Bookmark
        | CicsOperandName::Symbol
        | CicsOperandName::AtBookmark
        | CicsOperandName::ToBookmark
        | CicsOperandName::CharacterSet
        | CicsOperandName::SymbolValue => SlotUse::Input,
        CicsOperandName::SpoolToken => SlotUse::SpoolTokenInput,
        CicsOperandName::SpoolUserId => SlotUse::SpoolUserIdInput,
        CicsOperandName::SpoolClass => SlotUse::SpoolClassInput,
        CicsOperandName::SpoolNode => SlotUse::SpoolNodeInput,
        CicsOperandName::SpoolRecordLength => SlotUse::SpoolRecordLengthInput,
        CicsOperandName::SpoolOutDescr => SlotUse::SpoolOutDescrInput,
        CicsOperandName::SpoolMaxFlength => SlotUse::SpoolMaxFlengthInput,
        CicsOperandName::SpoolFrom => SlotUse::Input,
        CicsOperandName::SpoolFlength => SlotUse::SpoolMaxFlengthInput,
        CicsOperandName::CounterValue
        | CicsOperandName::CounterMinimum
        | CicsOperandName::CounterMaximum
        | CicsOperandName::CounterIncrement
        | CicsOperandName::CounterCompareMin
        | CicsOperandName::CounterCompareMax => SlotUse::CounterNumber,
        CicsOperandName::TraceNum | CicsOperandName::TraceFromLength => SlotUse::HalfwordInput,
        CicsOperandName::MonitorPoint => SlotUse::HalfwordInput,
        CicsOperandName::MonitorData1 | CicsOperandName::MonitorData2 => SlotUse::MonitorDataInput,
        CicsOperandName::DumpLength => SlotUse::HalfwordInput,
        CicsOperandName::DumpFlength | CicsOperandName::DumpNumSegments => SlotUse::FullwordInput,
        CicsOperandName::WebUrlLength
        | CicsOperandName::WebHostLength
        | CicsOperandName::WebPathLength
        | CicsOperandName::WebQueryStringLength => SlotUse::FullwordInput,
        CicsOperandName::WebMethodLength
        | CicsOperandName::WebVersionLength
        | CicsOperandName::WebRealmLength => SlotUse::FullwordInput,
        CicsOperandName::WebNameLength | CicsOperandName::WebValueLength => SlotUse::FullwordInput,
        CicsOperandName::WebStatusLength | CicsOperandName::WebFromLength => SlotUse::FullwordInput,
        CicsOperandName::WebReceiveMaxLength | CicsOperandName::WebReceiveStatusLength => {
            SlotUse::FullwordInput
        }
        CicsOperandName::WebStatusCode => SlotUse::HalfwordInput,
        CicsOperandName::WebPortNumber => SlotUse::FullwordInput,
        _ => SlotUse::Input,
    }
}

pub(super) const fn output_slot_use(name: CicsOutputName) -> SlotUse {
    match name {
        CicsOutputName::CounterValue
        | CicsOutputName::CounterMinimum
        | CicsOutputName::CounterMaximum => SlotUse::CounterNumber,
        CicsOutputName::Abstime => SlotUse::AbstimeOutput,
        CicsOutputName::TimerStatus => SlotUse::FullwordOutput,
        CicsOutputName::EventName | CicsOutputName::SubEventName => SlotUse::Output,
        CicsOutputName::EventType | CicsOutputName::FireStatus => SlotUse::FullwordOutput,
        CicsOutputName::Commarea => SlotUse::Output,
        CicsOutputName::Into => SlotUse::Output,
        CicsOutputName::Partn => SlotUse::Output,
        CicsOutputName::SetPointer => SlotUse::PointerOutput,
        CicsOutputName::SetPointer64 => SlotUse::Pointer64Output,
        CicsOutputName::WebEprSet => SlotUse::PointerOutput,
        CicsOutputName::WebEprLength => SlotUse::FullwordOutput,
        CicsOutputName::WebAction
        | CicsOutputName::WebMessageId
        | CicsOutputName::WebRelatesUri
        | CicsOutputName::WebRelatesType
        | CicsOutputName::WebEprInto => SlotUse::Output,
        CicsOutputName::Ridfld => SlotUse::Output,
        CicsOutputName::Token => SlotUse::FullwordOutput,
        CicsOutputName::ReturnTransId | CicsOutputName::ReturnTermId | CicsOutputName::Queue => {
            SlotUse::Output
        }
        CicsOutputName::ElementName
        | CicsOutputName::ElementNamespace
        | CicsOutputName::TypeName
        | CicsOutputName::TypeNamespace => SlotUse::Output,
        CicsOutputName::Milliseconds => SlotUse::MillisecondsOutput,
        CicsOutputName::Mmddyy | CicsOutputName::Time | CicsOutputName::Yymmdd => {
            SlotUse::FormatTextOutput(8)
        }
        CicsOutputName::Mmddyyyy | CicsOutputName::Yyyymmdd => SlotUse::FormatTextOutput(10),
        CicsOutputName::Yyddd => SlotUse::FormatTextOutput(6),
        CicsOutputName::Resp
        | CicsOutputName::SecurityRead
        | CicsOutputName::SecurityUpdate
        | CicsOutputName::SecurityControl
        | CicsOutputName::SecurityAlter
        | CicsOutputName::SecurityChangeTime
        | CicsOutputName::SecurityDaysLeft
        | CicsOutputName::SecurityEsmReason
        | CicsOutputName::SecurityEsmResp
        | CicsOutputName::SecurityExpiryTime
        | CicsOutputName::SecurityInvalidCount
        | CicsOutputName::SecurityLastUseTime
        | CicsOutputName::Resp2
        | CicsOutputName::Length
        | CicsOutputName::NumItems
        | CicsOutputName::JournalReqId => SlotUse::NumericOutput,
        CicsOutputName::ElementNameLength
        | CicsOutputName::ElementNamespaceLength
        | CicsOutputName::TypeNameLength
        | CicsOutputName::TypeNamespaceLength => SlotUse::NumericOutput,
        CicsOutputName::Assign(output) => SlotUse::AssignOutput(output),
        CicsOutputName::DocumentToken => SlotUse::Output,
        CicsOutputName::DocumentSize => SlotUse::NumericOutput,
        CicsOutputName::SpoolToken => SlotUse::SpoolTokenOutput,
        CicsOutputName::SpoolToFlength => SlotUse::SpoolToFlengthOutput,
        CicsOutputName::DumpId => SlotUse::DumpIdOutput,
        CicsOutputName::WebSchemeName
        | CicsOutputName::WebHost
        | CicsOutputName::WebPath
        | CicsOutputName::WebQueryString => SlotUse::Output,
        CicsOutputName::WebHttpMethod
        | CicsOutputName::WebHttpVersion
        | CicsOutputName::WebUriMap
        | CicsOutputName::WebRealm
        | CicsOutputName::WebValue => SlotUse::Output,
        CicsOutputName::WebBrowseName => SlotUse::Output,
        CicsOutputName::WebRetrieveDocumentToken => SlotUse::Output,
        CicsOutputName::WebReceiveInto
        | CicsOutputName::WebReceiveStatusText
        | CicsOutputName::WebReceiveMediaType
        | CicsOutputName::WebReceiveBodyCharset => SlotUse::Output,
        CicsOutputName::WebReceiveLength | CicsOutputName::WebReceiveStatusLength => {
            SlotUse::FullwordOutput
        }
        CicsOutputName::WebReceiveStatusCode => SlotUse::HalfwordOutput,
        CicsOutputName::WebConverseInto
        | CicsOutputName::WebConverseStatusText
        | CicsOutputName::WebConverseMediaType
        | CicsOutputName::WebConverseBodyCharset => SlotUse::Output,
        CicsOutputName::WebConverseToLength | CicsOutputName::WebConverseStatusLength => {
            SlotUse::FullwordOutput
        }
        CicsOutputName::WebConverseStatusCode => SlotUse::HalfwordOutput,
        CicsOutputName::WebHostLength
        | CicsOutputName::WebHostType
        | CicsOutputName::WebPortNumber
        | CicsOutputName::WebPathLength
        | CicsOutputName::WebQueryStringLength => SlotUse::FullwordOutput,
        CicsOutputName::WebScheme
        | CicsOutputName::WebMethodLength
        | CicsOutputName::WebVersionLength
        | CicsOutputName::WebRequestType
        | CicsOutputName::WebRealmLength
        | CicsOutputName::WebValueLength => SlotUse::FullwordOutput,
        CicsOutputName::WebBrowseNameLength => SlotUse::FullwordOutput,
        CicsOutputName::WebSessionToken => SlotUse::Output,
        CicsOutputName::WebHttpVNum | CicsOutputName::WebHttpRNum => SlotUse::HalfwordOutput,
    }
}

pub(super) const fn host_operation(operation: CicsPlanOperation) -> CicsOperation {
    match operation {
        CicsPlanOperation::Abend => CicsOperation::Abend,
        CicsPlanOperation::AddSubevent => CicsOperation::AddSubevent,
        CicsPlanOperation::RemoveSubevent => CicsOperation::RemoveSubevent,
        CicsPlanOperation::DeleteEvent => CicsOperation::DeleteEvent,
        CicsPlanOperation::CheckTimer => CicsOperation::CheckTimer,
        CicsPlanOperation::DefineTimer => CicsOperation::DefineTimer,
        CicsPlanOperation::DeleteTimer => CicsOperation::DeleteTimer,
        CicsPlanOperation::RetrieveReattachEvent => CicsOperation::RetrieveReattachEvent,
        CicsPlanOperation::RetrieveSubevent => CicsOperation::RetrieveSubevent,
        CicsPlanOperation::TestEvent => CicsOperation::TestEvent,
        CicsPlanOperation::SignalEvent => CicsOperation::SignalEvent,
        CicsPlanOperation::ForceTimer => CicsOperation::ForceTimer,
        CicsPlanOperation::Address => CicsOperation::Address,
        CicsPlanOperation::AddressSet => CicsOperation::AddressSet,
        CicsPlanOperation::Asktime => CicsOperation::Asktime,
        CicsPlanOperation::AsktimeEib => CicsOperation::AsktimeEib,
        CicsPlanOperation::FormatTime => CicsOperation::FormatTime,
        CicsPlanOperation::Cancel => CicsOperation::Cancel,
        CicsPlanOperation::Delay => CicsOperation::Delay,
        CicsPlanOperation::DefineCounter => CicsOperation::DefineCounter,
        CicsPlanOperation::DefineDCounter => CicsOperation::DefineDCounter,
        CicsPlanOperation::DeleteCounter => CicsOperation::DeleteCounter,
        CicsPlanOperation::DeleteDCounter => CicsOperation::DeleteDCounter,
        CicsPlanOperation::GetCounter => CicsOperation::GetCounter,
        CicsPlanOperation::GetDCounter => CicsOperation::GetDCounter,
        CicsPlanOperation::QueryCounter => CicsOperation::QueryCounter,
        CicsPlanOperation::QueryDCounter => CicsOperation::QueryDCounter,
        CicsPlanOperation::RewindCounter => CicsOperation::RewindCounter,
        CicsPlanOperation::RewindDCounter => CicsOperation::RewindDCounter,
        CicsPlanOperation::UpdateCounter => CicsOperation::UpdateCounter,
        CicsPlanOperation::UpdateDCounter => CicsOperation::UpdateDCounter,
        CicsPlanOperation::ChangeTask => CicsOperation::ChangeTask,
        CicsPlanOperation::Deq => CicsOperation::Deq,
        CicsPlanOperation::Enq => CicsOperation::Enq,
        CicsPlanOperation::HandleAid => CicsOperation::HandleAid,
        CicsPlanOperation::HandleAbend => CicsOperation::HandleAbend,
        CicsPlanOperation::HandleCondition => CicsOperation::HandleCondition,
        CicsPlanOperation::IgnoreCondition => CicsOperation::IgnoreCondition,
        CicsPlanOperation::InvokeApplication => CicsOperation::InvokeApplication,
        CicsPlanOperation::IssueAbort => CicsOperation::IssueAbort,
        CicsPlanOperation::IssueAdd => CicsOperation::IssueAdd,
        CicsPlanOperation::IssueEnd => CicsOperation::IssueEnd,
        CicsPlanOperation::IssueErase => CicsOperation::IssueErase,
        CicsPlanOperation::IssueNote => CicsOperation::IssueNote,
        CicsPlanOperation::IssueQuery => CicsOperation::IssueQuery,
        CicsPlanOperation::IssueReceive => CicsOperation::IssueReceive,
        CicsPlanOperation::IssueReplace => CicsOperation::IssueReplace,
        CicsPlanOperation::IssueSend => CicsOperation::IssueSend,
        CicsPlanOperation::Route => CicsOperation::Route,
        CicsPlanOperation::IssueWait => CicsOperation::IssueWait,
        CicsPlanOperation::Load => CicsOperation::Load,
        CicsPlanOperation::Release => CicsOperation::Release,
        CicsPlanOperation::Link => CicsOperation::Link,
        CicsPlanOperation::Xctl => CicsOperation::Xctl,
        CicsPlanOperation::Return => CicsOperation::Return,
        CicsPlanOperation::StartBrowse => CicsOperation::StartBrowse,
        CicsPlanOperation::ResetBrowse => CicsOperation::ResetBrowse,
        CicsPlanOperation::Unlock => CicsOperation::Unlock,
        CicsPlanOperation::ReadNext => CicsOperation::ReadNext,
        CicsPlanOperation::ReadPrev => CicsOperation::ReadPrev,
        CicsPlanOperation::ReadTransientData => CicsOperation::ReadTransientData,
        CicsPlanOperation::EndBrowse => CicsOperation::EndBrowse,
        CicsPlanOperation::Delete => CicsOperation::Delete,
        CicsPlanOperation::Write => CicsOperation::Write,
        CicsPlanOperation::WriteTransientData => CicsOperation::WriteTransientData,
        CicsPlanOperation::DeleteTransientData => CicsOperation::DeleteTransientData,
        CicsPlanOperation::DeleteTemporaryStorage => CicsOperation::DeleteTemporaryStorage,
        CicsPlanOperation::ReadTemporaryStorage => CicsOperation::ReadTemporaryStorage,
        CicsPlanOperation::WriteTemporaryStorage => CicsOperation::WriteTemporaryStorage,
        CicsPlanOperation::Getmain => CicsOperation::Getmain,
        CicsPlanOperation::Getmain64 => CicsOperation::Getmain64,
        CicsPlanOperation::Freemain => CicsOperation::Freemain,
        CicsPlanOperation::Freemain64 => CicsOperation::Freemain64,
        CicsPlanOperation::ReceiveMap => CicsOperation::ReceiveMap,
        CicsPlanOperation::SendMap => CicsOperation::SendMap,
        CicsPlanOperation::SendText => CicsOperation::SendText,
        CicsPlanOperation::SendPartnset => CicsOperation::SendPartnset,
        CicsPlanOperation::SendControl => CicsOperation::SendControl,
        CicsPlanOperation::SendPage => CicsOperation::SendPage,
        CicsPlanOperation::ReceivePartn => CicsOperation::ReceivePartn,
        CicsPlanOperation::PopHandle => CicsOperation::PopHandle,
        CicsPlanOperation::PushHandle => CicsOperation::PushHandle,
        CicsPlanOperation::Read => CicsOperation::Read,
        CicsPlanOperation::Rewrite => CicsOperation::Rewrite,
        CicsPlanOperation::SetAssociationUserCorrData => CicsOperation::SetAssociationUserCorrData,
        CicsPlanOperation::SpoolClose => CicsOperation::SpoolClose,
        CicsPlanOperation::SpoolOpenInput => CicsOperation::SpoolOpenInput,
        CicsPlanOperation::SpoolOpenOutput => CicsOperation::SpoolOpenOutput,
        CicsPlanOperation::SpoolRead => CicsOperation::SpoolRead,
        CicsPlanOperation::SpoolWrite => CicsOperation::SpoolWrite,
        CicsPlanOperation::EnterTraceNum => CicsOperation::EnterTraceNum,
        CicsPlanOperation::Monitor => CicsOperation::Monitor,
        CicsPlanOperation::DumpTransaction => CicsOperation::DumpTransaction,
        CicsPlanOperation::Dump => CicsOperation::Dump,
        CicsPlanOperation::Trace => CicsOperation::Trace,
        CicsPlanOperation::EnterTraceId => CicsOperation::EnterTraceId,
        CicsPlanOperation::Syncpoint => CicsOperation::Syncpoint,
        CicsPlanOperation::Suspend => CicsOperation::Suspend,
        CicsPlanOperation::WaitEvent => CicsOperation::WaitEvent,
        CicsPlanOperation::WaitExternal => CicsOperation::WaitExternal,
        CicsPlanOperation::Assign => CicsOperation::Assign,
        CicsPlanOperation::PurgeMessage => CicsOperation::PurgeMessage,
        CicsPlanOperation::QuerySecurity => CicsOperation::QuerySecurity,
        CicsPlanOperation::VerifyPassword => CicsOperation::VerifyPassword,
        CicsPlanOperation::ChangePassword => CicsOperation::ChangePassword,
        CicsPlanOperation::ChangePhrase => CicsOperation::ChangePhrase,
        CicsPlanOperation::RequestPassTicket => CicsOperation::RequestPassTicket,
        CicsPlanOperation::VerifyPhrase => CicsOperation::VerifyPhrase,
        CicsPlanOperation::Start => CicsOperation::Start,
        CicsPlanOperation::Retrieve => CicsOperation::Retrieve,
        CicsPlanOperation::DocumentCreate => CicsOperation::DocumentCreate,
        CicsPlanOperation::DefineInputEvent => CicsOperation::DefineInputEvent,
        CicsPlanOperation::DefineCompositeEvent => CicsOperation::DefineCompositeEvent,
        CicsPlanOperation::DocumentDelete => CicsOperation::DocumentDelete,
        CicsPlanOperation::DocumentInsert => CicsOperation::DocumentInsert,
        CicsPlanOperation::DocumentRetrieve => CicsOperation::DocumentRetrieve,
        CicsPlanOperation::DocumentSet => CicsOperation::DocumentSet,
        CicsPlanOperation::InvokeService => CicsOperation::InvokeService,
        CicsPlanOperation::SoapFaultAdd => CicsOperation::SoapFaultAdd,
        CicsPlanOperation::SoapFaultCreate => CicsOperation::SoapFaultCreate,
        CicsPlanOperation::SoapFaultDelete => CicsOperation::SoapFaultDelete,
        CicsPlanOperation::WsaContextBuild => CicsOperation::WsaContextBuild,
        CicsPlanOperation::WsaContextDelete => CicsOperation::WsaContextDelete,
        CicsPlanOperation::WsaContextGet => CicsOperation::WsaContextGet,
        CicsPlanOperation::WsaEprCreate => CicsOperation::WsaEprCreate,
        CicsPlanOperation::TransformDataToJson => CicsOperation::TransformDataToJson,
        CicsPlanOperation::TransformDataToXml => CicsOperation::TransformDataToXml,
        CicsPlanOperation::TransformJsonToData => CicsOperation::TransformJsonToData,
        CicsPlanOperation::TransformXmlToData => CicsOperation::TransformXmlToData,
        CicsPlanOperation::WaitJournalName => CicsOperation::WaitJournalName,
        CicsPlanOperation::WaitJournalNum => CicsOperation::WaitJournalNum,
        CicsPlanOperation::WriteJournalName => CicsOperation::WriteJournalName,
        CicsPlanOperation::WriteJournalNum => CicsOperation::WriteJournalNum,
        CicsPlanOperation::WebParseUrl => CicsOperation::WebParseUrl,
        CicsPlanOperation::WebOpen => CicsOperation::WebOpen,
        CicsPlanOperation::WebClose => CicsOperation::WebClose,
        CicsPlanOperation::WebExtract => CicsOperation::WebExtract,
        CicsPlanOperation::ExtractWeb => CicsOperation::ExtractWeb,
        CicsPlanOperation::WebRead => CicsOperation::WebRead,
        CicsPlanOperation::WebStartBrowse => CicsOperation::WebStartBrowse,
        CicsPlanOperation::WebReadNext => CicsOperation::WebReadNext,
        CicsPlanOperation::WebEndBrowse => CicsOperation::WebEndBrowse,
        CicsPlanOperation::WebWrite => CicsOperation::WebWrite,
        CicsPlanOperation::WebSend => CicsOperation::WebSend,
        CicsPlanOperation::WebRetrieve => CicsOperation::WebRetrieve,
        CicsPlanOperation::WebReceive => CicsOperation::WebReceive,
        CicsPlanOperation::WebConverse => CicsOperation::WebConverse,
    }
}

pub(super) const fn operand(name: CicsOperandName) -> &'static str {
    match name {
        CicsOperandName::ResClass => "RESCLASS",
        CicsOperandName::ResId => "RESID",
        CicsOperandName::ResIdLength => "RESIDLENGTH",
        CicsOperandName::ResType => "RESTYPE",
        CicsOperandName::LogMessage => "LOGMESSAGE",
        CicsOperandName::SecurityUserId => "USERID",
        CicsOperandName::SecurityGroupId => "GROUPID",
        CicsOperandName::SecurityPassword => "PASSWORD",
        CicsOperandName::SecurityNewPassword => "NEWPASSWORD",
        CicsOperandName::SecurityNewPhrase => "NEWPHRASE",
        CicsOperandName::SecurityNewPhraseLen => "NEWPHRASELEN",
        CicsOperandName::SecurityEsmAppName => "ESMAPPNAME",
        CicsOperandName::SecurityPhrase => "PHRASE",
        CicsOperandName::SecurityPhraseLen => "PHRASELEN",
        CicsOperandName::Abcode => "ABCODE",
        CicsOperandName::Event => "EVENT",
        CicsOperandName::SubEvent => "SUBEVENT",
        CicsOperandName::SubEvent1 => "SUBEVENT1",
        CicsOperandName::SubEvent2 => "SUBEVENT2",
        CicsOperandName::SubEvent3 => "SUBEVENT3",
        CicsOperandName::SubEvent4 => "SUBEVENT4",
        CicsOperandName::SubEvent5 => "SUBEVENT5",
        CicsOperandName::SubEvent6 => "SUBEVENT6",
        CicsOperandName::SubEvent7 => "SUBEVENT7",
        CicsOperandName::SubEvent8 => "SUBEVENT8",
        CicsOperandName::SignalFrom => "FROM",
        CicsOperandName::SignalFromLength => "FROMLENGTH",
        CicsOperandName::SignalFromChannel => "FROMCHANNEL",
        CicsOperandName::Timer => "TIMER",
        CicsOperandName::TimerDays => "DAYS",
        CicsOperandName::TimerHours => "HOURS",
        CicsOperandName::TimerMinutes => "MINUTES",
        CicsOperandName::TimerSeconds => "SECONDS",
        CicsOperandName::TimerYear => "YEAR",
        CicsOperandName::TimerMonth => "MONTH",
        CicsOperandName::TimerDayOfMonth => "DAYOFMONTH",
        CicsOperandName::TimerDayOfYear => "DAYOFYEAR",
        CicsOperandName::Label => "LABEL",
        CicsOperandName::Program => "PROGRAM",
        CicsOperandName::Commarea => "COMMAREA",
        CicsOperandName::TransId => "TRANSID",
        CicsOperandName::TermId => "TERMID",
        CicsOperandName::ReturnTransId => "RTRANSID",
        CicsOperandName::ReturnTermId => "RTERMID",
        CicsOperandName::UserId => "USERID",
        CicsOperandName::File => "FILE",
        CicsOperandName::Dataset => "DATASET",
        CicsOperandName::From => "FROM",
        CicsOperandName::Ridfld => "RIDFLD",
        CicsOperandName::Token => "TOKEN",
        CicsOperandName::Queue => "QUEUE",
        CicsOperandName::Qname => "QNAME",
        CicsOperandName::SysId => "SYSID",
        CicsOperandName::CommareaPointer => "COMMAREA",
        CicsOperandName::Map => "MAP",
        CicsOperandName::Mapset => "MAPSET",
        CicsOperandName::DestId => "DESTID",
        CicsOperandName::DestIdLength => "DESTIDLENG",
        CicsOperandName::Subaddress => "SUBADDR",
        CicsOperandName::Volume => "VOLUME",
        CicsOperandName::VolumeLength => "VOLUMELENG",
        CicsOperandName::NumRec => "NUMREC",
        CicsOperandName::Errterm => "ERRTERM",
        CicsOperandName::RouteTitle => "TITLE",
        CicsOperandName::RouteList => "LIST",
        CicsOperandName::Opclass => "OPCLASS",
        CicsOperandName::KeyNumber => "KEYNUMBER",
        CicsOperandName::Partnset => "PARTNSET",
        CicsOperandName::ControlCursor => "CURSOR",
        CicsOperandName::Msr => "MSR",
        CicsOperandName::Outpartn => "OUTPARTN",
        CicsOperandName::Actpartn => "ACTPARTN",
        CicsOperandName::Ldc => "LDC",
        CicsOperandName::Trailer => "TRAILER",
        CicsOperandName::Fmhparm => "FMHPARM",
        CicsOperandName::Resource => "RESOURCE",
        CicsOperandName::Length => "LENGTH",
        CicsOperandName::DataLength => "DATALENGTH",
        CicsOperandName::MaxLifetime => "MAXLIFETIME",
        CicsOperandName::Priority => "PRIORITY",
        CicsOperandName::UserCorrData => "USERCORRDATA",
        CicsOperandName::SetAddress => "SET.ADDRESS",
        CicsOperandName::SetPointer => "SET.POINTER",
        CicsOperandName::UsingAddress => "USING.ADDRESS",
        CicsOperandName::UsingPointer => "USING.POINTER",
        CicsOperandName::Conditions => "CONDITIONS",
        CicsOperandName::Aids => "AIDS",
        CicsOperandName::Abstime => "ABSTIME",
        CicsOperandName::DateSep => "DATESEP",
        CicsOperandName::TimeSep => "TIMESEP",
        CicsOperandName::KeyLength => "KEYLENGTH",
        CicsOperandName::ReqId => "REQID",
        CicsOperandName::Interval => "INTERVAL",
        CicsOperandName::StartTime => "TIME",
        CicsOperandName::Hours => "HOURS",
        CicsOperandName::Minutes => "MINUTES",
        CicsOperandName::Seconds => "SECONDS",
        CicsOperandName::Milliseconds => "MILLISECS",
        CicsOperandName::Flength => "FLENGTH",
        CicsOperandName::Flength64 => "FLENGTH",
        CicsOperandName::Location64 => "LOCATION",
        CicsOperandName::Abi64 => "ABI64",
        CicsOperandName::InitImage => "INITIMG",
        CicsOperandName::DataPointer => "DATAPOINTER",
        CicsOperandName::DataPointer64 => "DATAPOINTER",
        CicsOperandName::DataArea => "DATA",
        CicsOperandName::DataArea64 => "DATA",
        CicsOperandName::EventControlAddress => "ECADDR",
        CicsOperandName::WaitName => "NAME",
        CicsOperandName::EcbList => "ECBLIST",
        CicsOperandName::NumEvents => "NUMEVENTS",
        CicsOperandName::Purgeability => "PURGEABILITY",
        CicsOperandName::Item => "ITEM",
        CicsOperandName::Application => "APPLICATION",
        CicsOperandName::Platform => "PLATFORM",
        CicsOperandName::ApplicationOperation => "OPERATION",
        CicsOperandName::MajorVersion => "MAJORVERSION",
        CicsOperandName::MinorVersion => "MINORVERSION",
        CicsOperandName::Channel => "CHANNEL",
        CicsOperandName::LoadSet => "SET",
        CicsOperandName::Entry => "ENTRY",
        CicsOperandName::LoadLength => "LENGTH",
        CicsOperandName::LoadFlength => "FLENGTH",
        CicsOperandName::DocumentToken => "DOCTOKEN",
        CicsOperandName::Text => "TEXT",
        CicsOperandName::Binary => "BINARY",
        CicsOperandName::FromDocument => "FROMDOC",
        CicsOperandName::Template => "TEMPLATE",
        CicsOperandName::SymbolList => "SYMBOLLIST",
        CicsOperandName::ListLength => "LISTLENGTH",
        CicsOperandName::Delimiter => "DELIMITER",
        CicsOperandName::HostCodePage => "HOSTCODEPAGE",
        CicsOperandName::Bookmark => "BOOKMARK",
        CicsOperandName::Symbol => "SYMBOL",
        CicsOperandName::AtBookmark => "AT",
        CicsOperandName::ToBookmark => "TO",
        CicsOperandName::MaximumLength => "MAXLENGTH",
        CicsOperandName::CharacterSet => "CHARACTERSET",
        CicsOperandName::SymbolValue => "VALUE",
        CicsOperandName::Service => "SERVICE",
        CicsOperandName::ServiceOperation => "OPERATION",
        CicsOperandName::Uri => "URI",
        CicsOperandName::UriMap => "URIMAP",
        CicsOperandName::Scope => "SCOPE",
        CicsOperandName::ScopeLen => "SCOPELEN",
        CicsOperandName::FaultCode => "FAULTCODE",
        CicsOperandName::FaultCodeStr => "FAULTCODESTR",
        CicsOperandName::FaultCodeLen => "FAULTCODELEN",
        CicsOperandName::FaultString => "FAULTSTRING",
        CicsOperandName::FaultStrLen => "FAULTSTRLEN",
        CicsOperandName::NatLang => "NATLANG",
        CicsOperandName::SoapRole => "ROLE",
        CicsOperandName::RoleLength => "ROLELENGTH",
        CicsOperandName::FaultActor => "FAULTACTOR",
        CicsOperandName::FaultActLen => "FAULTACTLEN",
        CicsOperandName::Detail => "DETAIL",
        CicsOperandName::DetailLength => "DETAILLENGTH",
        CicsOperandName::FromCcsid => "FROMCCSID",
        CicsOperandName::SubcodeStr => "SUBCODESTR",
        CicsOperandName::SubcodeLen => "SUBCODELEN",
        CicsOperandName::ContextType => "CONTEXTTYPE",
        CicsOperandName::Action => "ACTION",
        CicsOperandName::MessageId => "MESSAGEID",
        CicsOperandName::RelatesUri => "RELATESURI",
        CicsOperandName::RelatesType => "RELATESTYPE",
        CicsOperandName::RelatesIndex => "RELATESINDEX",
        CicsOperandName::EprType => "EPRTYPE",
        CicsOperandName::EprField => "EPRFIELD",
        CicsOperandName::EprFrom => "EPRFROM",
        CicsOperandName::EprLength => "EPRLENGTH",
        CicsOperandName::FromCodepage => "FROMCODEPAGE",
        CicsOperandName::IntoCcsid => "INTOCCSID",
        CicsOperandName::IntoCodepage => "INTOCODEPAGE",
        CicsOperandName::Address => "ADDRESS",
        CicsOperandName::RefParms => "REFPARMS",
        CicsOperandName::RefParmsLen => "REFPARMSLEN",
        CicsOperandName::Metadata => "METADATA",
        CicsOperandName::MetadataLen => "METADATALEN",
        CicsOperandName::InContainer => "INCONTAINER",
        CicsOperandName::OutContainer => "OUTCONTAINER",
        CicsOperandName::Transformer => "TRANSFORMER",
        CicsOperandName::DataContainer => "DATCONTAINER",
        CicsOperandName::XmlContainer => "XMLCONTAINER",
        CicsOperandName::XmlTransform => "XMLTRANSFORM",
        CicsOperandName::NsContainer => "NSCONTAINER",
        CicsOperandName::ElementName => "ELEMNAME",
        CicsOperandName::ElementNameLength => "ELEMNAMELEN",
        CicsOperandName::ElementNamespace => "ELEMNS",
        CicsOperandName::ElementNamespaceLength => "ELEMNSLEN",
        CicsOperandName::TypeName => "TYPENAME",
        CicsOperandName::TypeNameLength => "TYPENAMELEN",
        CicsOperandName::TypeNamespace => "TYPENS",
        CicsOperandName::TypeNamespaceLength => "TYPENSLEN",
        CicsOperandName::JournalName => "JOURNALNAME",
        CicsOperandName::JournalNum => "JOURNALNUM",
        CicsOperandName::JournalReqId => "REQID",
        CicsOperandName::JournalTypeId => "JTYPEID",
        CicsOperandName::JournalFrom => "FROM",
        CicsOperandName::JournalFlength => "FLENGTH",
        CicsOperandName::JournalPrefix => "PREFIX",
        CicsOperandName::JournalPfxLeng => "PFXLENG",
        CicsOperandName::SpoolToken => "TOKEN",
        CicsOperandName::SpoolUserId => "USERID",
        CicsOperandName::SpoolClass => "CLASS",
        CicsOperandName::SpoolNode => "NODE",
        CicsOperandName::SpoolRecordLength => "RECORDLENGTH",
        CicsOperandName::SpoolOutDescr => "OUTDESCR",
        CicsOperandName::SpoolMaxFlength => "MAXFLENGTH",
        CicsOperandName::SpoolFrom => "FROM",
        CicsOperandName::SpoolFlength => "FLENGTH",
        CicsOperandName::CounterName => "COUNTER",
        CicsOperandName::CounterPool => "POOL",
        CicsOperandName::CounterValue => "VALUE",
        CicsOperandName::CounterMinimum => "MINIMUM",
        CicsOperandName::CounterMaximum => "MAXIMUM",
        CicsOperandName::CounterIncrement => "INCREMENT",
        CicsOperandName::CounterCompareMin => "COMPAREMIN",
        CicsOperandName::CounterCompareMax => "COMPAREMAX",
        CicsOperandName::TraceNum => "TRACENUM",
        CicsOperandName::TraceFrom => "FROM",
        CicsOperandName::TraceFromLength => "FROMLENGTH",
        CicsOperandName::TraceResource => "RESOURCE",
        CicsOperandName::MonitorPoint => "POINT",
        CicsOperandName::MonitorEntryName => "ENTRYNAME",
        CicsOperandName::MonitorData1 => "DATA1",
        CicsOperandName::MonitorData2 => "DATA2",
        CicsOperandName::DumpCode => "DUMPCODE",
        CicsOperandName::DumpFrom => "FROM",
        CicsOperandName::DumpLength => "LENGTH",
        CicsOperandName::DumpFlength => "FLENGTH",
        CicsOperandName::DumpSegmentList => "SEGMENTLIST",
        CicsOperandName::DumpLengthList => "LENGTHLIST",
        CicsOperandName::DumpNumSegments => "NUMSEGMENTS",
        CicsOperandName::TraceId => "TRACEID",
        CicsOperandName::TraceIdFrom => "FROM",
        CicsOperandName::TraceIdResource => "RESOURCE",
        CicsOperandName::TraceEntryName => "ENTRYNAME",
        CicsOperandName::WebUrl => "URL",
        CicsOperandName::WebUrlLength => "URLLENGTH",
        CicsOperandName::WebHostLength => "HOSTLENGTH",
        CicsOperandName::WebPathLength => "PATHLENGTH",
        CicsOperandName::WebQueryStringLength => "QUERYSTRLEN",
        CicsOperandName::WebHost => "HOST",
        CicsOperandName::WebSessionToken => "SESSTOKEN",
        CicsOperandName::WebMethodLength => "METHODLENGTH",
        CicsOperandName::WebVersionLength => "VERSIONLEN",
        CicsOperandName::WebRealmLength => "REALMLEN",
        CicsOperandName::WebHttpHeaderName => "HTTPHEADER",
        CicsOperandName::WebQueryParmName => "QUERYPARM",
        CicsOperandName::WebFormFieldName => "FORMFIELD",
        CicsOperandName::WebNameLength => "NAMELENGTH",
        CicsOperandName::WebValueLength => "VALUELENGTH",
        CicsOperandName::WebBrowseStartName => "BROWSESTARTNAME",
        CicsOperandName::WebHeaderValue => "VALUE",
        CicsOperandName::WebMethod => "METHOD",
        CicsOperandName::WebAction => "ACTION",
        CicsOperandName::WebCloseStatus => "CLOSESTATUS",
        CicsOperandName::WebDocumentToken => "DOCTOKEN",
        CicsOperandName::WebStatusCode => "STATUSCODE",
        CicsOperandName::WebStatusText => "STATUSTEXT",
        CicsOperandName::WebStatusLength => "STATUSLEN",
        CicsOperandName::WebFrom => "FROM",
        CicsOperandName::WebFromLength => "FROMLENGTH",
        CicsOperandName::WebPathInput => "PATH",
        CicsOperandName::WebQueryInput => "QUERYSTRING",
        CicsOperandName::WebMediaType => "MEDIATYPE",
        CicsOperandName::WebSendUriMap => "URIMAP",
        CicsOperandName::WebReceiveMaxLength => "MAXLENGTH",
        CicsOperandName::WebReceiveStatusLength => "STATUSLEN",
        CicsOperandName::WebPortNumber => "PORTNUMBER",
        CicsOperandName::WebScheme => "SCHEME",
        CicsOperandName::WebUriMap => "URIMAP",
        CicsOperandName::WebCertificate => "CERTIFICATE",
        CicsOperandName::WebCodePage => "CODEPAGE",
    }
}

pub(super) const fn operand_for(
    operation: CicsPlanOperation,
    name: CicsOperandName,
) -> &'static str {
    if matches!(
        operation,
        CicsPlanOperation::DefineDCounter
            | CicsPlanOperation::DeleteDCounter
            | CicsPlanOperation::GetDCounter
            | CicsPlanOperation::QueryDCounter
            | CicsPlanOperation::RewindDCounter
            | CicsPlanOperation::UpdateDCounter
    ) && matches!(name, CicsOperandName::CounterName)
    {
        "DCOUNTER"
    } else {
        operand(name)
    }
}

pub(super) const fn output(name: CicsOutputName) -> &'static str {
    match name {
        CicsOutputName::CounterValue => "VALUE",
        CicsOutputName::CounterMinimum => "MINIMUM",
        CicsOutputName::CounterMaximum => "MAXIMUM",
        CicsOutputName::Abstime => "ABSTIME",
        CicsOutputName::TimerStatus => "STATUS",
        CicsOutputName::EventName => "EVENT",
        CicsOutputName::SubEventName => "SUBEVENT",
        CicsOutputName::EventType => "EVENTTYPE",
        CicsOutputName::FireStatus => "FIRESTATUS",
        CicsOutputName::Commarea => "COMMAREA",
        CicsOutputName::Into => "INTO",
        CicsOutputName::Partn => "PARTN",
        CicsOutputName::SetPointer => "SET",
        CicsOutputName::SetPointer64 => "SET64",
        CicsOutputName::Ridfld => "RIDFLD",
        CicsOutputName::Token => "TOKEN",
        CicsOutputName::Milliseconds => "MILLISECONDS",
        CicsOutputName::Mmddyy => "MMDDYY",
        CicsOutputName::Mmddyyyy => "MMDDYYYY",
        CicsOutputName::Resp => "RESP",
        CicsOutputName::Resp2 => "RESP2",
        CicsOutputName::Time => "TIME",
        CicsOutputName::Yyddd => "YYDDD",
        CicsOutputName::Yymmdd => "YYMMDD",
        CicsOutputName::Yyyymmdd => "YYYYMMDD",
        CicsOutputName::Assign(output) => output.name(),
        CicsOutputName::Length => "LENGTH",
        CicsOutputName::ReturnTransId => "RTRANSID",
        CicsOutputName::ReturnTermId => "RTERMID",
        CicsOutputName::Queue => "QUEUE",
        CicsOutputName::NumItems => "NUMITEMS",
        CicsOutputName::DocumentToken => "DOCTOKEN",
        CicsOutputName::DocumentSize => "DOCSIZE",
        CicsOutputName::WebAction => "ACTION",
        CicsOutputName::WebMessageId => "MESSAGEID",
        CicsOutputName::WebRelatesUri => "RELATESURI",
        CicsOutputName::WebRelatesType => "RELATESTYPE",
        CicsOutputName::WebEprInto => "EPRINTO",
        CicsOutputName::WebEprSet => "EPRSET",
        CicsOutputName::WebEprLength => "EPRLENGTH",
        CicsOutputName::ElementName => "ELEMNAME",
        CicsOutputName::ElementNameLength => "ELEMNAMELEN",
        CicsOutputName::ElementNamespace => "ELEMNS",
        CicsOutputName::ElementNamespaceLength => "ELEMNSLEN",
        CicsOutputName::TypeName => "TYPENAME",
        CicsOutputName::TypeNameLength => "TYPENAMELEN",
        CicsOutputName::TypeNamespace => "TYPENS",
        CicsOutputName::TypeNamespaceLength => "TYPENSLEN",
        CicsOutputName::JournalReqId => "REQID",
        CicsOutputName::SpoolToken => "TOKEN",
        CicsOutputName::SpoolToFlength => "TOFLENGTH",
        CicsOutputName::DumpId => "DUMPID",
        CicsOutputName::WebSchemeName => "SCHEMENAME",
        CicsOutputName::WebHost => "HOST",
        CicsOutputName::WebHostLength => "HOSTLENGTH",
        CicsOutputName::WebHostType => "HOSTTYPE",
        CicsOutputName::WebPortNumber => "PORTNUMBER",
        CicsOutputName::WebPath => "PATH",
        CicsOutputName::WebPathLength => "PATHLENGTH",
        CicsOutputName::WebQueryString => "QUERYSTRING",
        CicsOutputName::WebQueryStringLength => "QUERYSTRLEN",
        CicsOutputName::WebSessionToken => "SESSTOKEN",
        CicsOutputName::WebHttpVNum => "HTTPVNUM",
        CicsOutputName::WebHttpRNum => "HTTPRNUM",
        CicsOutputName::WebScheme => "SCHEME",
        CicsOutputName::WebHttpMethod => "HTTPMETHOD",
        CicsOutputName::WebMethodLength => "METHODLENGTH",
        CicsOutputName::WebHttpVersion => "HTTPVERSION",
        CicsOutputName::WebVersionLength => "VERSIONLEN",
        CicsOutputName::WebRequestType => "REQUESTTYPE",
        CicsOutputName::WebUriMap => "URIMAP",
        CicsOutputName::WebRealm => "REALM",
        CicsOutputName::WebRealmLength => "REALMLEN",
        CicsOutputName::WebValue => "VALUE",
        CicsOutputName::WebValueLength => "VALUELENGTH",
        CicsOutputName::WebBrowseName => "BROWSENAME",
        CicsOutputName::WebBrowseNameLength => "NAMELENGTH",
        CicsOutputName::WebRetrieveDocumentToken => "DOCTOKEN",
        CicsOutputName::WebReceiveInto => "INTO",
        CicsOutputName::WebReceiveLength => "LENGTH",
        CicsOutputName::WebReceiveStatusCode => "STATUSCODE",
        CicsOutputName::WebReceiveStatusText => "STATUSTEXT",
        CicsOutputName::WebReceiveStatusLength => "STATUSLEN",
        CicsOutputName::WebReceiveMediaType => "MEDIATYPE",
        CicsOutputName::WebReceiveBodyCharset => "BODYCHARSET",
        CicsOutputName::WebConverseInto => "INTO",
        CicsOutputName::WebConverseToLength => "TOLENGTH",
        CicsOutputName::WebConverseStatusCode => "STATUSCODE",
        CicsOutputName::WebConverseStatusText => "STATUSTEXT",
        CicsOutputName::WebConverseStatusLength => "STATUSLEN",
        CicsOutputName::WebConverseMediaType => "MEDIATYPE",
        CicsOutputName::WebConverseBodyCharset => "BODYCHARSET",
    }
}

pub(super) const fn option(option: CicsPlanOption) -> &'static str {
    match option {
        CicsPlanOption::DefResp => "DEFRESP",
        CicsPlanOption::NoWait => "NOWAIT",
        CicsPlanOption::Rrn => "RRN",
        CicsPlanOption::Console => "CONSOLE",
        CicsPlanOption::PrintMedium => "PRINT",
        CicsPlanOption::Card => "CARD",
        CicsPlanOption::WpMedia1 => "WPMEDIA1",
        CicsPlanOption::WpMedia2 => "WPMEDIA2",
        CicsPlanOption::WpMedia3 => "WPMEDIA3",
        CicsPlanOption::Nleom => "NLEOM",
        CicsPlanOption::WpMedia4 => "WPMEDIA4",
        CicsPlanOption::Cancel => "CANCEL",
        CicsPlanOption::NoDump => "NODUMP",
        CicsPlanOption::Reset => "RESET",
        CicsPlanOption::Update => "UPDATE",
        CicsPlanOption::Rollback => "ROLLBACK",
        CicsPlanOption::NoHandle => "NOHANDLE",
        CicsPlanOption::AsIs => "ASIS",
        CicsPlanOption::Accum => "ACCUM",
        CicsPlanOption::Formfeed => "FORMFEED",
        CicsPlanOption::DefaultScreen => "DEFAULT",
        CicsPlanOption::AlternateScreen => "ALTERNATE",
        CicsPlanOption::EraseAup => "ERASEAUP",
        CicsPlanOption::Print => "PRINT",
        CicsPlanOption::Alarm => "ALARM",
        CicsPlanOption::Frset => "FRSET",
        CicsPlanOption::Paging => "PAGING",
        CicsPlanOption::Last => "LAST",
        CicsPlanOption::Honeom => "HONEOM",
        CicsPlanOption::L40 => "L40",
        CicsPlanOption::L64 => "L64",
        CicsPlanOption::L80 => "L80",
        CicsPlanOption::ReleasePage => "RELEASE",
        CicsPlanOption::RetainPage => "RETAIN",
        CicsPlanOption::Autopage => "AUTOPAGE",
        CicsPlanOption::CurrentPage => "CURRENT",
        CicsPlanOption::AllPages => "ALL",
        CicsPlanOption::NoAutopage => "NOAUTOPAGE",
        CicsPlanOption::OperPurge => "OPERPURGE",
        CicsPlanOption::Task => "TASK",
        CicsPlanOption::Uow => "UOW",
        CicsPlanOption::NoSuspend => "NOSUSPEND",
        CicsPlanOption::CounterNoSuspend => "NOSUSPEND",
        CicsPlanOption::CounterReduce => "REDUCE",
        CicsPlanOption::CounterWrap => "WRAP",
        CicsPlanOption::Erase => "ERASE",
        CicsPlanOption::Cursor => "CURSOR",
        CicsPlanOption::DateSep => "DATESEP",
        CicsPlanOption::TimeSep => "TIMESEP",
        CicsPlanOption::FreeKb => "FREEKB",
        CicsPlanOption::Gteq => "GTEQ",
        CicsPlanOption::Fmh => "FMH",
        CicsPlanOption::Protect => "PROTECT",
        CicsPlanOption::Wait => "WAIT",
        CicsPlanOption::After => "AFTER",
        CicsPlanOption::At => "AT",
        CicsPlanOption::For => "FOR",
        CicsPlanOption::Until => "UNTIL",
        CicsPlanOption::NoCheck => "NOCHECK",
        CicsPlanOption::MapOnly => "MAPONLY",
        CicsPlanOption::DataOnly => "DATAONLY",
        CicsPlanOption::DocumentDataOnly => "DATAONLY",
        CicsPlanOption::Generic => "GENERIC",
        CicsPlanOption::Equal => "EQUAL",
        CicsPlanOption::Terminal => "TERMINAL",
        CicsPlanOption::Purgeable => "PURGEABLE",
        CicsPlanOption::NotPurgeable => "NOTPURGEABLE",
        CicsPlanOption::Next => "NEXT",
        CicsPlanOption::RewriteTemporary => "REWRITE",
        CicsPlanOption::Auxiliary => "AUXILIARY",
        CicsPlanOption::Main => "MAIN",
        CicsPlanOption::ExactMatch => "EXACTMATCH",
        CicsPlanOption::Minimum => "MINIMUM",
        CicsPlanOption::Hold => "HOLD",
        CicsPlanOption::Unescaped => "UNESCAPED",
        CicsPlanOption::CicsDataKey64 => "CICSDATAKEY",
        CicsPlanOption::UserDataKey64 => "USERDATAKEY",
        CicsPlanOption::Shared64 => "SHARED",
        CicsPlanOption::Executable64 => "EXECUTABLE",
        CicsPlanOption::SpoolKeep => "KEEP",
        CicsPlanOption::SpoolDelete => "DELETE",
        CicsPlanOption::SpoolNoCc => "NOCC",
        CicsPlanOption::SpoolAsa => "ASA",
        CicsPlanOption::SpoolMcc => "MCC",
        CicsPlanOption::SpoolPrint => "PRINT",
        CicsPlanOption::SpoolPunch => "PUNCH",
        CicsPlanOption::SpoolLine => "LINE",
        CicsPlanOption::SpoolPage => "PAGE",
        CicsPlanOption::EventAnd => "AND",
        CicsPlanOption::EventOr => "OR",
        CicsPlanOption::TimerAfter => "AFTER",
        CicsPlanOption::TimerAt => "AT",
        CicsPlanOption::TimerOn => "ON",
        CicsPlanOption::AcqActivity => "ACQACTIVITY",
        CicsPlanOption::AcqProcess => "ACQPROCESS",
        CicsPlanOption::TraceException => "EXCEPTION",
        CicsPlanOption::DumpComplete => "COMPLETE",
        CicsPlanOption::DumpTask => "TASK",
        CicsPlanOption::DumpStorage => "STORAGE",
        CicsPlanOption::DumpProgram => "PROGRAM",
        CicsPlanOption::DumpTerminal => "TERMINAL",
        CicsPlanOption::DumpTables => "TABLES",
        CicsPlanOption::DumpFct => "FCT",
        CicsPlanOption::DumpPct => "PCT",
        CicsPlanOption::DumpPpt => "PPT",
        CicsPlanOption::DumpSit => "SIT",
        CicsPlanOption::DumpTct => "TCT",
        CicsPlanOption::DumpTrt => "TRT",
        CicsPlanOption::DumpDct => "DCT",
        CicsPlanOption::TraceOn => "ON",
        CicsPlanOption::TraceOff => "OFF",
        CicsPlanOption::TraceSystem => "SYSTEM",
        CicsPlanOption::TraceUser => "USER",
        CicsPlanOption::TraceEi => "EI",
        CicsPlanOption::TraceSingle => "SINGLE",
        CicsPlanOption::TraceAccount => "ACCOUNT",
        CicsPlanOption::TraceMonitor => "MONITOR",
        CicsPlanOption::TracePerform => "PERFORM",
        CicsPlanOption::WebBrowseHttpHeader => "HTTPHEADER",
        CicsPlanOption::WebBrowseQueryParm => "QUERYPARM",
        CicsPlanOption::WebBrowseFormField => "FORMFIELD",
        CicsPlanOption::WebNotruncate => "NOTRUNCATE",
        CicsPlanOption::WebNoClientConvert => "NOCLICONVERT",
        CicsPlanOption::WebNoServerConvert => "NOSRVCONVERT",
    }
}
