// @generated by tools/generate_mq_mqi_registry.py; do not edit.
pub(super) const PROJECTION_SHA256: &str =
    "0788fb791ee6a781efec7cb24a36362ab0aa86a65305c676d1c48ecaebe6311e";
pub(super) const MQIA_Q_TYPE: i32 = 20;
pub(super) const MQQT_LOCAL: i32 = 1;
pub(super) const MAX_INTEGER_SLOTS: usize = 256;
