// @generated by tools/generate_mq_mqi_registry.py; do not edit.
pub(super) const PROJECTION_SHA256: &str =
    "8ba5dd73b8cc3870dad202885073b821c9525c993e3477f46ddb9c304a825792";
pub(super) const MQIA_Q_TYPE: i32 = 20;
pub(super) const MQQT_LOCAL: i32 = 1;
pub(super) const MAX_INTEGER_SLOTS: usize = 256;
