use mainframe_env_ir::CicsAssignOutput;

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum HirCicsOutputName {
    Abstime,
    Commarea,
    Into,
    SetPointer,
    Ridfld,
    Milliseconds,
    Mmddyy,
    Mmddyyyy,
    Resp,
    Resp2,
    Time,
    Yyddd,
    Yymmdd,
    Yyyymmdd,
    Assign(CicsAssignOutput),
    Length,
    ReturnTransId,
    ReturnTermId,
    Queue,
    NumItems,
    DocumentToken,
    DocumentSize,
    ElementName,
    ElementNameLength,
    ElementNamespace,
    ElementNamespaceLength,
    TypeName,
    TypeNameLength,
    TypeNamespace,
    TypeNamespaceLength,
}
