//! Typed CICS HIR identities and resolved statement records.

use super::{HirCicsOutputName, HirDataReference};
use std::collections::BTreeSet;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum HirCicsOperation {
    Abend,
    Address,
    AddressSet,
    Asktime,
    AsktimeEib,
    FormatTime,
    ConvertTime,
    BifDeedit,
    BifDigest,
    Freemain,
    Getmain,
    Cancel,
    Delay,
    Post,
    WriteOperator,
    ChangeTask,
    Deq,
    Enq,
    HandleAid,
    HandleAbend,
    HandleCondition,
    IgnoreCondition,
    InvokeApplication,
    Load,
    Release,
    Link,
    Xctl,
    Return,
    StartBrowse,
    ResetBrowse,
    ReadNext,
    ReadPrev,
    ReadTransientData,
    EndBrowse,
    Delete,
    Write,
    WriteTransientData,
    DeleteTransientData,
    DeleteTemporaryStorage,
    ReadTemporaryStorage,
    WriteTemporaryStorage,
    ReceiveMap,
    SendMap,
    SendText,
    Assign,
    PurgeMessage,
    PopHandle,
    PushHandle,
    Read,
    Rewrite,
    SetAssociationUserCorrData,
    SpoolClose,
    SpoolOpenInput,
    SpoolOpenOutput,
    SpoolRead,
    SpoolWrite,
    Syncpoint,
    Unlock,
    Suspend,
    WaitEvent,
    WaitExternal,
    WaitCics,
    Start,
    Retrieve,
    DocumentCreate,
    DocumentDelete,
    DocumentInsert,
    DocumentRetrieve,
    DocumentSet,
    TransformDataToJson,
    TransformDataToXml,
    TransformJsonToData,
    TransformXmlToData,
    WaitJournalName,
    WaitJournalNum,
    WriteJournalName,
    WriteJournalNum,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum HirCicsOperandName {
    Abcode,
    Label,
    Program,
    Commarea,
    TransId,
    TermId,
    ReturnTransId,
    ReturnTermId,
    File,
    Dataset,
    From,
    Ridfld,
    Token,
    Queue,
    Qname,
    SysId,
    Item,
    CommareaPointer,
    Map,
    Mapset,
    Resource,
    Length,
    MaxLifetime,
    Priority,
    UserCorrData,
    SetAddress,
    SetPointer,
    UsingAddress,
    UsingPointer,
    /// Canonical condition specifications for HANDLE or IGNORE.
    Conditions,
    /// Canonical terminal AID handler specifications.
    Aids,
    Abstime,
    DateString,
    Field,
    Record,
    RecordLength,
    DigestType,
    OperatorText,
    OperatorTextLength,
    OperatorRouteCodes,
    OperatorNumRoutes,
    OperatorConsName,
    OperatorAction,
    OperatorMaxLength,
    OperatorTimeout,
    DateSep,
    TimeSep,
    KeyLength,
    ReqId,
    Interval,
    StartTime,
    UserId,
    Hours,
    Minutes,
    Seconds,
    Milliseconds,
    DataLength,
    Flength,
    InitImage,
    DataPointer,
    DataArea,
    EventControlAddress,
    WaitName,
    EcbList,
    NumEvents,
    Purgeability,
    Application,
    Platform,
    ApplicationOperation,
    MajorVersion,
    MinorVersion,
    Channel,
    LoadSet,
    Entry,
    LoadLength,
    LoadFlength,
    DocumentToken,
    Text,
    Binary,
    FromDocument,
    Template,
    SymbolList,
    ListLength,
    Delimiter,
    HostCodePage,
    Bookmark,
    Symbol,
    AtBookmark,
    ToBookmark,
    MaximumLength,
    CharacterSet,
    SymbolValue,
    InContainer,
    OutContainer,
    Transformer,
    DataContainer,
    XmlContainer,
    XmlTransform,
    NsContainer,
    ElementName,
    ElementNameLength,
    ElementNamespace,
    ElementNamespaceLength,
    TypeName,
    TypeNameLength,
    TypeNamespace,
    TypeNamespaceLength,
    JournalName,
    JournalNum,
    JournalReqId,
    JournalTypeId,
    JournalFrom,
    JournalFlength,
    JournalPrefix,
    JournalPfxLeng,
    SpoolToken,
    SpoolUserId,
    SpoolClass,
    SpoolNode,
    SpoolRecordLength,
    SpoolOutDescr,
    SpoolMaxFlength,
    SpoolFrom,
    SpoolFlength,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum HirCicsValue {
    Literal(String),
    Data(HirDataReference),
    Integer(i64),
    LengthOf(HirDataReference),
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct HirCicsNamedOperand {
    pub name: HirCicsOperandName,
    pub value: HirCicsValue,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum HirCicsOption {
    DigestHex,
    DigestBinary,
    DigestBase64,
    OperatorImmediate,
    OperatorEventual,
    OperatorCritical,
    Cancel,
    NoDump,
    Reset,
    Update,
    Rollback,
    NoHandle,
    Task,
    Uow,
    NoSuspend,
    Erase,
    Cursor,
    DateSep,
    TimeSep,
    FreeKb,
    Gteq,
    Generic,
    Fmh,
    Protect,
    Wait,
    After,
    At,
    For,
    Until,
    NoCheck,
    MapOnly,
    DataOnly,
    Equal,
    Terminal,
    Purgeable,
    NotPurgeable,
    Next,
    RewriteTemporary,
    Auxiliary,
    Main,
    ExactMatch,
    Minimum,
    Hold,
    Unescaped,
    SpoolKeep,
    SpoolDelete,
    SpoolNoCc,
    SpoolAsa,
    SpoolMcc,
    SpoolPrint,
    SpoolPunch,
    SpoolLine,
    SpoolPage,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct HirCicsOutputBinding {
    pub name: HirCicsOutputName,
    pub target: HirDataReference,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum HirCicsConditionPolicy {
    Default,
    NoHandle,
    Respond {
        response: HirDataReference,
        response2: Option<HirDataReference>,
    },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct HirCicsStatement {
    pub operation: HirCicsOperation,
    pub operands: Vec<HirCicsNamedOperand>,
    pub options: BTreeSet<HirCicsOption>,
    pub outputs: Vec<HirCicsOutputBinding>,
    pub condition_policy: HirCicsConditionPolicy,
}
