use mainframe_env_ir::{CicsAssignOutput, CicsCertificateOutput, CicsTcpipOutput};

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum HirCicsOutputName {
    Abstime,
    Field,
    DigestResult,
    OperatorReply,
    OperatorReplyLength,
    Certificate(CicsCertificateOutput),
    Tcpip(CicsTcpipOutput),
    Commarea,
    Into,
    SetPointer,
    Ridfld,
    Token,
    Milliseconds,
    Mmddyy,
    Mmddyyyy,
    Resp,
    Resp2,
    Time,
    Yyddd,
    Yymmdd,
    Yyyymmdd,
    Assign(CicsAssignOutput),
    Length,
    ReturnTransId,
    ReturnTermId,
    Queue,
    NumItems,
    SpoolToken,
    SpoolToFlength,
    JournalReqId,
    DocumentToken,
    DocumentSize,
    ElementName,
    ElementNameLength,
    ElementNamespace,
    ElementNamespaceLength,
    TypeName,
    TypeNameLength,
    TypeNamespace,
    TypeNamespaceLength,
}
