// @generated by `python3 -B tools/generate_cics_descriptors.py`; do not edit.

pub(super) const CICS_LEGACY_SPI_COMPATIBILITY:
    CicsLegacySpiCompatibilityDescriptor = CicsLegacySpiCompatibilityDescriptor {
        official_row: "ibm-cics-ts-6x-2026-08-31:spi-commands-unique:0155",
        label_tokens: &["INQUIRE", "PROGRAM"],
        recognition_head: &["INQUIRE"],
        runtime_operation: "Inquire",
        required_value_options: &["PROGRAM"],
        optional_value_options: &["RESP", "RESP2"],
        optional_flag_options: &["NOHANDLE"],
        application_discriminator_options: &["ACTIVITYID", "CONTAINER", "EVENT", "PROCESS", "TIMER"],
        resp2_requires_resp: true,
    };
