// @generated by `python3 -B tools/generate_cics_descriptors.py`; do not edit.

pub(super) const CICS_LEGACY_COMPATIBILITY: &[CicsLegacyCompatibilityDescriptor] = &[
    CicsLegacyCompatibilityDescriptor {
        official_row: "ibm-cics-ts-6x-2026-08-31:spi-commands-unique:0155",
        label_tokens: &["INQUIRE", "PROGRAM"],
        recognition_head: &["INQUIRE"],
        runtime_operation: "Inquire",
        runtime_official_row: "ibm-cics-ts-6x-2026-08-31:spi-commands-unique:0155",
        required_value_options: &["PROGRAM"],
        optional_value_options: &["RESP", "RESP2"],
        optional_flag_options: &["NOHANDLE"],
        application_discriminator_options: &["ACTIVITYID", "CONTAINER", "EVENT", "PROCESS", "TIMER"],
        resp2_requires_resp: true,
        reject_unknown_options: true,
    },
    CicsLegacyCompatibilityDescriptor {
        official_row: "ibm-cics-ts-6x-2026-08-31:api-commands:0187",
        label_tokens: &["SEND"],
        recognition_head: &["SEND"],
        runtime_operation: "SendText",
        runtime_official_row: "ibm-cics-ts-6x-2026-08-31:api-commands:0192",
        required_value_options: &["FROM"],
        optional_value_options: &["LENGTH", "RESP", "RESP2"],
        optional_flag_options: &["ERASE", "NOHANDLE"],
        application_discriminator_options: &["CONTROL", "MAP", "PAGE", "PARTNSET", "TEXT"],
        resp2_requires_resp: true,
        reject_unknown_options: false,
    },
];
