import importlib.util
import json
from pathlib import Path
import tempfile
import unittest


TOOL = Path(__file__).resolve().parents[1] / "check_module_boundaries.py"
SPEC = importlib.util.spec_from_file_location("check_module_boundaries", TOOL)
module_boundaries = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(module_boundaries)


def source_lines(count: int, first: str = "// production") -> str:
    return "\n".join([first] + ["// production" for _ in range(count - 1)]) + "\n"


class ModuleBoundaryTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.inventory_path = self.root / "module-budgets.json"
        self.inventory = {
            "schema_version": module_boundaries.SCHEMA_VERSION,
            "default_max_production_lines": 1200,
            "source_roots": ["crates"],
            "test_only_path_components": ["tests", "benches"],
            "generated_path_component": "generated",
            "oversized_modules": [],
            "generated_exemptions": [],
            "facade_exemptions": [],
            "cics_family_layout": {
                "provider_root": "crates/providers/cics/src",
                "frozen_service": "crates/providers/cics/src/service.rs",
                "existing_modules": [
                    "crates/providers/cics/src/abi.rs",
                    "crates/providers/cics/src/lib.rs",
                    "crates/providers/cics/src/service.rs",
                ],
                "descriptor_directory": "crates/providers/cics/src/generated",
                "handler_directory": "crates/providers/cics/src/handlers",
                "handler_modules": ["crates/providers/cics/src/handlers/file.rs"],
            },
        }
        self.write("crates/providers/cics/src/abi.rs", "pub fn abi() {}\n")
        self.write(
            "crates/providers/cics/src/lib.rs",
            "//! CICS facade.\nmod abi;\nmod service;\npub use service::*;\n",
        )
        self.write("crates/providers/cics/src/service.rs", "pub fn serve() {}\n")
        self.write(
            "crates/providers/cics/src/generated/commands.rs",
            "// @generated by `fixture`; do not edit.\npub const COMMANDS: &[&str] = &[];\n",
        )
        self.write(
            "crates/providers/cics/src/handlers/file.rs",
            "pub fn handle_file() {}\n",
        )

    def tearDown(self):
        self.temporary.cleanup()

    def write(self, relative: str, source: str) -> None:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source)

    def save(self) -> None:
        self.inventory_path.write_text(json.dumps(self.inventory, indent=2) + "\n")

    def check(self):
        self.save()
        return module_boundaries.check(self.root, self.inventory_path)

    def test_counts_a_terminal_test_module_as_test_only(self):
        source = (
            "#[cfg(test)]\nfn early_test_helper() {}\n"
            "pub fn production() {}\n"
            "#[cfg(test)]\nmod tests {\n"
            + "    // test scenario\n" * 50
            + "}\n"
        )
        self.assertEqual(module_boundaries.production_line_count(source), 3)

    def test_production_after_a_test_module_cannot_evade_the_budget(self):
        source = (
            "pub fn before() {}\n"
            "#[cfg(test)]\nmod tests {\n"
            "    const BRACES: &str = \"{ not structure }\";\n"
            "}\n"
            "pub fn appended_production() {}\n"
        )
        self.assertEqual(module_boundaries.production_line_count(source), 6)

    def test_reviewed_production_and_generated_exemptions_are_exact(self):
        self.write("crates/example/src/large.rs", source_lines(1201))
        self.inventory["oversized_modules"].append(
            {
                "path": "crates/example/src/large.rs",
                "max_production_lines": 1201,
                "responsibility": "A reviewed legacy production responsibility.",
                "split_boundary": "Extract the stable command families.",
            }
        )
        self.write(
            "crates/example/src/generated/catalog.rs",
            source_lines(1201, "// @generated by `fixture`; do not edit."),
        )
        self.write("authority/catalog.json", "{}\n")
        self.inventory["generated_exemptions"].append(
            {
                "path": "crates/example/src/generated/catalog.rs",
                "max_generated_lines": 1201,
                "generator": "fixture generator",
                "authorities": ["authority/catalog.json"],
            }
        )
        summary = self.check()
        self.assertEqual(summary["oversized_modules"], 1)
        self.assertEqual(summary["generated_exemptions"], 1)

    def test_new_oversized_module_and_growth_both_fail_closed(self):
        self.write("crates/example/src/large.rs", source_lines(1201))
        with self.assertRaisesRegex(module_boundaries.ModuleBoundaryError, "hard limit"):
            self.check()
        self.inventory["oversized_modules"].append(
            {
                "path": "crates/example/src/large.rs",
                "max_production_lines": 1201,
                "responsibility": "A reviewed legacy production responsibility.",
                "split_boundary": "Extract the stable command families.",
            }
        )
        self.write("crates/example/src/large.rs", source_lines(1202))
        with self.assertRaisesRegex(module_boundaries.ModuleBoundaryError, "non-growing ceiling"):
            self.check()

    def test_test_only_files_do_not_consume_a_production_budget(self):
        self.write("crates/example/tests/large_scenario.rs", source_lines(3000))
        self.check()

    def test_generated_sources_require_provenance_even_below_the_limit(self):
        self.write("crates/example/src/generated/catalog.rs", "pub const ROW: u8 = 1;\n")
        with self.assertRaisesRegex(module_boundaries.ModuleBoundaryError, "generator-owned header"):
            self.check()

    def test_crate_roots_reject_implementation_and_ratchet_legacy_debt(self):
        self.write("crates/example/src/lib.rs", "pub struct State;\n")
        with self.assertRaisesRegex(module_boundaries.ModuleBoundaryError, "facade"):
            self.check()
        self.inventory["facade_exemptions"].append(
            {
                "path": "crates/example/src/lib.rs",
                "max_production_lines": 1,
                "responsibility": "A pre-existing root implementation.",
                "split_boundary": "Move the state into a focused module.",
            }
        )
        self.check()
        self.write("crates/example/src/lib.rs", "pub struct State;\npub struct Other;\n")
        with self.assertRaisesRegex(module_boundaries.ModuleBoundaryError, "non-growing ceiling"):
            self.check()

    def test_cics_requires_both_generated_descriptors_and_reviewed_handlers(self):
        (self.root / "crates/providers/cics/src/generated/commands.rs").unlink()
        with self.assertRaisesRegex(module_boundaries.ModuleBoundaryError, "descriptor layer is absent"):
            self.check()
        self.write(
            "crates/providers/cics/src/generated/commands.rs",
            "// @generated by `fixture`; do not edit.\n",
        )
        (self.root / "crates/providers/cics/src/handlers/file.rs").unlink()
        with self.assertRaisesRegex(module_boundaries.ModuleBoundaryError, "family layer is absent"):
            self.check()
        self.write(
            "crates/providers/cics/src/handlers/file.rs",
            "// @generated by `fixture`; do not edit.\n",
        )
        with self.assertRaisesRegex(module_boundaries.ModuleBoundaryError, "reviewed source"):
            self.check()
        self.write("crates/providers/cics/src/handlers/file.rs", "pub fn handle_file() {}\n")
        self.write("crates/providers/cics/src/handlers/extra.rs", "pub fn extra() {}\n")
        with self.assertRaisesRegex(module_boundaries.ModuleBoundaryError, "frozen inventory"):
            self.check()

    def test_refresh_updates_only_rows_with_human_rationale(self):
        self.write("crates/example/src/large.rs", source_lines(1201))
        self.inventory["oversized_modules"].append(
            {
                "path": "crates/example/src/large.rs",
                "max_production_lines": 1300,
                "responsibility": "A reviewed legacy production responsibility.",
                "split_boundary": "Extract the stable command families.",
            }
        )
        self.save()
        module_boundaries.refresh(self.root, self.inventory_path)
        refreshed = json.loads(self.inventory_path.read_text())
        self.assertEqual(refreshed["oversized_modules"][0]["max_production_lines"], 1201)


if __name__ == "__main__":
    unittest.main()
