[package]
name = "mainframe-env-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mainframe-env-execution-api.workspace = true
mainframe-env-host-api.workspace = true
sha2.workspace = true

[dev-dependencies]
serde_json.workspace = true
