//! Finite shape checks, not an object catalog, MQINQ implementation or SAF grant.
//!
//! Original row0016/position16 q101840_: selector order/count (19–48), integer
//! output and unchanged excess slots (706–715). Supplements q091590_451–453
//! bind MQIA_Q_TYPE. Inquiry attribute q092480_11–13 and q103490_19–28 plus
//! supplements q102970_25–28 bind the normal-local scalar. All source facts
//! join the existing catalog's separate reviewed projection, not a new domain.

use super::*;
use crate::mq_status::MqCompletion;

mod generated;
use generated::*;

impl MqMqiSelector {
    /// Checks a signed numeric selector against the finite reviewed identity.
    /// Unknown, negative and out-of-MQLONG values refuse; pending variants are
    /// never promoted by equality. This does not authorize use on an object.
    pub fn reviewed_local_type(value: i64) -> Result<Self, MqMqiProblem> {
        if i32::try_from(value) == Ok(MQIA_Q_TYPE) {
            Ok(Self::ReviewedQueueType)
        } else {
            Err(MqMqiProblem::InquiryProfile)
        }
    }

    /// Returns only an explicitly reviewed identity, never a pending number.
    #[must_use]
    pub const fn reviewed_number(self) -> Option<i32> {
        match self {
            Self::ReviewedQueueType => Some(MQIA_Q_TYPE),
            Self::PendingInteger(_) | Self::PendingCharacter(_) => None,
        }
    }
}

/// Checked adequate-integer-buffer shape for an actual normal-local queue.
///
/// Construction checks representation only. Dispatch must independently prove
/// the live issued connection/object, normal-local catalog origin, INQUIRE open
/// access, current frame, original core occurrence, SAF and physical fencing.
/// No local-type output is generated by this type. Only later actual catalog
/// observations may be checked. Characters, other selectors/kinds and warnings
/// remain pending. This wrapper is non-Serde and mints no handle authority.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MqMqiLocalTypeInquiry {
    inquiry: MqMqiInquiry,
}

impl MqMqiLocalTypeInquiry {
    /// Checks all signed counts/selectors before allocating a bounded request.
    /// Integer capacity counts slots, not bytes; character capacity must be zero.
    /// Adequate capacity is at most the smaller product/selected selector limit.
    /// Zero selectors are valid and do not bypass any live dispatch obligation.
    pub fn new(
        connection: MqHconn,
        object: MqHobj,
        selectors: &[i64],
        integer_capacity: i64,
        character_capacity: i64,
        limits: MqMqiLimits,
    ) -> Result<Self, MqMqiProblem> {
        limits.validate()?;
        let ceiling = limits.selectors.min(MAX_INTEGER_SLOTS);
        if selectors.len() > ceiling {
            return Err(MqMqiProblem::SelectorCount);
        }
        if integer_capacity < selectors.len() as i64
            || integer_capacity > ceiling as i64
            || character_capacity != 0
        {
            return Err(MqMqiProblem::AttributeCount);
        }
        for &selector in selectors {
            MqMqiSelector::reviewed_local_type(selector)?;
        }
        if !matches!(connection, MqHconn::Issued(_)) {
            return Err(MqMqiProblem::Connection);
        }
        let mut reviewed = Vec::new();
        reviewed
            .try_reserve_exact(selectors.len())
            .map_err(|_| MqMqiProblem::Allocation)?;
        reviewed.resize(selectors.len(), MqMqiSelector::ReviewedQueueType);
        Self::from_inquiry(
            MqMqiInquiry {
                connection,
                object,
                selectors: reviewed,
                integer_capacity: integer_capacity as usize,
                character_capacity: 0,
            },
            limits,
        )
    }

    /// Checks a directly assembled inquiry without changing its order or handles.
    /// PendingInteger(20) remains pending and is refused by this finite profile.
    pub fn from_inquiry(inquiry: MqMqiInquiry, limits: MqMqiLimits) -> Result<Self, MqMqiProblem> {
        validate(&inquiry, limits)?;
        Ok(Self { inquiry })
    }

    /// Borrows the exact request; no mutable profile or permission is exposed.
    #[must_use]
    pub fn inquiry(&self) -> &MqMqiInquiry {
        &self.inquiry
    }

    /// Consumes into the existing Inquire payload. Empty selectors retain their
    /// historical identity; use this wrapper's result check for that empty shape.
    /// No selected/provider admission is activated by conversion.
    #[must_use]
    pub fn into_inquiry(self) -> MqMqiInquiry {
        self.inquiry
    }

    /// Checks a complete actual observation against this exact request shape.
    /// Only OK/NONE with one observed LOCAL scalar per occurrence is admitted.
    /// Returned slice owns the requested prefix only: excess caller integer
    /// slots and all character storage must be untouched by a future writer.
    /// Unknown/pending/failure/warning/status-only results cannot establish it.
    pub fn validate_result<'a>(
        &self,
        result: &'a MqMqiResult,
        limits: MqMqiLimits,
    ) -> Result<&'a [i32], MqMqiProblem> {
        validate(&self.inquiry, limits)?;
        result.validate(limits)?;
        complete(&self.inquiry, result)
    }

    /// Independent frozen source projection identity, never execution evidence.
    #[must_use]
    pub const fn projection_sha256() -> &'static str {
        PROJECTION_SHA256
    }
}

pub(super) fn is_reviewed(request: &MqMqiInquiry) -> bool {
    request
        .selectors
        .contains(&MqMqiSelector::ReviewedQueueType)
}

pub(super) fn validate(request: &MqMqiInquiry, limits: MqMqiLimits) -> Result<(), MqMqiProblem> {
    limits.validate()?;
    let ceiling = limits.selectors.min(MAX_INTEGER_SLOTS);
    if request.selectors.len() > ceiling {
        return Err(MqMqiProblem::SelectorCount);
    }
    if request.integer_capacity < request.selectors.len()
        || request.integer_capacity > ceiling
        || request.character_capacity != 0
    {
        return Err(MqMqiProblem::AttributeCount);
    }
    if !matches!(request.connection, MqHconn::Issued(_)) {
        return Err(MqMqiProblem::Connection);
    }
    if request
        .selectors
        .iter()
        .any(|s| *s != MqMqiSelector::ReviewedQueueType)
    {
        return Err(MqMqiProblem::InquiryProfile);
    }
    Ok(())
}

pub(super) fn complete<'a>(
    request: &MqMqiInquiry,
    result: &'a MqMqiResult,
) -> Result<&'a [i32], MqMqiProblem> {
    if result.call != MqMqiCall::Inquire {
        return Err(MqMqiProblem::OutputCallMismatch);
    }
    let output = match &result.outcome {
        MqMqiOutcome::Completed {
            status: MqMqiStatus::OkNone,
            output,
        } => output,
        MqMqiOutcome::ReviewedOutput { status, output }
            if status.call() == MqMqiCall::Inquire
                && status.completion() == MqCompletion::Ok
                && status.reason_symbol() == "MQRC_NONE" =>
        {
            output
        }
        _ => return Err(MqMqiProblem::StatusCallMismatch),
    };
    let MqMqiOutput::Attributes {
        integers,
        characters,
    } = output
    else {
        return Err(MqMqiProblem::OutputCallMismatch);
    };
    if integers.len() != request.selectors.len() || !characters.is_empty() {
        return Err(MqMqiProblem::AttributeCount);
    }
    if integers.iter().any(|&value| value != MQQT_LOCAL) {
        return Err(MqMqiProblem::InquiryProfile);
    }
    Ok(integers)
}
