//! Bounded IMS PCB mask layout and execution-context contracts.

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
/// Execution-context identity used by applicability descriptors; runtime admission remains separate.
pub enum ImsExecutionContext {
    /// Combined database and transaction-manager context identity.
    DbDc,
    /// Database-control context identity.
    Dbctl,
    /// Transaction-manager-control context identity.
    Dcctl,
    /// Standalone database-batch context identity.
    DbBatch,
    /// Transaction-manager batch context identity.
    TmBatch,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
/// Closed PCB mask category used by layout and status validation.
pub enum ImsPcbKind {
    /// Full-function database PCB mask category.
    Database,
    /// GSAM database PCB mask category.
    Gsam,
    /// Message I/O PCB mask category.
    Io,
    /// Alternate PCB mask category.
    Alternate,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
/// Field identity in generated mask descriptors; width and contextual meaning come from the descriptor.
pub enum ImsPcbField {
    /// Database identity slot in the mask.
    DatabaseName,
    /// Segment hierarchy-level slot.
    SegmentLevelNumber,
    /// Two-byte call-status slot.
    StatusCode,
    /// PCB processing-option slot.
    ProcessingOptions,
    /// Reserved slot with no application-owned interpretation.
    ReservedForIms,
    /// Segment identity slot.
    SegmentName,
    /// Length slot associated with key feedback.
    KeyFeedbackLength,
    /// Sensitive-segment count slot.
    SensitiveSegmentCount,
    /// Variable key-feedback byte area.
    KeyFeedbackArea,
    /// Combined key-feedback and undefined-length slot identity.
    KeyFeedbackAndUndefinedLength,
    /// GSAM record-search-argument slot; no host logical-token encoding is implied.
    RecordSearchArgument,
    /// Undefined-record length slot.
    UndefinedRecordLength,
    /// Logical-terminal identity slot.
    LogicalTerminalName,
    /// Local-date slot; this enum does not encode calendar bytes.
    LocalDate,
    /// Local-time slot; this enum does not encode clock bytes.
    LocalTime,
    /// Input-message sequence-number slot.
    InputMessageSequenceNumber,
    /// Message-output descriptor identity slot.
    MessageOutputDescriptorName,
    /// User identity slot.
    UserId,
    /// Group identity slot.
    GroupName,
    /// Extended-date slot identity.
    ExtendedDate,
    /// Extended-time slot identity.
    ExtendedTime,
    /// UTC-offset slot identity; no numeric unit conversion occurs here.
    UtcOffset,
    /// User-identity indicator slot.
    UserIdIndicator,
    /// Reserved extension slot with no application meaning assigned here.
    ReservedExtension,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
/// Generated byte-width rule resolved by the bounded layout constructor.
pub enum ImsPcbFieldWidth {
    /// Exact width in bytes independent of the supplied variable length.
    Fixed(usize),
    /// Use the caller-supplied key-feedback byte length.
    VariableKeyFeedback,
    /// Accept only one of the listed byte lengths for the variable area.
    OneOf(&'static [usize]),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
/// Whether a descriptor assigns application meaning to a field in this mask.
pub enum ImsPcbSemanticValue {
    /// The mask descriptor assigns application-visible meaning.
    Application,
    /// The mask reserves this field for subsystem use.
    Reserved,
    /// The field has no assigned meaning for this mask category.
    Unused,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
/// Generated field identity, byte-width rule and context applicability.
pub struct ImsPcbFieldDescriptor {
    /// Field identity occupying this ordered mask slot.
    pub field: ImsPcbField,
    /// Byte-width rule for this slot.
    pub width: ImsPcbFieldWidth,
    /// Application, reserved or unused interpretation in the descriptor.
    pub semantic_value: ImsPcbSemanticValue,
    /// Contexts in which the field is meaningful according to the registry.
    pub applicable_contexts: &'static [ImsExecutionContext],
}

impl ImsPcbFieldDescriptor {
    #[must_use]
    /// Return whether the registry lists this context for the field.
    pub fn applies_in(&self, context: ImsExecutionContext) -> bool {
        self.applicable_contexts.contains(&context)
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
/// Pinned-source mask inventory, without raw-language ABI execution or coverage authority.
pub struct ImsPcbMaskDescriptor {
    /// PCB category described by this mask.
    pub kind: ImsPcbKind,
    /// Pinned topic locator from the committed mask rules.
    pub source_topic: &'static str,
    /// Expected source-body SHA-256 identity from those rules.
    pub source_sha256: &'static str,
    /// Execution contexts allowed by the mask descriptor.
    pub allowed_contexts: &'static [ImsExecutionContext],
    /// Fields in exact descriptor order used to compute byte offsets.
    pub fields: &'static [ImsPcbFieldDescriptor],
}

impl ImsPcbMaskDescriptor {
    #[must_use]
    /// Return whether the mask descriptor permits the requested context.
    pub fn allowed_in(&self, context: ImsExecutionContext) -> bool {
        self.allowed_contexts.contains(&context)
    }
}

include!("generated/ims_pcb_masks.rs");

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
/// Local ceiling on the resolved mask byte length.
pub struct ImsPcbLimits {
    /// Maximum total layout size in bytes; default 64 KiB, and zero rejects construction.
    pub max_mask_bytes: usize,
}

impl Default for ImsPcbLimits {
    fn default() -> Self {
        Self {
            max_mask_bytes: 64 * 1024,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
/// Explicit rejection while resolving a bounded PCB mask layout.
pub enum ImsPcbProblem {
    /// The generated mask does not admit the requested execution context.
    ForbiddenExecutionContext,
    /// The supplied variable byte length conflicts with the mask's width rule.
    InvalidVariableAreaLength,
    /// The total size overflows or exceeds a nonzero byte ceiling.
    ResourceExhausted,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
/// Validated descriptor plus resolved byte lengths; it does not serialize or interpret mask contents.
pub struct ImsPcbLayout {
    mask: &'static ImsPcbMaskDescriptor,
    variable_field_bytes: usize,
    total_bytes: usize,
}

impl ImsPcbLayout {
    #[must_use]
    /// Return the immutable generated descriptor used for this layout.
    pub const fn mask(self) -> &'static ImsPcbMaskDescriptor {
        self.mask
    }

    #[must_use]
    /// Return the checked total mask size in bytes.
    pub const fn total_bytes(self) -> usize {
        self.total_bytes
    }

    #[must_use]
    /// Return the resolved byte width by zero-based field index, or None out of range.
    pub fn field_width(self, index: usize) -> Option<usize> {
        self.mask
            .fields
            .get(index)
            .map(|field| resolved_width(field.width, self.variable_field_bytes))
    }

    #[must_use]
    /// Return the zero-based byte offset by field index, or None for an invalid index/overflow.
    pub fn field_offset(self, index: usize) -> Option<usize> {
        if index >= self.mask.fields.len() {
            return None;
        }
        self.mask.fields[..index]
            .iter()
            .try_fold(0_usize, |offset, field| {
                offset.checked_add(resolved_width(field.width, self.variable_field_bytes))
            })
    }

    #[must_use]
    /// Return the status field's zero-based byte offset, or None when unavailable.
    pub fn status_offset(self) -> Option<usize> {
        self.mask
            .fields
            .iter()
            .position(|field| field.field == ImsPcbField::StatusCode)
            .and_then(|index| self.field_offset(index))
    }
}

#[must_use]
/// Return the complete immutable generated mask inventory.
pub fn ims_pcb_masks() -> &'static [ImsPcbMaskDescriptor] {
    IMS_PCB_MASKS
}

#[must_use]
/// Return the generated descriptor for a closed PCB kind; the registry must be exhaustive.
pub fn ims_pcb_mask(kind: ImsPcbKind) -> &'static ImsPcbMaskDescriptor {
    IMS_PCB_MASKS
        .iter()
        .find(|mask| mask.kind == kind)
        .expect("generated IMS PCB mask registry must cover every closed kind")
}

/// Resolve mask size and offsets, rejecting context, variable-length or byte-limit violations.
pub fn ims_pcb_layout(
    kind: ImsPcbKind,
    context: ImsExecutionContext,
    variable_field_bytes: usize,
    limits: ImsPcbLimits,
) -> Result<ImsPcbLayout, ImsPcbProblem> {
    let mask = ims_pcb_mask(kind);
    if !mask.allowed_in(context) {
        return Err(ImsPcbProblem::ForbiddenExecutionContext);
    }
    if limits.max_mask_bytes == 0 {
        return Err(ImsPcbProblem::ResourceExhausted);
    }

    let mut variable_fields = 0_usize;
    let mut total_bytes = 0_usize;
    for field in mask.fields {
        let width = match field.width {
            ImsPcbFieldWidth::Fixed(width) => width,
            ImsPcbFieldWidth::VariableKeyFeedback => {
                variable_fields += 1;
                variable_field_bytes
            }
            ImsPcbFieldWidth::OneOf(widths) => {
                variable_fields += 1;
                if !widths.contains(&variable_field_bytes) {
                    return Err(ImsPcbProblem::InvalidVariableAreaLength);
                }
                variable_field_bytes
            }
        };
        total_bytes = total_bytes
            .checked_add(width)
            .ok_or(ImsPcbProblem::ResourceExhausted)?;
    }
    if variable_fields == 0 && variable_field_bytes != 0 {
        return Err(ImsPcbProblem::InvalidVariableAreaLength);
    }
    if variable_fields > 1 || total_bytes > limits.max_mask_bytes {
        return Err(ImsPcbProblem::ResourceExhausted);
    }
    Ok(ImsPcbLayout {
        mask,
        variable_field_bytes,
        total_bytes,
    })
}

fn resolved_width(width: ImsPcbFieldWidth, variable_field_bytes: usize) -> usize {
    match width {
        ImsPcbFieldWidth::Fixed(width) => width,
        ImsPcbFieldWidth::VariableKeyFeedback | ImsPcbFieldWidth::OneOf(_) => variable_field_bytes,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pcb_masks_preserve_exact_field_order_widths_and_offsets() {
        let database = ims_pcb_layout(
            ImsPcbKind::Database,
            ImsExecutionContext::DbDc,
            13,
            ImsPcbLimits::default(),
        )
        .unwrap();
        assert_eq!(database.total_bytes(), 49);
        assert_eq!(database.status_offset(), Some(10));
        assert_eq!(
            database
                .mask()
                .fields
                .iter()
                .map(|field| field.field)
                .collect::<Vec<_>>(),
            [
                ImsPcbField::DatabaseName,
                ImsPcbField::SegmentLevelNumber,
                ImsPcbField::StatusCode,
                ImsPcbField::ProcessingOptions,
                ImsPcbField::ReservedForIms,
                ImsPcbField::SegmentName,
                ImsPcbField::KeyFeedbackLength,
                ImsPcbField::SensitiveSegmentCount,
                ImsPcbField::KeyFeedbackArea,
            ]
        );
        assert_eq!(
            (0..database.mask().fields.len())
                .map(|index| database.field_width(index).unwrap())
                .collect::<Vec<_>>(),
            [8, 2, 2, 4, 4, 8, 4, 4, 13]
        );

        let gsam_basic = ims_pcb_layout(
            ImsPcbKind::Gsam,
            ImsExecutionContext::TmBatch,
            8,
            ImsPcbLimits::default(),
        )
        .unwrap();
        let gsam_large = ims_pcb_layout(
            ImsPcbKind::Gsam,
            ImsExecutionContext::DbBatch,
            12,
            ImsPcbLimits::default(),
        )
        .unwrap();
        assert_eq!(gsam_basic.total_bytes(), 48);
        assert_eq!(gsam_large.total_bytes(), 52);
        assert_eq!(gsam_basic.status_offset(), Some(10));
        assert_eq!(
            gsam_basic
                .mask()
                .fields
                .iter()
                .filter(|field| field.semantic_value == ImsPcbSemanticValue::Unused)
                .map(|field| field.field)
                .collect::<Vec<_>>(),
            [
                ImsPcbField::SegmentLevelNumber,
                ImsPcbField::SegmentName,
                ImsPcbField::SensitiveSegmentCount,
            ]
        );

        let io = ims_pcb_layout(
            ImsPcbKind::Io,
            ImsExecutionContext::Dbctl,
            0,
            ImsPcbLimits::default(),
        )
        .unwrap();
        let alternate = ims_pcb_layout(
            ImsPcbKind::Alternate,
            ImsExecutionContext::Dcctl,
            0,
            ImsPcbLimits::default(),
        )
        .unwrap();
        assert_eq!(io.total_bytes(), 64);
        assert_eq!(alternate.total_bytes(), 12);
        assert_eq!(io.status_offset(), Some(10));
        assert_eq!(alternate.status_offset(), Some(10));
        assert_eq!(
            (0..io.mask().fields.len())
                .map(|index| io.field_width(index).unwrap())
                .collect::<Vec<_>>(),
            [8, 2, 2, 4, 4, 4, 8, 8, 8, 4, 6, 2, 1, 3]
        );
    }

    #[test]
    fn execution_context_and_field_applicability_are_fail_closed() {
        for context in [
            ImsExecutionContext::DbDc,
            ImsExecutionContext::Dbctl,
            ImsExecutionContext::DbBatch,
        ] {
            assert!(
                ims_pcb_layout(ImsPcbKind::Database, context, 0, ImsPcbLimits::default()).is_ok()
            );
        }
        for context in [ImsExecutionContext::Dcctl, ImsExecutionContext::TmBatch] {
            assert_eq!(
                ims_pcb_layout(ImsPcbKind::Database, context, 0, ImsPcbLimits::default()),
                Err(ImsPcbProblem::ForbiddenExecutionContext)
            );
        }
        for context in [
            ImsExecutionContext::Dbctl,
            ImsExecutionContext::DbBatch,
            ImsExecutionContext::TmBatch,
        ] {
            assert_eq!(
                ims_pcb_layout(ImsPcbKind::Alternate, context, 0, ImsPcbLimits::default()),
                Err(ImsPcbProblem::ForbiddenExecutionContext)
            );
        }

        let io = ims_pcb_mask(ImsPcbKind::Io);
        let terminal = &io.fields[0];
        let status = &io.fields[2];
        assert!(terminal.applies_in(ImsExecutionContext::DbDc));
        assert!(terminal.applies_in(ImsExecutionContext::Dcctl));
        assert!(!terminal.applies_in(ImsExecutionContext::Dbctl));
        assert!(status.applies_in(ImsExecutionContext::Dbctl));
        assert!(status.applies_in(ImsExecutionContext::DbBatch));
        assert!(status.applies_in(ImsExecutionContext::TmBatch));
    }

    #[test]
    fn mask_limits_and_variable_widths_are_enforced() {
        assert_eq!(
            ims_pcb_layout(
                ImsPcbKind::Database,
                ImsExecutionContext::DbDc,
                29,
                ImsPcbLimits { max_mask_bytes: 64 },
            ),
            Err(ImsPcbProblem::ResourceExhausted)
        );
        assert_eq!(
            ims_pcb_layout(
                ImsPcbKind::Gsam,
                ImsExecutionContext::DbDc,
                9,
                ImsPcbLimits::default(),
            ),
            Err(ImsPcbProblem::InvalidVariableAreaLength)
        );
        assert_eq!(
            ims_pcb_layout(
                ImsPcbKind::Io,
                ImsExecutionContext::DbDc,
                1,
                ImsPcbLimits::default(),
            ),
            Err(ImsPcbProblem::InvalidVariableAreaLength)
        );
    }
}
