use super::super::{HirCicsOperation, HirCicsOption, Resolution, ResolutionFailure};
use mainframe_env_ir::CicsApplicationRegistryDescriptor;

pub(super) fn resolve(
    descriptor: &CicsApplicationRegistryDescriptor,
) -> Resolution<HirCicsOperation> {
    Ok(match descriptor.label_tokens {
        ["ABEND"] => HirCicsOperation::Abend,
        ["ADDRESS", "SET"] => HirCicsOperation::AddressSet,
        ["ADDRESS"] => HirCicsOperation::Address,
        ["ASKTIME", "ABSTIME"] => HirCicsOperation::Asktime,
        ["ASKTIME"] => HirCicsOperation::AsktimeEib,
        ["FORMATTIME"] => HirCicsOperation::FormatTime,
        ["FREEMAIN"] => HirCicsOperation::Freemain,
        ["GETMAIN"] => HirCicsOperation::Getmain,
        ["CHANGE", "TASK"] => HirCicsOperation::ChangeTask,
        ["DEQ"] => HirCicsOperation::Deq,
        ["ENQ"] => HirCicsOperation::Enq,
        ["HANDLE", "ABEND"] => HirCicsOperation::HandleAbend,
        ["HANDLE", "AID"] => HirCicsOperation::HandleAid,
        ["HANDLE", "CONDITION"] => HirCicsOperation::HandleCondition,
        ["IGNORE", "CONDITION"] => HirCicsOperation::IgnoreCondition,
        ["INVOKE", "APPLICATION"] => HirCicsOperation::InvokeApplication,
        ["LOAD"] => HirCicsOperation::Load,
        ["RELEASE"] => HirCicsOperation::Release,
        ["LINK"] => HirCicsOperation::Link,
        ["XCTL"] => HirCicsOperation::Xctl,
        ["RETURN"] => HirCicsOperation::Return,
        ["STARTBR"] => HirCicsOperation::StartBrowse,
        ["READNEXT"] => HirCicsOperation::ReadNext,
        ["READPREV"] => HirCicsOperation::ReadPrev,
        ["READQ", "TD"] => HirCicsOperation::ReadTransientData,
        ["ENDBR"] => HirCicsOperation::EndBrowse,
        ["DELETE"] => HirCicsOperation::Delete,
        ["WRITE", "FILE"] => HirCicsOperation::Write,
        ["WRITEQ", "TD"] => HirCicsOperation::WriteTransientData,
        ["DELETEQ", "TD"] => HirCicsOperation::DeleteTransientData,
        ["DELETEQ", "TS"] => HirCicsOperation::DeleteTemporaryStorage,
        ["READQ", "TS"] => HirCicsOperation::ReadTemporaryStorage,
        ["WRITEQ", "TS"] => HirCicsOperation::WriteTemporaryStorage,
        ["RECEIVE", "MAP"] => HirCicsOperation::ReceiveMap,
        ["SEND", "MAP"] => HirCicsOperation::SendMap,
        ["SEND", "TEXT"] => HirCicsOperation::SendText,
        ["ASSIGN"] => HirCicsOperation::Assign,
        ["CANCEL"] => HirCicsOperation::Cancel,
        ["DELAY"] => HirCicsOperation::Delay,
        ["PURGE", "MESSAGE"] => HirCicsOperation::PurgeMessage,
        ["POP", "HANDLE"] => HirCicsOperation::PopHandle,
        ["PUSH", "HANDLE"] => HirCicsOperation::PushHandle,
        ["READ"] => HirCicsOperation::Read,
        ["REWRITE"] => HirCicsOperation::Rewrite,
        ["SET", "ASSOCIATION", "USERCORRDATA"] => HirCicsOperation::SetAssociationUserCorrData,
        ["SYNCPOINT"] => HirCicsOperation::Syncpoint,
        ["SUSPEND"] => HirCicsOperation::Suspend,
        ["WAIT", "EVENT"] => HirCicsOperation::WaitEvent,
        ["WAIT", "EXTERNAL"] => HirCicsOperation::WaitExternal,
        ["START"] => HirCicsOperation::Start,
        ["RETRIEVE"] => HirCicsOperation::Retrieve,
        ["DOCUMENT", "CREATE"] => HirCicsOperation::DocumentCreate,
        ["DOCUMENT", "DELETE"] => HirCicsOperation::DocumentDelete,
        ["DOCUMENT", "INSERT"] => HirCicsOperation::DocumentInsert,
        ["DOCUMENT", "RETRIEVE"] => HirCicsOperation::DocumentRetrieve,
        ["DOCUMENT", "SET"] => HirCicsOperation::DocumentSet,
        ["TRANSFORM", "DATATOJSON"] => HirCicsOperation::TransformDataToJson,
        ["TRANSFORM", "DATATOXML"] => HirCicsOperation::TransformDataToXml,
        ["TRANSFORM", "JSONTODATA"] => HirCicsOperation::TransformJsonToData,
        ["TRANSFORM", "XMLTODATA"] => HirCicsOperation::TransformXmlToData,
        ["WAIT", "JOURNALNAME"] => HirCicsOperation::WaitJournalName,
        ["WAIT", "JOURNALNUM"] => HirCicsOperation::WaitJournalNum,
        _ => return Err(ResolutionFailure::Unsupported),
    })
}

pub(super) fn resolve_option(option: &str) -> HirCicsOption {
    match option {
        "CANCEL" => HirCicsOption::Cancel,
        "NODUMP" => HirCicsOption::NoDump,
        "RESET" => HirCicsOption::Reset,
        "UPDATE" => HirCicsOption::Update,
        "ROLLBACK" => HirCicsOption::Rollback,
        "NOHANDLE" => HirCicsOption::NoHandle,
        "TASK" => HirCicsOption::Task,
        "UOW" => HirCicsOption::Uow,
        "NOSUSPEND" => HirCicsOption::NoSuspend,
        "ERASE" => HirCicsOption::Erase,
        "CURSOR" => HirCicsOption::Cursor,
        "DATESEP" => HirCicsOption::DateSep,
        "TIMESEP" => HirCicsOption::TimeSep,
        "FREEKB" => HirCicsOption::FreeKb,
        "GTEQ" => HirCicsOption::Gteq,
        "GENERIC" => HirCicsOption::Generic,
        "EQUAL" => HirCicsOption::Equal,
        "TERMINAL" => HirCicsOption::Terminal,
        "FMH" => HirCicsOption::Fmh,
        "PROTECT" => HirCicsOption::Protect,
        "WAIT" => HirCicsOption::Wait,
        "AFTER" => HirCicsOption::After,
        "AT" => HirCicsOption::At,
        "FOR" => HirCicsOption::For,
        "UNTIL" => HirCicsOption::Until,
        "NOCHECK" => HirCicsOption::NoCheck,
        "MAPONLY" => HirCicsOption::MapOnly,
        "DATAONLY" => HirCicsOption::DataOnly,
        "UNESCAPED" => HirCicsOption::Unescaped,
        "NEXT" => HirCicsOption::Next,
        "REWRITE" => HirCicsOption::RewriteTemporary,
        "AUXILIARY" => HirCicsOption::Auxiliary,
        "MAIN" => HirCicsOption::Main,
        "PURGEABLE" => HirCicsOption::Purgeable,
        "NOTPURGEABLE" => HirCicsOption::NotPurgeable,
        "EXACTMATCH" => HirCicsOption::ExactMatch,
        "MINIMUM" => HirCicsOption::Minimum,
        "HOLD" => HirCicsOption::Hold,
        _ => unreachable!("allowed CICS option"),
    }
}
