use super::super::{HirCicsOperation, HirCicsOption, Resolution, ResolutionFailure};
use mainframe_env_ir::{CICS_APPLICATION_CONDITION_NAMES, CicsApplicationRegistryDescriptor};

pub(super) fn is_condition_name(name: &str) -> bool {
    CICS_APPLICATION_CONDITION_NAMES
        .binary_search(&name)
        .is_ok()
}

pub(super) fn command_label(descriptor: &CicsApplicationRegistryDescriptor) -> String {
    descriptor.label_tokens.join(" ")
}

pub(super) fn resolve(
    descriptor: &CicsApplicationRegistryDescriptor,
) -> Resolution<HirCicsOperation> {
    Ok(match descriptor.label_tokens {
        ["ENDBROWSE", "EVENT"] => HirCicsOperation::BtsEndBrowseEvent,
        ["GETNEXT", "EVENT"] => HirCicsOperation::BtsGetNextEvent,
        ["INQUIRE", "EVENT"] => HirCicsOperation::BtsInquireEvent,
        ["STARTBROWSE", "EVENT"] => HirCicsOperation::BtsStartBrowseEvent,
        ["ENDBROWSE", "TIMER"] => HirCicsOperation::BtsEndBrowseTimer,
        ["INQUIRE", "TIMER"] => HirCicsOperation::BtsInquireTimer,
        ["STARTBROWSE", "TIMER"] => HirCicsOperation::BtsStartBrowseTimer,
        ["STARTBROWSE", "ACTIVITY"] => HirCicsOperation::BtsStartBrowseActivity,
        ["GETNEXT", "ACTIVITY"] => HirCicsOperation::BtsGetNextActivity,
        ["ENDBROWSE", "ACTIVITY"] => HirCicsOperation::BtsEndBrowseActivity,
        ["INQUIRE", "ACTIVITYID"] => HirCicsOperation::BtsInquireActivity,
        ["STARTBROWSE", "PROCESS"] => HirCicsOperation::BtsStartBrowseProcess,
        ["GETNEXT", "PROCESS"] => HirCicsOperation::BtsGetNextProcess,
        ["ENDBROWSE", "PROCESS"] => HirCicsOperation::BtsEndBrowseProcess,
        ["INQUIRE", "PROCESS"] => HirCicsOperation::BtsInquireProcess,
        ["ACQUIRE", "ACTIVITYID"] => HirCicsOperation::AcquireActivityId,
        ["ACQUIRE", "PROCESS"] => HirCicsOperation::AcquireProcess,
        ["CANCEL", "ACQACTIVITY"] => HirCicsOperation::CancelAcqActivity,
        ["CANCEL", "ACQPROCESS"] => HirCicsOperation::CancelAcqProcess,
        ["CANCEL", "ACTIVITY"] => HirCicsOperation::CancelActivity,
        ["CHECK", "ACQACTIVITY"] => HirCicsOperation::CheckAcqActivity,
        ["CHECK", "ACQPROCESS"] => HirCicsOperation::CheckAcqProcess,
        ["CHECK", "ACTIVITY"] => HirCicsOperation::CheckActivity,
        ["DEFINE", "ACTIVITY"] => HirCicsOperation::DefineActivity,
        ["DEFINE", "PROCESS"] => HirCicsOperation::DefineProcess,
        ["DELETE", "ACTIVITY"] => HirCicsOperation::DeleteActivity,
        ["RESET", "ACQPROCESS"] => HirCicsOperation::ResetAcqProcess,
        ["RESET", "ACTIVITY"] => HirCicsOperation::ResetActivity,
        ["RESUME", "ACQACTIVITY"] => HirCicsOperation::ResumeAcqActivity,
        ["RESUME", "ACQPROCESS"] => HirCicsOperation::ResumeAcqProcess,
        ["RESUME", "ACTIVITY"] => HirCicsOperation::ResumeActivity,
        ["RUN", "ACQACTIVITY"] => HirCicsOperation::RunAcqActivity,
        ["RUN", "ACQPROCESS"] => HirCicsOperation::RunAcqProcess,
        ["RUN", "ACTIVITY"] => HirCicsOperation::RunActivity,
        ["RUN", "TRANSID"] => HirCicsOperation::RunTransId,
        ["SUSPEND", "ACQACTIVITY"] => HirCicsOperation::SuspendAcqActivity,
        ["SUSPEND", "ACQPROCESS"] => HirCicsOperation::SuspendAcqProcess,
        ["SUSPEND", "ACTIVITY"] => HirCicsOperation::SuspendActivity,
        ["FETCH", "ANY"] => HirCicsOperation::FetchAny,
        ["FETCH", "CHILD"] => HirCicsOperation::FetchChild,
        ["FREE", "CHILD"] => HirCicsOperation::FreeChild,
        ["LINK", "ACQACTIVITY"] => HirCicsOperation::LinkAcqActivity,
        ["LINK", "ACQPROCESS"] => HirCicsOperation::LinkAcqProcess,
        ["LINK", "ACTIVITY"] => HirCicsOperation::LinkActivity,
        ["ABEND"] => HirCicsOperation::Abend,
        ["EXTRACT", "ATTACH"] => HirCicsOperation::ExtractAttach,
        ["EXTRACT", "ATTRIBUTES"] => HirCicsOperation::ExtractAttributes,
        ["GDS", "EXTRACT", "ATTRIBUTES"] => HirCicsOperation::GdsExtractAttributes,
        ["EXTRACT", "LOGONMSG"] => HirCicsOperation::ExtractLogonMsg,
        ["EXTRACT", "PROCESS"] => HirCicsOperation::ExtractProcess,
        ["GDS", "EXTRACT", "PROCESS"] => HirCicsOperation::GdsExtractProcess,
        ["EXTRACT", "TCT"] => HirCicsOperation::ExtractTct,
        ["POINT"] => HirCicsOperation::Point,
        ["ALLOCATE"] => HirCicsOperation::AllocateConversation,
        ["GDS", "ALLOCATE"] => HirCicsOperation::GdsAllocateConversation,
        ["GDS", "ASSIGN"] => HirCicsOperation::GdsAssignConversation,
        ["BUILD", "ATTACH"] => HirCicsOperation::BuildAttach,
        ["CONNECT", "PROCESS"] => HirCicsOperation::ConnectProcess,
        ["GDS", "CONNECT", "PROCESS"] => HirCicsOperation::GdsConnectProcess,
        ["CONVERSE"] => HirCicsOperation::Converse,
        ["FREE"] => HirCicsOperation::FreeConversation,
        ["GDS", "FREE"] => HirCicsOperation::GdsFreeConversation,
        ["RECEIVE"] => HirCicsOperation::ReceiveConversation,
        ["GDS", "RECEIVE"] => HirCicsOperation::GdsReceiveConversation,
        ["SEND"] => HirCicsOperation::SendConversation,
        ["WAIT"] => HirCicsOperation::GdsWaitConversation,
        ["WAIT", "CONVID"] => HirCicsOperation::WaitConvid,
        ["WAIT", "SIGNAL"] => HirCicsOperation::WaitSignal,
        ["WAIT", "TERMINAL"] => HirCicsOperation::WaitTerminal,
        ["ADD", "SUBEVENT"] => HirCicsOperation::AddSubevent,
        ["ADDRESS", "SET"] => HirCicsOperation::AddressSet,
        ["ADDRESS"] => HirCicsOperation::Address,
        ["ASKTIME", "ABSTIME"] => HirCicsOperation::Asktime,
        ["ASKTIME"] => HirCicsOperation::AsktimeEib,
        ["FORMATTIME"] => HirCicsOperation::FormatTime,
        ["CONVERTTIME"] => HirCicsOperation::ConvertTime,
        ["BIF", "DEEDIT"] => HirCicsOperation::BifDeedit,
        ["BIF", "DIGEST"] => HirCicsOperation::BifDigest,
        ["FREEMAIN"] => HirCicsOperation::Freemain,
        ["GETMAIN"] => HirCicsOperation::Getmain,
        ["CHANGE", "TASK"] => HirCicsOperation::ChangeTask,
        ["DEQ"] => HirCicsOperation::Deq,
        ["DEFINE", "COUNTER"] => HirCicsOperation::DefineCounter,
        ["DEFINE", "DCOUNTER"] => HirCicsOperation::DefineDCounter,
        ["DELETE", "COUNTER"] => HirCicsOperation::DeleteCounter,
        ["DELETE", "DCOUNTER"] => HirCicsOperation::DeleteDCounter,
        ["GET", "COUNTER"] => HirCicsOperation::GetCounter,
        ["GET", "DCOUNTER"] => HirCicsOperation::GetDCounter,
        ["QUERY", "COUNTER"] => HirCicsOperation::QueryCounter,
        ["QUERY", "DCOUNTER"] => HirCicsOperation::QueryDCounter,
        ["REWIND", "COUNTER"] => HirCicsOperation::RewindCounter,
        ["REWIND", "DCOUNTER"] => HirCicsOperation::RewindDCounter,
        ["UPDATE", "COUNTER"] => HirCicsOperation::UpdateCounter,
        ["UPDATE", "DCOUNTER"] => HirCicsOperation::UpdateDCounter,
        ["ENQ"] => HirCicsOperation::Enq,
        ["HANDLE", "ABEND"] => HirCicsOperation::HandleAbend,
        ["HANDLE", "AID"] => HirCicsOperation::HandleAid,
        ["HANDLE", "CONDITION"] => HirCicsOperation::HandleCondition,
        ["IGNORE", "CONDITION"] => HirCicsOperation::IgnoreCondition,
        ["INVOKE", "APPLICATION"] => HirCicsOperation::InvokeApplication,
        ["INVOKE", "SERVICE"] => HirCicsOperation::InvokeService,
        ["ISSUE", "ABORT"] => HirCicsOperation::IssueAbort,
        ["ISSUE", "ABEND"] => HirCicsOperation::IssueAbend,
        ["ISSUE", "CONFIRMATION"] => HirCicsOperation::IssueConfirmation,
        ["ISSUE", "COPY"] => HirCicsOperation::IssueCopy,
        ["ISSUE", "DISCONNECT"] => HirCicsOperation::IssueDisconnect,
        ["ISSUE", "ENDFILE"] => HirCicsOperation::IssueEndfile,
        ["ISSUE", "ENDOUTPUT"] => HirCicsOperation::IssueEndoutput,
        ["ISSUE", "EODS"] => HirCicsOperation::IssueEods,
        ["ISSUE", "ERASEAUP"] => HirCicsOperation::IssueEraseAup,
        ["ISSUE", "ERROR"] => HirCicsOperation::IssueError,
        ["ISSUE", "LOAD"] => HirCicsOperation::IssueLoad,
        ["ISSUE", "PASS"] => HirCicsOperation::IssuePass,
        ["ISSUE", "PREPARE"] => HirCicsOperation::IssuePrepare,
        ["ISSUE", "PRINT"] => HirCicsOperation::IssuePrint,
        ["ISSUE", "RESET"] => HirCicsOperation::IssueReset,
        ["ISSUE", "SIGNAL"] => HirCicsOperation::IssueSignal,
        ["ISSUE", "ADD"] => HirCicsOperation::IssueAdd,
        ["ISSUE", "END"] => HirCicsOperation::IssueEnd,
        ["ISSUE", "ERASE"] => HirCicsOperation::IssueErase,
        ["ISSUE", "NOTE"] => HirCicsOperation::IssueNote,
        ["ISSUE", "QUERY"] => HirCicsOperation::IssueQuery,
        ["ISSUE", "RECEIVE"] => HirCicsOperation::IssueReceive,
        ["ISSUE", "REPLACE"] => HirCicsOperation::IssueReplace,
        ["ISSUE", "SEND"] => HirCicsOperation::IssueSend,
        ["ROUTE"] => HirCicsOperation::Route,
        ["ISSUE", "WAIT"] => HirCicsOperation::IssueWait,
        ["SOAPFAULT", "ADD"] => HirCicsOperation::SoapFaultAdd,
        ["SOAPFAULT", "CREATE"] => HirCicsOperation::SoapFaultCreate,
        ["SOAPFAULT", "DELETE"] => HirCicsOperation::SoapFaultDelete,
        ["WSACONTEXT", "BUILD"] => HirCicsOperation::WsaContextBuild,
        ["WSACONTEXT", "DELETE"] => HirCicsOperation::WsaContextDelete,
        ["WSACONTEXT", "GET"] => HirCicsOperation::WsaContextGet,
        ["WSAEPR", "CREATE"] => HirCicsOperation::WsaEprCreate,
        ["LOAD"] => HirCicsOperation::Load,
        ["RELEASE"] => HirCicsOperation::Release,
        ["LINK"] => HirCicsOperation::Link,
        ["XCTL"] => HirCicsOperation::Xctl,
        ["RETURN"] => HirCicsOperation::Return,
        ["STARTBR"] => HirCicsOperation::StartBrowse,
        ["RESETBR"] => HirCicsOperation::ResetBrowse,
        ["UNLOCK"] => HirCicsOperation::Unlock,
        ["READNEXT"] => HirCicsOperation::ReadNext,
        ["READPREV"] => HirCicsOperation::ReadPrev,
        ["READQ", "TD"] => HirCicsOperation::ReadTransientData,
        ["REMOVE", "SUBEVENT"] => HirCicsOperation::RemoveSubevent,
        ["ENDBR"] => HirCicsOperation::EndBrowse,
        ["DELETE"] => HirCicsOperation::Delete,
        ["WRITE", "FILE"] => HirCicsOperation::Write,
        ["WRITEQ", "TD"] => HirCicsOperation::WriteTransientData,
        ["DELETEQ", "TD"] => HirCicsOperation::DeleteTransientData,
        ["DELETEQ", "TS"] => HirCicsOperation::DeleteTemporaryStorage,
        ["READQ", "TS"] => HirCicsOperation::ReadTemporaryStorage,
        ["WRITEQ", "TS"] => HirCicsOperation::WriteTemporaryStorage,
        ["RECEIVE", "MAP"] => HirCicsOperation::ReceiveMap,
        ["SEND", "MAP"] => HirCicsOperation::SendMap,
        ["SEND", "TEXT"] => HirCicsOperation::SendText,
        ["SEND", "PARTNSET"] => HirCicsOperation::SendPartnset,
        ["SEND", "CONTROL"] => HirCicsOperation::SendControl,
        ["SEND", "PAGE"] => HirCicsOperation::SendPage,
        ["RECEIVE", "PARTN"] => HirCicsOperation::ReceivePartn,
        ["ASSIGN"] => HirCicsOperation::Assign,
        ["CANCEL"] => HirCicsOperation::Cancel,
        ["DELAY"] => HirCicsOperation::Delay,
        ["POST"] => HirCicsOperation::Post,
        ["WRITE", "OPERATOR"] => HirCicsOperation::WriteOperator,
        ["EXTRACT", "CERTIFICATE"] => HirCicsOperation::ExtractCertificate,
        ["EXTRACT", "TCPIP"] => HirCicsOperation::ExtractTcpip,
        ["PURGE", "MESSAGE"] => HirCicsOperation::PurgeMessage,
        ["QUERY", "SECURITY"] => HirCicsOperation::QuerySecurity,
        ["VERIFY", "PASSWORD"] => HirCicsOperation::VerifyPassword,
        ["CHANGE", "PASSWORD"] => HirCicsOperation::ChangePassword,
        ["CHANGE", "PHRASE"] => HirCicsOperation::ChangePhrase,
        ["REQUEST", "PASSTICKET"] => HirCicsOperation::RequestPassTicket,
        ["REQUEST", "ENCRYPTPTKT"] => HirCicsOperation::RequestEncryptPassTicket,
        ["SIGNON"] => HirCicsOperation::Signon,
        ["SIGNOFF"] => HirCicsOperation::Signoff,
        ["VERIFY", "PHRASE"] => HirCicsOperation::VerifyPhrase,
        ["VERIFY", "TOKEN"] => HirCicsOperation::VerifyToken,
        ["POP", "HANDLE"] => HirCicsOperation::PopHandle,
        ["PUSH", "HANDLE"] => HirCicsOperation::PushHandle,
        ["READ"] => HirCicsOperation::Read,
        ["REWRITE"] => HirCicsOperation::Rewrite,
        ["SET", "ASSOCIATION", "USERCORRDATA"] => HirCicsOperation::SetAssociationUserCorrData,
        ["SPOOLCLOSE"] => HirCicsOperation::SpoolClose,
        ["SPOOLOPEN", "INPUT"] => HirCicsOperation::SpoolOpenInput,
        ["SPOOLOPEN", "OUTPUT"] => HirCicsOperation::SpoolOpenOutput,
        ["SPOOLREAD"] => HirCicsOperation::SpoolRead,
        ["SPOOLWRITE"] => HirCicsOperation::SpoolWrite,
        ["ENTER", "TRACENUM"] => HirCicsOperation::EnterTraceNum,
        ["ENTER", "TRACEID"] => HirCicsOperation::EnterTraceId,
        ["MONITOR"] => HirCicsOperation::Monitor,
        ["DUMP", "TRANSACTION"] => HirCicsOperation::DumpTransaction,
        ["DUMP"] => HirCicsOperation::Dump,
        ["TRACE"] => HirCicsOperation::Trace,
        ["SYNCPOINT"] => HirCicsOperation::Syncpoint,
        ["SUSPEND"] => HirCicsOperation::Suspend,
        ["WAIT", "EVENT"] => HirCicsOperation::WaitEvent,
        ["WAIT", "EXTERNAL"] => HirCicsOperation::WaitExternal,
        ["WAITCICS"] => HirCicsOperation::WaitCics,
        ["START"] => HirCicsOperation::Start,
        ["START", "ATTACH"] => HirCicsOperation::StartAttach,
        ["START", "BREXIT"] => HirCicsOperation::StartBrexit,
        ["RETRIEVE"] => HirCicsOperation::Retrieve,
        ["DOCUMENT", "CREATE"] => HirCicsOperation::DocumentCreate,
        ["DEFINE", "INPUT", "EVENT"] => HirCicsOperation::DefineInputEvent,
        ["DEFINE", "COMPOSITE", "EVENT"] => HirCicsOperation::DefineCompositeEvent,
        ["DELETE", "EVENT"] => HirCicsOperation::DeleteEvent,
        ["CHECK", "TIMER"] => HirCicsOperation::CheckTimer,
        ["DEFINE", "TIMER"] => HirCicsOperation::DefineTimer,
        ["DELETE", "TIMER"] => HirCicsOperation::DeleteTimer,
        ["RETRIEVE", "REATTACH", "EVENT"] => HirCicsOperation::RetrieveReattachEvent,
        ["RETRIEVE", "SUBEVENT"] => HirCicsOperation::RetrieveSubevent,
        ["TEST", "EVENT"] => HirCicsOperation::TestEvent,
        ["SIGNAL", "EVENT"] => HirCicsOperation::SignalEvent,
        ["FORCE", "TIMER"] => HirCicsOperation::ForceTimer,
        ["DOCUMENT", "DELETE"] => HirCicsOperation::DocumentDelete,
        ["DOCUMENT", "INSERT"] => HirCicsOperation::DocumentInsert,
        ["DOCUMENT", "RETRIEVE"] => HirCicsOperation::DocumentRetrieve,
        ["DOCUMENT", "SET"] => HirCicsOperation::DocumentSet,
        ["TRANSFORM", "DATATOJSON"] => HirCicsOperation::TransformDataToJson,
        ["TRANSFORM", "DATATOXML"] => HirCicsOperation::TransformDataToXml,
        ["TRANSFORM", "JSONTODATA"] => HirCicsOperation::TransformJsonToData,
        ["TRANSFORM", "XMLTODATA"] => HirCicsOperation::TransformXmlToData,
        ["WEB", "PARSE", "URL"] => HirCicsOperation::WebParseUrl,
        ["WEB", "OPEN"] => HirCicsOperation::WebOpen,
        ["WEB", "CLOSE"] => HirCicsOperation::WebClose,
        ["WEB", "EXTRACT"] => HirCicsOperation::WebExtract,
        ["EXTRACT", "WEB"] => HirCicsOperation::ExtractWeb,
        ["WEB", "READ"] => HirCicsOperation::WebRead,
        ["WEB", "STARTBROWSE"] => HirCicsOperation::WebStartBrowse,
        ["WEB", "READNEXT"] => HirCicsOperation::WebReadNext,
        ["WEB", "ENDBROWSE"] => HirCicsOperation::WebEndBrowse,
        ["WEB", "WRITE"] => HirCicsOperation::WebWrite,
        ["WEB", "SEND"] => HirCicsOperation::WebSend,
        ["WEB", "RETRIEVE"] => HirCicsOperation::WebRetrieve,
        ["WEB", "RECEIVE"] => HirCicsOperation::WebReceive,
        ["WEB", "CONVERSE"] => HirCicsOperation::WebConverse,
        ["WAIT", "JOURNALNAME"] => HirCicsOperation::WaitJournalName,
        ["WAIT", "JOURNALNUM"] => HirCicsOperation::WaitJournalNum,
        ["WRITE", "JOURNALNAME"] => HirCicsOperation::WriteJournalName,
        ["WRITE", "JOURNALNUM"] => HirCicsOperation::WriteJournalNum,
        _ => return Err(ResolutionFailure::Unsupported),
    })
}

pub(super) fn resolve_option(option: &str, operation: HirCicsOperation) -> HirCicsOption {
    match option {
        "BASICAUTH" => HirCicsOption::SecurityBasicAuth,
        "JWT" => HirCicsOption::SecurityJwt,
        "KERBEROS" => HirCicsOption::SecurityKerberos,
        "BIT" => HirCicsOption::SecurityBit,
        "BASE64" if operation == HirCicsOperation::BifDigest => HirCicsOption::DigestBase64,
        "BASE64" => HirCicsOption::SecurityBase64,
        "DEFRESP" => HirCicsOption::DefResp,
        "NOWAIT" => HirCicsOption::NoWait,
        "RRN" => HirCicsOption::Rrn,
        "CONSOLE" => HirCicsOption::Console,
        "PRINT"
            if matches!(
                operation,
                HirCicsOperation::IssueAbort
                    | HirCicsOperation::IssueEnd
                    | HirCicsOperation::IssueSend
                    | HirCicsOperation::IssueWait
            ) =>
        {
            HirCicsOption::PrintMedium
        }
        "CARD" => HirCicsOption::Card,
        "WPMEDIA1" => HirCicsOption::WpMedia1,
        "WPMEDIA2" => HirCicsOption::WpMedia2,
        "WPMEDIA3" => HirCicsOption::WpMedia3,
        "NLEOM" => HirCicsOption::Nleom,
        "WPMEDIA4" => HirCicsOption::WpMedia4,
        "HEX" => HirCicsOption::DigestHex,
        "BINARY" => HirCicsOption::DigestBinary,
        "IMMEDIATE" => HirCicsOption::OperatorImmediate,
        "EVENTUAL" => HirCicsOption::OperatorEventual,
        "CRITICAL" => HirCicsOption::OperatorCritical,
        "OWNER" => HirCicsOption::CertificateOwner,
        "ISSUER" => HirCicsOption::CertificateIssuer,
        "CANCEL" => HirCicsOption::Cancel,
        "NODUMP" => HirCicsOption::NoDump,
        "RESET" => HirCicsOption::Reset,
        "UPDATE" => HirCicsOption::Update,
        "ROLLBACK" => HirCicsOption::Rollback,
        "NOHANDLE" => HirCicsOption::NoHandle,
        "ASIS" => HirCicsOption::AsIs,
        "ACCUM" => HirCicsOption::Accum,
        "FORMFEED" => HirCicsOption::Formfeed,
        "DEFAULT" => HirCicsOption::DefaultScreen,
        "ALTERNATE" => HirCicsOption::AlternateScreen,
        "ERASEAUP" => HirCicsOption::EraseAup,
        "PRINT" => HirCicsOption::Print,
        "ALARM" => HirCicsOption::Alarm,
        "FRSET" => HirCicsOption::Frset,
        "PAGING" => HirCicsOption::Paging,
        "LAST" => HirCicsOption::Last,
        "HONEOM" => HirCicsOption::Honeom,
        "L40" => HirCicsOption::L40,
        "L64" => HirCicsOption::L64,
        "L80" => HirCicsOption::L80,
        "RELEASE" => HirCicsOption::ReleasePage,
        "RETAIN" => HirCicsOption::RetainPage,
        "AUTOPAGE" => HirCicsOption::Autopage,
        "CURRENT" => HirCicsOption::CurrentPage,
        "ALL" => HirCicsOption::AllPages,
        "NOAUTOPAGE" => HirCicsOption::NoAutopage,
        "OPERPURGE" => HirCicsOption::OperPurge,
        "AND" => HirCicsOption::EventAnd,
        "OR" => HirCicsOption::EventOr,
        "TASK" => HirCicsOption::Task,
        "UOW" => HirCicsOption::Uow,
        "NOSUSPEND" => HirCicsOption::NoSuspend,
        "ERASE" => HirCicsOption::Erase,
        "CURSOR" => HirCicsOption::Cursor,
        "DATESEP" => HirCicsOption::DateSep,
        "TIMESEP" => HirCicsOption::TimeSep,
        "FREEKB" => HirCicsOption::FreeKb,
        "GTEQ" => HirCicsOption::Gteq,
        "GENERIC" => HirCicsOption::Generic,
        "EQUAL" => HirCicsOption::Equal,
        "TERMINAL" => HirCicsOption::Terminal,
        "FMH" => HirCicsOption::Fmh,
        "PROTECT" => HirCicsOption::Protect,
        "WAIT"
            if matches!(
                operation,
                HirCicsOperation::IssueCopy | HirCicsOperation::IssueEraseAup
            ) =>
        {
            HirCicsOption::IssueWaitOption
        }
        "WAIT" => HirCicsOption::Wait,
        "ENDOUTPUT" if operation == HirCicsOperation::IssueEndfile => HirCicsOption::IssueEndOutput,
        "ENDFILE" if operation == HirCicsOperation::IssueEndoutput => HirCicsOption::IssueEndFile,
        "CONVERSE" if operation == HirCicsOperation::IssueLoad => HirCicsOption::IssueConverse,
        "LOGONLOGMODE" if operation == HirCicsOperation::IssuePass => {
            HirCicsOption::IssueLogonLogmode
        }
        "NOQUIESCE" if operation == HirCicsOperation::IssuePass => HirCicsOption::IssueNoQuiesce,
        "AFTER" => HirCicsOption::After,
        "AT" => HirCicsOption::At,
        "FOR" => HirCicsOption::For,
        "UNTIL" => HirCicsOption::Until,
        "NOCHECK" => HirCicsOption::NoCheck,
        "MAPONLY" => HirCicsOption::MapOnly,
        "DATAONLY" => HirCicsOption::DataOnly,
        "UNESCAPED" => HirCicsOption::Unescaped,
        "NEXT" => HirCicsOption::Next,
        "REWRITE" => HirCicsOption::RewriteTemporary,
        "AUXILIARY" => HirCicsOption::Auxiliary,
        "MAIN" => HirCicsOption::Main,
        "PURGEABLE" => HirCicsOption::Purgeable,
        "NOTPURGEABLE" => HirCicsOption::NotPurgeable,
        "EXACTMATCH" => HirCicsOption::ExactMatch,
        "MINIMUM" => HirCicsOption::Minimum,
        "HOLD" => HirCicsOption::Hold,
        "EXCEPTION" => HirCicsOption::TraceException,
        "HTTPHEADER" => HirCicsOption::WebBrowseHttpHeader,
        "QUERYPARM" => HirCicsOption::WebBrowseQueryParm,
        "FORMFIELD" => HirCicsOption::WebBrowseFormField,
        "NOTRUNCATE" => HirCicsOption::WebNotruncate,
        "NOCLICONVERT" => HirCicsOption::WebNoClientConvert,
        "NOSRVCONVERT" => HirCicsOption::WebNoServerConvert,
        _ => super::spool_control::option(option).expect("allowed CICS option"),
    }
}

#[cfg(test)]
mod issue_tests {
    use super::*;
    use mainframe_env_ir::CICS_APPLICATION_REGISTRY;

    #[test]
    fn assigned_issue_rows_keep_distinct_cobol_heads_and_gds_rejection() {
        let mapped_and_device = [
            ("0108", HirCicsOperation::IssueAbend),
            ("0112", HirCicsOperation::IssueConfirmation),
            ("0114", HirCicsOperation::IssueCopy),
            ("0115", HirCicsOperation::IssueDisconnect),
            ("0117", HirCicsOperation::IssueEndfile),
            ("0118", HirCicsOperation::IssueEndoutput),
            ("0119", HirCicsOperation::IssueEods),
            ("0121", HirCicsOperation::IssueEraseAup),
            ("0122", HirCicsOperation::IssueError),
            ("0124", HirCicsOperation::IssueLoad),
            ("0126", HirCicsOperation::IssuePass),
            ("0127", HirCicsOperation::IssuePrepare),
            ("0129", HirCicsOperation::IssuePrint),
            ("0133", HirCicsOperation::IssueReset),
            ("0136", HirCicsOperation::IssueSignal),
        ];
        for (row, expected) in mapped_and_device {
            let descriptor = CICS_APPLICATION_REGISTRY
                .iter()
                .find(|descriptor| descriptor.official_row.ends_with(row))
                .unwrap();
            assert!(matches!(resolve(descriptor), Ok(actual) if actual == expected));
        }
        for row in ["0109", "0113", "0123", "0128", "0135"] {
            let descriptor = CICS_APPLICATION_REGISTRY
                .iter()
                .find(|descriptor| descriptor.official_row.ends_with(row))
                .unwrap();
            assert!(matches!(
                resolve(descriptor),
                Err(ResolutionFailure::Unsupported)
            ));
        }
        assert_eq!(
            resolve_option("WAIT", HirCicsOperation::IssueCopy),
            HirCicsOption::IssueWaitOption
        );
        assert_eq!(
            resolve_option("ENDOUTPUT", HirCicsOperation::IssueEndfile),
            HirCicsOption::IssueEndOutput
        );
    }
}
