use super::*;

/// Eight source-pinned extraction and positioning routes, in reserved tag order.
pub(super) const CONVERSATION_EXECUTABLE_DESCRIPTORS: [CicsExecutableDescriptor; 8] = [
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ExtractAttach,
        namespace: "cics.conversation",
        name: "extract-attach",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ExtractAttributes,
        namespace: "cics.conversation",
        name: "extract-attributes",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::GdsExtractAttributes,
        namespace: "cics.conversation",
        name: "gds-extract-attributes",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ExtractLogonMsg,
        namespace: "cics.conversation",
        name: "extract-logonmsg",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ExtractProcess,
        namespace: "cics.conversation",
        name: "extract-process",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::GdsExtractProcess,
        namespace: "cics.conversation",
        name: "gds-extract-process",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ExtractTct,
        namespace: "cics.conversation",
        name: "extract-tct",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Point,
        namespace: "cics.conversation",
        name: "point",
        major: 1,
        effects: DOCUMENT_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
];

pub(super) const CONVERSATION_OPEN_EXECUTABLE_DESCRIPTORS: [CicsExecutableDescriptor; 9] = [
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::AllocateConversation,
        namespace: "cics.conversation",
        name: "allocate",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::GdsAllocateConversation,
        namespace: "cics.conversation",
        name: "gds-allocate",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::GdsAssignConversation,
        namespace: "cics.conversation",
        name: "gds-assign",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::BuildAttach,
        namespace: "cics.conversation",
        name: "build-attach",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ConnectProcess,
        namespace: "cics.conversation",
        name: "connect-process",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::GdsConnectProcess,
        namespace: "cics.conversation",
        name: "gds-connect-process",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Converse,
        namespace: "cics.conversation",
        name: "converse",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::FreeConversation,
        namespace: "cics.conversation",
        name: "free",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::GdsFreeConversation,
        namespace: "cics.conversation",
        name: "gds-free",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
];

pub(super) const CONVERSATION_DATA_EXECUTABLE_DESCRIPTORS: [CicsExecutableDescriptor; 7] = [
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ReceiveConversation,
        namespace: "cics.conversation",
        name: "receive",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::GdsReceiveConversation,
        namespace: "cics.conversation",
        name: "gds-receive",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::SendConversation,
        namespace: "cics.conversation",
        name: "send",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::GdsWaitConversation,
        namespace: "cics.conversation",
        name: "gds-wait",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WaitConvid,
        namespace: "cics.conversation",
        name: "wait-convid",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WaitSignal,
        namespace: "cics.conversation",
        name: "wait-signal",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::WaitTerminal,
        namespace: "cics.conversation",
        name: "wait-terminal",
        major: 1,
        effects: CONVERSATION_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
];
