use super::*;

pub(super) const SECURITY_EXECUTABLE_DESCRIPTORS: [CicsExecutableDescriptor; 10] = [
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::QuerySecurity,
        namespace: "cics.security",
        name: "query",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::VerifyPassword,
        namespace: "cics.security",
        name: "verify-password",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::VerifyPhrase,
        namespace: "cics.security",
        name: "verify-phrase",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ChangePassword,
        namespace: "cics.security",
        name: "change-password",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::ChangePhrase,
        namespace: "cics.security",
        name: "change-phrase",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::RequestPassTicket,
        namespace: "cics.security",
        name: "request-passticket",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::RequestEncryptPassTicket,
        namespace: "cics.security",
        name: "request-encryptptkt",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Signon,
        namespace: "cics.security",
        name: "signon",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::Signoff,
        namespace: "cics.security",
        name: "signoff",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
    CicsExecutableDescriptor {
        operation: CicsPlanOperation::VerifyToken,
        namespace: "cics.security",
        name: "verify-token",
        major: 1,
        effects: STORAGE_EFFECTS,
        runtime_import: CICS_RUNTIME_IMPORT,
    },
];
