// @generated by tools/generate_mq_mqi_registry.py; do not edit.
/// Frozen private RFH2 projection, with no execution credit.
pub const MQ_RFH2_PROFILE_SHA256: &str =
    "d975dd8353d7c3eb5e36be6d045518cf9174bb40447416184261f1e8e564c95b";
pub(super) const MQBMHO_DELETE_PROPERTIES: i32 = 1;
pub(super) const MQBMHO_NONE: i32 = 0;
pub(super) const MQBMHO_VERSION_1: i32 = 1;
pub(super) const MQMHBO_DELETE_PROPERTIES: i32 = 2;
pub(super) const MQMHBO_NONE: i32 = 0;
pub(super) const MQMHBO_PROPERTIES_IN_MQRFH2: i32 = 1;
pub(super) const MQMHBO_VERSION_1: i32 = 1;
pub(super) const MQRFH_NONE: i32 = 0;
pub(super) const MQRFH_STRUC_LENGTH_FIXED_2: i32 = 36;
pub(super) const MQRFH_VERSION_2: i32 = 2;
pub(super) const MQBMHO_STRUC_ID: [u8; 4] = *b"BMHO";
pub(super) const MQMHBO_STRUC_ID: [u8; 4] = *b"MHBO";
pub(super) const MQRFH_STRUC_ID: [u8; 4] = *b"RFH ";
pub(super) const MQFMT_NONE: [u8; 8] = *b"        ";
pub(super) const MQFMT_RF_HEADER_2: [u8; 8] = *b"MQHRF2  ";
pub(super) const STRUCID_OFFSET: usize = 0;
pub(super) const VERSION_OFFSET: usize = 4;
pub(super) const STRUCLENGTH_OFFSET: usize = 8;
pub(super) const ENCODING_OFFSET: usize = 12;
pub(super) const CODEDCHARSETID_OFFSET: usize = 16;
pub(super) const FORMAT_OFFSET: usize = 20;
pub(super) const FLAGS_OFFSET: usize = 28;
pub(super) const NAMEVALUECCSID_OFFSET: usize = 32;
pub(super) const MQCCSI_INHERIT: i32 = -2;
pub(super) const NAME_VALUE_CCSID: i32 = 1208;
pub(super) const RESERVED_NAMES: &[&str] = &[
    "Root",
    "Body",
    "Properties",
    "Environment",
    "LocalEnvironment",
    "DestinationList",
    "ExceptionList",
    "InputBody",
    "InputRoot",
    "InputProperties",
    "InputLocalEnvironment",
    "InputDestinationList",
    "InputExceptionList",
    "OutputRoot",
    "OutputLocalEnvironment",
    "OutputDestinationList",
    "OutputExceptionList",
];
pub(super) const RESERVED_PREFIXES: &[&str] = &[
    "body",
    "jms",
    "mcd",
    "properties",
    "psc",
    "pscr",
    "root",
    "usr",
    "ibm",
    "mq",
    "sib",
    "wmq",
    "xml",
];
pub(super) fn lexical(kind: crate::MqPropertyType) -> Option<&'static str> {
    Some(match kind {
        crate::MqPropertyType::ByteString => "bin.hex",
        crate::MqPropertyType::Int8 => "i1",
        crate::MqPropertyType::Int16 => "i2",
        crate::MqPropertyType::Int32 => "i4",
        crate::MqPropertyType::Int64 => "i8",
        crate::MqPropertyType::String => "string",
        _ => return None,
    })
}
