use super::*;

/// Buffer observation distinguishes untouched storage from an actual generated
/// prefix. No failure padding or copied bytes are synthesized.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MqRfh2BufferObservation {
    /// All application bytes retain their original value.
    Unchanged,
    /// Exact prefix written by the owned formatter; remaining capacity is untouched.
    WrittenPrefix(Vec<u8>),
}
/// Lossless defined observations for the finite conversion profile. Associated
/// descriptor replacement is registry state, never an application MD writeback.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MqRfh2Observation {
    /// Actual outer MHBUF descriptor, or absent when unchanged/undefined.
    pub descriptor: Option<MqMdValue>,
    /// Defined required/generated byte length, or absent when undefined.
    pub data_length: Option<i32>,
    /// Exact write/no-write observation, not a successful buffer placeholder.
    pub buffer: MqRfh2BufferObservation,
}
impl MqRfh2Observation {
    /// Standalone bounds and call shape. Request binding and live source authority
    /// are additional obligations before physical publication or writeback.
    pub fn validate(&self, call: MqMqiCall, limits: MqMqiLimits) -> Result<(), MqPropertyProblem> {
        limits.validate().map_err(|_| MqPropertyProblem::Capacity)?;
        if !matches!(call, MqMqiCall::BufferToHandle | MqMqiCall::HandleToBuffer) {
            return Err(MqPropertyProblem::Call);
        }
        if let Some(length) = self.data_length {
            if length < 0 || length as usize > limits.buffer_bytes {
                return Err(MqPropertyProblem::Capacity);
            }
        }
        match &self.buffer {
            MqRfh2BufferObservation::Unchanged => {
                if self.descriptor.is_some() {
                    return Err(MqPropertyProblem::Value);
                }
            }
            MqRfh2BufferObservation::WrittenPrefix(bytes) => {
                if call != MqMqiCall::HandleToBuffer
                    || bytes.len() > limits.buffer_bytes
                    || self.data_length != i32::try_from(bytes.len()).ok()
                {
                    return Err(MqPropertyProblem::Value);
                }
                validate_md(self.descriptor.as_ref().ok_or(MqPropertyProblem::Value)?)?;
            }
        }
        Ok(())
    }
    /// Exact finite reviewed call/completion/reason pairing, with no mutation
    /// decision inferred from the reason's name.
    pub fn validate_status(&self, status: MqReviewedStatus) -> bool {
        match (
            status.call(),
            status.completion(),
            status.reason_symbol(),
            &self.buffer,
        ) {
            (
                MqMqiCall::BufferToHandle,
                MqCompletion::Ok,
                "MQRC_NONE",
                MqRfh2BufferObservation::Unchanged,
            ) => self.data_length.is_some(),
            (
                MqMqiCall::BufferToHandle,
                MqCompletion::Failed,
                "MQRC_RFH_ERROR" | "MQRC_RFH_FORMAT_ERROR",
                MqRfh2BufferObservation::Unchanged,
            ) => self.data_length.is_none(),
            (
                MqMqiCall::HandleToBuffer,
                MqCompletion::Ok,
                "MQRC_NONE",
                MqRfh2BufferObservation::WrittenPrefix(_),
            ) => self.descriptor.is_some(),
            (
                MqMqiCall::HandleToBuffer,
                MqCompletion::Failed,
                "MQRC_PROPERTY_VALUE_TOO_BIG",
                MqRfh2BufferObservation::Unchanged,
            ) => self.data_length.is_some_and(|v| v > 0),
            (
                MqMqiCall::HandleToBuffer,
                MqCompletion::Failed,
                "MQRC_PROPERTY_NOT_AVAILABLE",
                MqRfh2BufferObservation::Unchanged,
            ) => self.data_length == Some(0),
            _ => false,
        }
    }
}
pub(in crate::mq_mqi) fn bind(
    request: &MqMqiRequest,
    output: &MqMqiOutput,
) -> Result<(), MqPropertyProblem> {
    let MqMqiRequest::Rfh2(request) = request else {
        return if matches!(output, MqMqiOutput::Rfh2Observation(_)) {
            Err(MqPropertyProblem::Call)
        } else {
            Ok(())
        };
    };
    let MqMqiOutput::Rfh2Observation(v) = output else {
        return Err(MqPropertyProblem::Call);
    };
    match request {
        MqMqiRfh2Request::BufferToHandle { buffer, .. } => {
            if v.descriptor.is_some()
                || v.buffer != MqRfh2BufferObservation::Unchanged
                || v.data_length.is_some_and(|n| n as usize != buffer.len())
            {
                return Err(MqPropertyProblem::Value);
            }
        }
        MqMqiRfh2Request::HandleToBuffer {
            descriptor,
            buffer_capacity,
            name,
            ..
        } => {
            match &v.buffer {
                MqRfh2BufferObservation::WrittenPrefix(bytes) => {
                    if bytes.len() > *buffer_capacity || v.descriptor != Some(outer_md(descriptor))
                    {
                        return Err(MqPropertyProblem::Value);
                    }
                    // Validate exact single-property folder and absence of any
                    // body before accepting a directly assembled result.
                    let limits = MqMqiLimits::default();
                    let imported = mq_rfh2_decode(v.descriptor.as_ref().unwrap(), bytes, limits)?;
                    if !imported.tail.is_empty()
                        || imported.properties.len() != 1
                        || imported.properties[0].0 != *name
                    {
                        return Err(MqPropertyProblem::Value);
                    }
                }
                MqRfh2BufferObservation::Unchanged => {
                    if v.descriptor.is_some()
                        || v.data_length
                            .is_some_and(|n| n > 0 && n as usize <= *buffer_capacity)
                    {
                        return Err(MqPropertyProblem::Value);
                    }
                }
            }
        }
    }
    Ok(())
}
