use super::*;

pub(super) const fn operation_tag(value: CicsPlanOperation) -> u16 {
    match value {
        CicsPlanOperation::AllocateConversation => 222,
        CicsPlanOperation::GdsAllocateConversation => 223,
        CicsPlanOperation::GdsAssignConversation => 224,
        CicsPlanOperation::BuildAttach => 225,
        CicsPlanOperation::ConnectProcess => 226,
        CicsPlanOperation::GdsConnectProcess => 227,
        CicsPlanOperation::Converse => 228,
        CicsPlanOperation::FreeConversation => 229,
        CicsPlanOperation::GdsFreeConversation => 230,
        CicsPlanOperation::ReceiveConversation => 259,
        CicsPlanOperation::GdsReceiveConversation => 260,
        CicsPlanOperation::SendConversation => 261,
        CicsPlanOperation::GdsWaitConversation => 262,
        CicsPlanOperation::WaitConvid => 263,
        CicsPlanOperation::WaitSignal => 264,
        CicsPlanOperation::WaitTerminal => 265,
        _ => panic!("unmapped conversation operation"),
    }
}

pub(super) fn operation_from_tag(value: u16) -> Result<CicsPlanOperation, CicsPlanCodecProblem> {
    match value {
        222 => Ok(CicsPlanOperation::AllocateConversation),
        223 => Ok(CicsPlanOperation::GdsAllocateConversation),
        224 => Ok(CicsPlanOperation::GdsAssignConversation),
        225 => Ok(CicsPlanOperation::BuildAttach),
        226 => Ok(CicsPlanOperation::ConnectProcess),
        227 => Ok(CicsPlanOperation::GdsConnectProcess),
        228 => Ok(CicsPlanOperation::Converse),
        229 => Ok(CicsPlanOperation::FreeConversation),
        230 => Ok(CicsPlanOperation::GdsFreeConversation),
        259 => Ok(CicsPlanOperation::ReceiveConversation),
        260 => Ok(CicsPlanOperation::GdsReceiveConversation),
        261 => Ok(CicsPlanOperation::SendConversation),
        262 => Ok(CicsPlanOperation::GdsWaitConversation),
        263 => Ok(CicsPlanOperation::WaitConvid),
        264 => Ok(CicsPlanOperation::WaitSignal),
        265 => Ok(CicsPlanOperation::WaitTerminal),
        _ => Err(CicsPlanCodecProblem::Malformed),
    }
}

pub(super) const fn operand_tag(value: CicsOperandName) -> u16 {
    match value {
        CicsOperandName::ConversationSysid => 1216,
        CicsOperandName::ConversationPartner => 1217,
        CicsOperandName::ConversationProfile => 1218,
        CicsOperandName::ConversationSession => 1219,
        CicsOperandName::ConversationModeName => 1220,
        CicsOperandName::ConversationConvid => 1221,
        CicsOperandName::ConversationAttachId => 1222,
        CicsOperandName::ConversationProcess => 1223,
        CicsOperandName::ConversationResource => 1224,
        CicsOperandName::ConversationReturnProcess => 1225,
        CicsOperandName::ConversationReturnResource => 1226,
        CicsOperandName::ConversationQueue => 1227,
        CicsOperandName::ConversationIuType => 1228,
        CicsOperandName::ConversationDataStream => 1229,
        CicsOperandName::ConversationRecordFormat => 1230,
        CicsOperandName::ConversationProcName => 1231,
        CicsOperandName::ConversationProcLength => 1232,
        CicsOperandName::ConversationPipList => 1233,
        CicsOperandName::ConversationPipLength => 1234,
        CicsOperandName::ConversationSyncLevel => 1235,
        CicsOperandName::ConversationFrom => 1236,
        CicsOperandName::ConversationFromLength => 1237,
        CicsOperandName::ConversationFromFullLength => 1238,
        CicsOperandName::ConversationMaxLength => 1239,
        CicsOperandName::ConversationMaxFullLength => 1240,
        CicsOperandName::ConversationToLength => 1241,
        CicsOperandName::ConversationToFullLength => 1242,
        CicsOperandName::ConversationDataConvid => 1600,
        CicsOperandName::ConversationDataSession => 1601,
        CicsOperandName::ConversationDataFrom => 1602,
        CicsOperandName::ConversationDataLength => 1603,
        CicsOperandName::ConversationDataFullLength => 1604,
        CicsOperandName::ConversationDataMaxLength => 1605,
        CicsOperandName::ConversationDataMaxFullLength => 1606,
        CicsOperandName::ConversationDataAttachId => 1607,
        _ => panic!("unmapped conversation operand"),
    }
}

pub(super) fn operand_from_tag(value: u16) -> Result<CicsOperandName, CicsPlanCodecProblem> {
    match value {
        1216 => Ok(CicsOperandName::ConversationSysid),
        1217 => Ok(CicsOperandName::ConversationPartner),
        1218 => Ok(CicsOperandName::ConversationProfile),
        1219 => Ok(CicsOperandName::ConversationSession),
        1220 => Ok(CicsOperandName::ConversationModeName),
        1221 => Ok(CicsOperandName::ConversationConvid),
        1222 => Ok(CicsOperandName::ConversationAttachId),
        1223 => Ok(CicsOperandName::ConversationProcess),
        1224 => Ok(CicsOperandName::ConversationResource),
        1225 => Ok(CicsOperandName::ConversationReturnProcess),
        1226 => Ok(CicsOperandName::ConversationReturnResource),
        1227 => Ok(CicsOperandName::ConversationQueue),
        1228 => Ok(CicsOperandName::ConversationIuType),
        1229 => Ok(CicsOperandName::ConversationDataStream),
        1230 => Ok(CicsOperandName::ConversationRecordFormat),
        1231 => Ok(CicsOperandName::ConversationProcName),
        1232 => Ok(CicsOperandName::ConversationProcLength),
        1233 => Ok(CicsOperandName::ConversationPipList),
        1234 => Ok(CicsOperandName::ConversationPipLength),
        1235 => Ok(CicsOperandName::ConversationSyncLevel),
        1236 => Ok(CicsOperandName::ConversationFrom),
        1237 => Ok(CicsOperandName::ConversationFromLength),
        1238 => Ok(CicsOperandName::ConversationFromFullLength),
        1239 => Ok(CicsOperandName::ConversationMaxLength),
        1240 => Ok(CicsOperandName::ConversationMaxFullLength),
        1241 => Ok(CicsOperandName::ConversationToLength),
        1242 => Ok(CicsOperandName::ConversationToFullLength),
        1600 => Ok(CicsOperandName::ConversationDataConvid),
        1601 => Ok(CicsOperandName::ConversationDataSession),
        1602 => Ok(CicsOperandName::ConversationDataFrom),
        1603 => Ok(CicsOperandName::ConversationDataLength),
        1604 => Ok(CicsOperandName::ConversationDataFullLength),
        1605 => Ok(CicsOperandName::ConversationDataMaxLength),
        1606 => Ok(CicsOperandName::ConversationDataMaxFullLength),
        1607 => Ok(CicsOperandName::ConversationDataAttachId),
        _ => Err(CicsPlanCodecProblem::Malformed),
    }
}

pub(super) const fn option_tag(value: CicsPlanOption) -> u16 {
    match value {
        CicsPlanOption::ConversationNoQueue => 1148,
        CicsPlanOption::ConversationNotruncate => 1149,
        CicsPlanOption::ConversationDefresp => 1150,
        CicsPlanOption::ConversationFmh => 1151,
        CicsPlanOption::ConversationDataNotruncate => 1532,
        CicsPlanOption::ConversationDataBuffer => 1533,
        CicsPlanOption::ConversationDataLlid => 1534,
        CicsPlanOption::ConversationDataInvite => 1535,
        CicsPlanOption::ConversationDataLast => 1536,
        CicsPlanOption::ConversationDataConfirm => 1537,
        CicsPlanOption::ConversationDataWait => 1538,
        CicsPlanOption::ConversationDataFmh => 1539,
        CicsPlanOption::ConversationDataDefresp => 1540,
        _ => panic!("unmapped conversation option"),
    }
}

pub(super) fn option_from_tag(value: u16) -> Result<CicsPlanOption, CicsPlanCodecProblem> {
    match value {
        1148 => Ok(CicsPlanOption::ConversationNoQueue),
        1149 => Ok(CicsPlanOption::ConversationNotruncate),
        1150 => Ok(CicsPlanOption::ConversationDefresp),
        1151 => Ok(CicsPlanOption::ConversationFmh),
        1532 => Ok(CicsPlanOption::ConversationDataNotruncate),
        1533 => Ok(CicsPlanOption::ConversationDataBuffer),
        1534 => Ok(CicsPlanOption::ConversationDataLlid),
        1535 => Ok(CicsPlanOption::ConversationDataInvite),
        1536 => Ok(CicsPlanOption::ConversationDataLast),
        1537 => Ok(CicsPlanOption::ConversationDataConfirm),
        1538 => Ok(CicsPlanOption::ConversationDataWait),
        1539 => Ok(CicsPlanOption::ConversationDataFmh),
        1540 => Ok(CicsPlanOption::ConversationDataDefresp),
        _ => Err(CicsPlanCodecProblem::Malformed),
    }
}
