[package]
name = "mainframe-env-cics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
fault-injection = []

[dependencies]
mainframe-env-source.workspace = true
mainframe-env-execution-api.workspace = true
mainframe-env-encoding.workspace = true
mainframe-env-host-api.workspace = true
mainframe-env-store-api.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
mainframe-env-store = { path = "../../stores/mainframe-env-store" }
mainframe-env-racf.workspace = true
