#!/usr/bin/env python3
"""Enforce the reviewed Rust module-size and crate-facade ratchet."""

from __future__ import annotations

import argparse
import json
from pathlib import Path, PurePosixPath
import re
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
INVENTORY_PATH = Path("conformance/subsystems/cics/application/inventory/module-budgets.json")
SCHEMA_VERSION = "mainframe-env.rust-module-budgets@1"
GENERATED_PREFIX = "// @generated by `"
TEST_SUFFIX = re.compile(
    r"(?m)^#\[cfg\(test\)\]\r?\n"
    r"(?:#\[[^\n]+\]\r?\n)*"
    r"mod\s+[A-Za-z_][A-Za-z0-9_]*\s*\{"
)
CHAR_LITERAL = re.compile(
    r"'(?:\\(?:x[0-9A-Fa-f]{2}|u\{[0-9A-Fa-f_]+\}|.)|[^\\'\r\n])'"
)
RAW_STRING = re.compile(r'(?:br|r)(?P<hashes>#{0,255})"')
FACADE_IMPLEMENTATION = re.compile(
    r"^(?:pub(?:\([^\n)]*\))?\s+)?"
    r"(?:(?:async|unsafe)\s+)?"
    r"(?:fn|struct|enum|union|trait|type|static)\b|"
    r"^(?:unsafe\s+)?impl(?:\s|<)|"
    r"^macro_rules!\s+|"
    r"^(?:extern\s+crate|use)\s+",
    re.MULTILINE,
)


class ModuleBoundaryError(ValueError):
    """A source module or its reviewed budget inventory violates the ADR."""


def _lines(source: str) -> int:
    return len(source.splitlines())


def _rust_structure(source: str) -> str:
    """Mask Rust comments and literals while preserving structural bytes."""

    masked = list(source)
    index = 0
    block_depth = 0
    while index < len(source):
        if block_depth:
            if source.startswith("/*", index):
                masked[index : index + 2] = "  "
                block_depth += 1
                index += 2
            elif source.startswith("*/", index):
                masked[index : index + 2] = "  "
                block_depth -= 1
                index += 2
            else:
                if source[index] != "\n":
                    masked[index] = " "
                index += 1
            continue
        if source.startswith("//", index):
            end = source.find("\n", index)
            end = len(source) if end == -1 else end
            masked[index:end] = " " * (end - index)
            index = end
            continue
        if source.startswith("/*", index):
            masked[index : index + 2] = "  "
            block_depth = 1
            index += 2
            continue
        raw = RAW_STRING.match(source, index)
        if raw and (index == 0 or not (source[index - 1].isalnum() or source[index - 1] == "_")):
            terminator = '"' + raw.group("hashes")
            end = source.find(terminator, raw.end())
            end = len(source) if end == -1 else end + len(terminator)
            for offset in range(index, end):
                if source[offset] != "\n":
                    masked[offset] = " "
            index = end
            continue
        if source[index] == '"':
            end = index + 1
            while end < len(source):
                if source[end] == "\\":
                    end += 2
                elif source[end] == '"':
                    end += 1
                    break
                else:
                    end += 1
            for offset in range(index, min(end, len(source))):
                if source[offset] != "\n":
                    masked[offset] = " "
            index = end
            continue
        character = CHAR_LITERAL.match(source, index)
        if character:
            masked[index : character.end()] = " " * (character.end() - index)
            index = character.end()
            continue
        index += 1
    return "".join(masked)


def terminal_test_suffix_start(source: str) -> int | None:
    """Return a proven terminal test-module marker, never an interior marker."""

    structure = _rust_structure(source)
    for marker in reversed(list(TEST_SUFFIX.finditer(source))):
        opening = structure.find("{", marker.start(), marker.end())
        if opening == -1:
            continue
        depth = 0
        closing = None
        for index in range(opening, len(structure)):
            if structure[index] == "{":
                depth += 1
            elif structure[index] == "}":
                depth -= 1
                if depth == 0:
                    closing = index
                    break
        if closing is not None and not structure[closing + 1 :].strip():
            return marker.start()
    return None


def production_line_count(source: str) -> int:
    """Count physical lines before a proven terminal unit-test module.

    Rustfmt places a top-level ``#[cfg(test)] mod ...`` at column zero.  That
    marker begins the test-only suffix.  Test helpers deliberately left before
    the suffix remain in the production count, which makes the guard
    conservative without pretending to parse Rust with regular expressions.
    """

    marker = terminal_test_suffix_start(source)
    return _lines(source if marker is None else source[:marker])


def is_test_only(path: PurePosixPath, components: set[str]) -> bool:
    return any(component in components for component in path.parts)


def is_generated(path: PurePosixPath, component: str) -> bool:
    return component in path.parts


def facade_implementation(source: str) -> str | None:
    """Return the first forbidden top-level implementation token, if present."""

    marker = terminal_test_suffix_start(source)
    production = source if marker is None else source[:marker]
    match = FACADE_IMPLEMENTATION.search(production)
    return None if match is None else match.group(0).strip()


def _object(value: Any, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ModuleBoundaryError(f"{label} must be an object")
    return value


def _array(value: Any, label: str) -> list[Any]:
    if not isinstance(value, list):
        raise ModuleBoundaryError(f"{label} must be an array")
    return value


def _text(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ModuleBoundaryError(f"{label} must be non-empty text")
    return value


def _positive_int(value: Any, label: str) -> int:
    if not isinstance(value, int) or isinstance(value, bool) or value < 1:
        raise ModuleBoundaryError(f"{label} must be a positive integer")
    return value


def _relative_path(value: Any, label: str) -> PurePosixPath:
    text = _text(value, label)
    path = PurePosixPath(text)
    if path.is_absolute() or ".." in path.parts or str(path) != text:
        raise ModuleBoundaryError(f"{label} must be a normalized repository-relative path")
    return path


def load_inventory(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as error:
        raise ModuleBoundaryError(f"{path}: {error}") from error
    inventory = _object(value, str(path))
    expected = {
        "schema_version",
        "default_max_production_lines",
        "source_roots",
        "test_only_path_components",
        "generated_path_component",
        "oversized_modules",
        "generated_exemptions",
        "facade_exemptions",
        "cics_family_layout",
    }
    if set(inventory) != expected:
        raise ModuleBoundaryError(
            f"{path} fields differ: missing={sorted(expected - set(inventory))} "
            f"unknown={sorted(set(inventory) - expected)}"
        )
    if inventory["schema_version"] != SCHEMA_VERSION:
        raise ModuleBoundaryError(f"{path} has an unsupported schema_version")
    _positive_int(
        inventory["default_max_production_lines"],
        "default_max_production_lines",
    )
    for index, value in enumerate(_array(inventory["source_roots"], "source_roots")):
        _relative_path(value, f"source_roots[{index}]")
    for index, value in enumerate(
        _array(inventory["test_only_path_components"], "test_only_path_components")
    ):
        _text(value, f"test_only_path_components[{index}]")
    _text(inventory["generated_path_component"], "generated_path_component")
    return inventory


def _reviewed_rows(
    inventory: dict[str, Any], key: str, line_field: str
) -> dict[PurePosixPath, dict[str, Any]]:
    rows: dict[PurePosixPath, dict[str, Any]] = {}
    for index, value in enumerate(_array(inventory[key], key)):
        row = _object(value, f"{key}[{index}]")
        path = _relative_path(row.get("path"), f"{key}[{index}].path")
        if path in rows:
            raise ModuleBoundaryError(f"{key} contains duplicate path {path}")
        _positive_int(row.get(line_field), f"{key}[{index}].{line_field}")
        _text(row.get("responsibility"), f"{key}[{index}].responsibility")
        _text(row.get("split_boundary"), f"{key}[{index}].split_boundary")
        rows[path] = row
    return rows


def _generated_rows(inventory: dict[str, Any]) -> dict[PurePosixPath, dict[str, Any]]:
    rows: dict[PurePosixPath, dict[str, Any]] = {}
    for index, value in enumerate(
        _array(inventory["generated_exemptions"], "generated_exemptions")
    ):
        row = _object(value, f"generated_exemptions[{index}]")
        path = _relative_path(row.get("path"), f"generated_exemptions[{index}].path")
        if path in rows:
            raise ModuleBoundaryError(f"generated_exemptions contains duplicate path {path}")
        _positive_int(
            row.get("max_generated_lines"),
            f"generated_exemptions[{index}].max_generated_lines",
        )
        _text(row.get("generator"), f"generated_exemptions[{index}].generator")
        authorities = _array(
            row.get("authorities"), f"generated_exemptions[{index}].authorities"
        )
        if not authorities:
            raise ModuleBoundaryError(f"generated_exemptions[{index}].authorities is empty")
        for authority_index, authority in enumerate(authorities):
            _relative_path(
                authority,
                f"generated_exemptions[{index}].authorities[{authority_index}]",
            )
        rows[path] = row
    return rows


def _sources(root: Path, inventory: dict[str, Any]) -> dict[PurePosixPath, str]:
    sources: dict[PurePosixPath, str] = {}
    for value in inventory["source_roots"]:
        source_root = root / str(_relative_path(value, "source_root"))
        if not source_root.is_dir():
            raise ModuleBoundaryError(f"source root is missing: {source_root}")
        for path in sorted(source_root.rglob("*.rs")):
            relative = PurePosixPath(path.relative_to(root).as_posix())
            try:
                sources[relative] = path.read_text()
            except (OSError, UnicodeDecodeError) as error:
                raise ModuleBoundaryError(f"{path}: {error}") from error
    return sources


def _check_cics_layout(
    sources: dict[PurePosixPath, str], inventory: dict[str, Any]
) -> None:
    layout = _object(inventory["cics_family_layout"], "cics_family_layout")
    expected = {
        "provider_root",
        "frozen_service",
        "existing_modules",
        "descriptor_directory",
        "handler_directory",
        "handler_modules",
    }
    if set(layout) != expected:
        raise ModuleBoundaryError("cics_family_layout fields differ from the contract")
    provider_root = _relative_path(layout["provider_root"], "cics provider_root")
    frozen_service = _relative_path(layout["frozen_service"], "cics frozen_service")
    descriptor = _relative_path(layout["descriptor_directory"], "cics descriptor_directory")
    handlers = _relative_path(layout["handler_directory"], "cics handler_directory")
    expected_handlers = {
        _relative_path(value, "cics handler_modules entry")
        for value in _array(layout["handler_modules"], "cics handler_modules")
    }
    existing = {
        _relative_path(value, "cics existing_modules entry")
        for value in _array(layout["existing_modules"], "cics existing_modules")
    }
    if frozen_service not in existing or frozen_service not in sources:
        raise ModuleBoundaryError("CICS frozen service is missing from existing_modules or sources")
    if not descriptor.is_relative_to(provider_root) or not handlers.is_relative_to(provider_root):
        raise ModuleBoundaryError("CICS descriptor and handler directories must be below provider_root")
    descriptor_modules = 0
    handler_modules: set[PurePosixPath] = set()
    for path, source in sources.items():
        if not path.is_relative_to(provider_root) or path in existing:
            continue
        if path.is_relative_to(descriptor):
            if path.name != "mod.rs" and not source.startswith(GENERATED_PREFIX):
                raise ModuleBoundaryError(
                    f"CICS descriptor {path} is not generator-owned ({GENERATED_PREFIX!r})"
                )
            if path.name != "mod.rs":
                descriptor_modules += 1
        elif path.is_relative_to(handlers):
            if path.name != "mod.rs":
                if source.startswith(GENERATED_PREFIX):
                    raise ModuleBoundaryError(
                        f"CICS semantic handler {path} must be reviewed source, not generated"
                    )
                handler_modules.add(path)
        else:
            raise ModuleBoundaryError(
                f"new CICS module {path} must be a generated descriptor or semantic handler family"
            )
    if descriptor_modules == 0:
        raise ModuleBoundaryError(
            f"CICS descriptor layer is absent below {descriptor}; freeze a generator-owned descriptor"
        )
    if not handler_modules:
        raise ModuleBoundaryError(
            f"CICS semantic family layer is absent below {handlers}; extract at least one handler family"
        )
    if handler_modules != expected_handlers:
        raise ModuleBoundaryError(
            "CICS semantic handler families differ from the frozen inventory: "
            f"missing={sorted(map(str, expected_handlers - handler_modules))} "
            f"unknown={sorted(map(str, handler_modules - expected_handlers))}"
        )


def check(root: Path = ROOT, inventory_path: Path | None = None) -> dict[str, int]:
    path = inventory_path or root / INVENTORY_PATH
    inventory = load_inventory(path)
    default = _positive_int(
        inventory["default_max_production_lines"],
        "default_max_production_lines",
    )
    test_components = set(inventory["test_only_path_components"])
    generated_component = inventory["generated_path_component"]
    oversized = _reviewed_rows(
        inventory, "oversized_modules", "max_production_lines"
    )
    facades = _reviewed_rows(
        inventory, "facade_exemptions", "max_production_lines"
    )
    generated = _generated_rows(inventory)
    sources = _sources(root, inventory)
    observed_oversized: set[PurePosixPath] = set()
    observed_generated: set[PurePosixPath] = set()
    observed_facades: set[PurePosixPath] = set()
    checked = 0

    for relative, source in sources.items():
        if is_test_only(relative, test_components):
            continue
        checked += 1
        lines = production_line_count(source)
        generated_source = is_generated(relative, generated_component)
        if generated_source and relative.name != "mod.rs" and not source.startswith(GENERATED_PREFIX):
            raise ModuleBoundaryError(
                f"generated Rust source {relative} lacks the generator-owned header"
            )
        if generated_source and lines > default:
            row = generated.get(relative)
            if row is None:
                raise ModuleBoundaryError(
                    f"generated module {relative} has {lines} lines and needs a reviewed exemption"
                )
            expected_lines = row["max_generated_lines"]
            if lines != expected_lines:
                raise ModuleBoundaryError(
                    f"generated module {relative} has {lines} lines; inventory records "
                    f"{expected_lines}; regenerate and refresh the reviewed inventory"
                )
            for authority in row["authorities"]:
                if not (root / authority).is_file():
                    raise ModuleBoundaryError(
                        f"generated module {relative} authority is missing: {authority}"
                    )
            observed_generated.add(relative)
        elif not generated_source and lines > default:
            row = oversized.get(relative)
            if row is None:
                raise ModuleBoundaryError(
                    f"production module {relative} has {lines} lines; hard limit is {default}"
                )
            expected_lines = row["max_production_lines"]
            if lines != expected_lines:
                raise ModuleBoundaryError(
                    f"production module {relative} has {lines} lines; its exact non-growing "
                    f"ceiling is {expected_lines}; split it or refresh a reviewed pre-adoption rebase"
                )
            observed_oversized.add(relative)

        if relative.name == "lib.rs":
            token = facade_implementation(source)
            if token is not None:
                row = facades.get(relative)
                if row is None:
                    raise ModuleBoundaryError(
                        f"crate facade {relative} contains implementation token {token!r}"
                    )
                expected_lines = row["max_production_lines"]
                if lines != expected_lines:
                    raise ModuleBoundaryError(
                        f"legacy crate facade {relative} has {lines} production lines; "
                        f"its exact non-growing ceiling is {expected_lines}"
                    )
                observed_facades.add(relative)

    stale = {
        "oversized_modules": set(oversized) - observed_oversized,
        "generated_exemptions": set(generated) - observed_generated,
        "facade_exemptions": set(facades) - observed_facades,
    }
    stale = {key: sorted(map(str, value)) for key, value in stale.items() if value}
    if stale:
        raise ModuleBoundaryError(f"module budget inventory has stale exemptions: {stale}")
    _check_cics_layout(sources, inventory)
    return {
        "checked_production_modules": checked,
        "oversized_modules": len(observed_oversized),
        "generated_exemptions": len(observed_generated),
        "legacy_facades": len(observed_facades),
    }


def refresh(root: Path = ROOT, inventory_path: Path | None = None) -> None:
    """Refresh exact counts while retaining human-written rationale.

    This command is intended for the final pre-adoption rebase and for lowering
    a ceiling after a split.  An increase after ADR adoption needs an explicit
    superseding decision even though this mechanical helper can record it.
    """

    path = inventory_path or root / INVENTORY_PATH
    inventory = load_inventory(path)
    default = inventory["default_max_production_lines"]
    test_components = set(inventory["test_only_path_components"])
    generated_component = inventory["generated_path_component"]
    sources = _sources(root, inventory)
    by_path = {str(relative): source for relative, source in sources.items()}

    def retain(rows: list[dict[str, Any]], field: str, generated_row: bool) -> list[dict[str, Any]]:
        kept = []
        for row in rows:
            source = by_path.get(row["path"])
            if source is None:
                raise ModuleBoundaryError(f"cannot refresh missing module {row['path']}")
            lines = production_line_count(source)
            if lines > default:
                row[field] = lines
                kept.append(row)
            elif generated_row is False and PurePosixPath(row["path"]).name == "lib.rs" and facade_implementation(source):
                row[field] = lines
                kept.append(row)
        return kept

    inventory["oversized_modules"] = retain(
        inventory["oversized_modules"], "max_production_lines", True
    )
    inventory["generated_exemptions"] = retain(
        inventory["generated_exemptions"], "max_generated_lines", True
    )
    inventory["facade_exemptions"] = retain(
        inventory["facade_exemptions"], "max_production_lines", False
    )

    known_oversized = {row["path"] for row in inventory["oversized_modules"]}
    known_generated = {row["path"] for row in inventory["generated_exemptions"]}
    known_facades = {row["path"] for row in inventory["facade_exemptions"]}
    missing = []
    for relative, source in sources.items():
        if is_test_only(relative, test_components):
            continue
        relative_text = str(relative)
        lines = production_line_count(source)
        if lines > default:
            known = known_generated if is_generated(relative, generated_component) else known_oversized
            if relative_text not in known:
                missing.append(relative_text)
        if relative.name == "lib.rs" and facade_implementation(source) and relative_text not in known_facades:
            missing.append(relative_text)
    if missing:
        raise ModuleBoundaryError(
            "add responsibility and split_boundary for new reviewed exemptions before refresh: "
            + ", ".join(sorted(set(missing)))
        )
    path.write_text(json.dumps(inventory, indent=2) + "\n")
    check(root, path)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--refresh",
        action="store_true",
        help="refresh exact counts after a reviewed split or final pre-adoption rebase",
    )
    args = parser.parse_args()
    if args.refresh:
        refresh()
        print(f"module-boundaries: refreshed {INVENTORY_PATH}")
    else:
        summary = check()
        print(
            "module-boundaries: pass "
            + " ".join(f"{key}={value}" for key, value in summary.items())
        )


if __name__ == "__main__":
    main()
