#!/usr/bin/env python3
"""Deterministic MQ reviewed-status descriptors; never reads external HTML in CI."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess

import mq_status_catalog as authority

HEADER = "// @generated by `python3 -B tools/generate_mq_status_catalog.py`; source facts only, execution credit 0.\n"
REVIEWS = {"admitted": "Admitted", "pending-number": "PendingNumber",
    "pending-numeric-conflict": "PendingNumericConflict", "pending-symbol-conflict": "PendingSymbolConflict",
    "pending-symbol-spelling": "PendingSymbolSpelling"}
BLOCK_SIZE = 48


def reproduce_wire(catalog: dict, supplemental_cache: Path, call_cache: Path) -> None:
    sources = authority.wire_source_lines(catalog, supplemental_cache, call_cache)
    wire = catalog["completion_wire_mapping"]
    for fact in [*wire["classes"], wire["excluded_unknown"]]:
        fragment = sources[wire["topic_path"]][fact["first_line"]-1:fact["last_line"]]
        if (hashlib.sha256("\n".join(fragment).encode()).hexdigest() != fact["fragment_sha256"]
                or len(fragment) != 3):
            raise ValueError("MQ generator completion fragment differs")
        symbol, decimal, hexadecimal = [line.removesuffix(" |").strip() for line in fragment]
        if (symbol != fact["symbol"] or int(decimal) != fact["decimal"]
                or hexadecimal != "X'" + fact["hexadecimal"] + "'"):
            raise ValueError("MQ generator completion numeric identity differs")
    for source in wire["corroboration"]:
        fragment = sources[source["topic_path"]][source["first_line"]-1:source["last_line"]]
        if hashlib.sha256("\n".join(fragment).encode()).hexdigest() != source["fragment_sha256"]:
            raise ValueError("MQ generator completion context differs")


def optional(value) -> str:
    return "None" if value is None else f"Some({json.dumps(value)})"


def formatted(text: str, root: Path) -> str:
    result = subprocess.run(["rustfmt", "--edition", "2024", "--config-path", str(root / "rustfmt.toml")],
        input=text, capture_output=True, text=True, cwd=authority.ROOT, check=True)
    if len(result.stdout.splitlines()) >= 1200:
        raise ValueError("MQ generated module production line bound")
    return result.stdout


def render(root: Path = authority.ROOT) -> dict[Path, str]:
    catalog = authority.load(root)
    files = {}
    modules = []
    descriptors = []
    for call, variant in zip(catalog["calls"], authority.CALL_VARIANTS):
        blocks = []
        for offset in range(0, len(call["pairs"]), BLOCK_SIZE):
            name = f"row_{call['official_row'][-4:]}_{offset // BLOCK_SIZE}"
            modules.append(name)
            blocks.append(f"{name}::PAIRS")
            rows = [HEADER, "use super::*;\npub(super) static PAIRS: &[MqStatusPairDescriptor] = &[\n"]
            for pair in call["pairs"][offset:offset+BLOCK_SIZE]:
                locations = ",".join("MqStatusSourceLocation { " + ",".join(f"{key}: {value}" for key,value in loc.items()) + " }" for loc in pair["source_locations"])
                rows.append("MqStatusPairDescriptor { "
                    f"completion: MqCompletion::{authority.COMPLETIONS[pair['completion_symbol']]}, "
                    f"reason_symbol: {json.dumps(pair['reason_symbol'])}, "
                    f"declared_decimal: {optional(pair['declared_decimal'])}, "
                    f"declared_hex: {optional(pair['declared_hex'])}, "
                    f"review: MqStatusReview::{REVIEWS[pair['review']]}, "
                    f"source_locations: &[{locations}] " + "},\n")
            rows.append("];\n")
            files[authority.OUTPUT / f"{name}.rs"] = formatted("".join(rows), root)
        section = call["reason_section"]
        section = "None" if section is None else f"Some(({section['first_line']}, {section['last_line']}))"
        notes = ",".join("MqStatusContextNote { " + ",".join(f"{key}: {json.dumps(value)}" for key,value in note.items()) + " }" for note in call["context_notes"])
        descriptors.append("MqStatusCallDescriptor { "
            f"call: MqMqiCall::{variant}, has_call_return: {str(call['return_kind']=='call-return').lower()}, "
            f"reason_section: {section}, context_notes: &[{notes}], "
            f"reviewed_projection_sha256: {json.dumps(call['reviewed_projection_sha256'])}, "
            f"pair_blocks: &[{','.join(blocks)}] " + "},\n")
    main = [HEADER, "use super::*;\n"]
    main += [f"mod {name};\n" for name in modules]
    wire = catalog["completion_wire_mapping"]
    main += [f'pub const MQ_STATUS_CATALOG_SHA256: &str = "sha256:{wire["canonical_call_return_sha256"]}";\n',
        f'pub const MQ_COMPLETION_WIRE_PROJECTION_SHA256: &str = "sha256:{wire["projection_sha256"]}";\n',
        f'pub const MQ_COMPLETION_WIRE_TOPIC_SHA256: &str = "{wire["topic_sha256"]}";\n',
        f"pub const MQ_STATUS_PAIR_COUNT: usize = {catalog['pair_count']};\n",
        f"pub const MQ_STATUS_PENDING_COUNT: usize = {catalog['pending_pair_count']};\n",
        "pub(super) const COMPLETIONS: &[(MqCompletion, &str)] = &[\n"]
    main += [f"(MqCompletion::{variant}, {json.dumps(symbol)}),\n" for symbol,variant in authority.COMPLETIONS.items()]
    main += ["];\npub(super) fn completion_symbol(completion: MqCompletion) -> &'static str { match completion {\n"]
    main += [f"MqCompletion::{variant} => {json.dumps(symbol)},\n" for symbol,variant in authority.COMPLETIONS.items()]
    main += ["} }\npub(super) fn completion_wire_number(completion: MqCompletion) -> i32 { match completion {\n"]
    main += [f"MqCompletion::{authority.COMPLETIONS[fact['symbol']]} => {fact['decimal']},\n" for fact in wire["classes"]]
    main += ["} }\npub(super) fn completion_from_wire(number: i32) -> Option<MqCompletion> { match number {\n"]
    main += [f"{fact['decimal']} => Some(MqCompletion::{authority.COMPLETIONS[fact['symbol']]}),\n" for fact in wire["classes"]]
    main += ["_ => None, } }\npub(super) static CALLS: [MqStatusCallDescriptor; 26] = [\n", *descriptors,
        "];\npub(super) fn descriptor(call: MqMqiCall) -> &'static MqStatusCallDescriptor { &CALLS[match call {\n"]
    main += [f"MqMqiCall::{variant} => {index},\n" for index,variant in enumerate(authority.CALL_VARIANTS)]
    main.append("}] }\n")
    files[authority.OUTPUT / "mod.rs"] = formatted("".join(main), root)
    return files


def check(root: Path = authority.ROOT) -> None:
    expected = render(root)
    actual = set((root / authority.OUTPUT).glob("*.rs"))
    if actual != {root / path for path in expected}:
        raise ValueError("MQ generated status module set differs")
    for path, text in expected.items():
        if (root / path).read_text() != text:
            raise ValueError(f"stale generated MQ status descriptor: {path}")


def patch(root: Path = authority.ROOT) -> str:
    parts = ["*** Begin Patch\n"]
    expected = render(root)
    for path in sorted(set((root / authority.OUTPUT).glob("*.rs")) - {root / p for p in expected}):
        parts.append(f"*** Delete File: {path.relative_to(root)}\n")
    for path,text in expected.items():
        target = root / path
        if target.exists():
            if target.read_text() == text:
                continue
            parts.append(f"*** Update File: {path}\n@@\n")
            parts.extend("-"+line+"\n" for line in target.read_text().splitlines())
        else:
            parts.append(f"*** Add File: {path}\n")
        parts.extend("+"+line+"\n" for line in text.splitlines())
    parts.append("*** End Patch\n")
    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--patch", action="store_true", help="emit edits for apply_patch")
    parser.add_argument("--supplemental-cache", type=Path)
    parser.add_argument("--source-cache", type=Path)
    args = parser.parse_args()
    if bool(args.supplemental_cache) != bool(args.source_cache):
        parser.error("wire reproduction requires supplemental and original call caches")
    if args.supplemental_cache:
        reproduce_wire(authority.load(), args.supplemental_cache, args.source_cache)
    if args.check:
        check()
        print("MQ status descriptors fresh; execution credit 0")
    else:
        print(patch(), end="")


if __name__ == "__main__":
    main()
