"""Independent, finite inquiry projection in the existing MQ catalog authority.

No selector execution, object origin or authorization follows from this artifact.
Historical @1/@2 projections stay separately frozen; HTML stays external.
"""
import hashlib
import json
from pathlib import Path
import sys

import mq_wire_options as wire

OUTPUT = Path('crates/contracts/mainframe-env-host-api/src/mq_mqi/inquiry/generated.rs')
PROJECTION_SHA = '8ba5dd73b8cc3870dad202885073b821c9525c993e3477f46ddb9c304a825792'
SCOPES = ('ibm-mq-9.4-mqi-2026-08-31', 'mq-programming-supplements',
          'mq-inquiry-attribute-sources')


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(',', ':')).encode()).hexdigest()


def load(root):
    wire.historical_sha(root / wire.CATALOG)
    value = wire.read_json(root / wire.CATALOG).get('inquiry_local_type')
    if not isinstance(value, dict) or digest(value) != PROJECTION_SHA:
        raise ValueError('reviewed MQ inquiry local-type projection differs')
    topics = {}
    for source, scope in zip(value['sources'], SCOPES, strict=True):
        path = root / source['topic_manifest']['path']
        manifest = wire.read_json(path)
        if (source['scope_id'] != scope or source['baseline_id'] != manifest['baseline_id']
                or manifest['product'] != 'SSFKSJ_9.4.0'
                or source['topic_manifest']['sha256'] != hashlib.sha256(path.read_bytes()).hexdigest()):
            raise ValueError('MQ inquiry manifest identity differs')
        topics.update({t['topic_path']: t['sha256'] for t in manifest['topics']})
    for locator in [f['source'] for f in value['facts']] + list(value['semantics'].values()):
        if topics.get(locator['topic_path']) != locator['topic_sha256']:
            raise ValueError('MQ inquiry source pin differs')
    return value


def verify_source(root, caches):
    value = load(root)
    sys.path.insert(0, str(root / 'conformance/tools'))
    import ibm_docs
    contents = {}
    needed = [f['source'] for f in value['facts']] + list(value['semantics'].values())
    for scope in SCOPES:
        pins, tocs = ibm_docs.select(*ibm_docs.load_pins(), scope, None)
        cache = caches[scope]
        for toc in tocs:
            ibm_docs.cached_toc(cache, toc)
        for pin in pins:
            if any(s['topic_path'] == pin.topic for s in needed):
                contents[pin.topic] = ibm_docs.plain_text(ibm_docs.cached_body(cache, pin))
    for source in needed:
        fragment = contents[source['topic_path']][source['first_line']-1:source['last_line']]
        if hashlib.sha256('\n'.join(fragment).encode()).hexdigest() != source['fragment_sha256']:
            raise ValueError('MQ inquiry source fragment differs')
    for fact in value['facts']:
        s = fact['source']
        fragment = contents[s['topic_path']][s['first_line']-1:s['last_line']]
        if [line.removesuffix(' |') for line in fragment] != [
                fact['symbol'], str(fact['decimal']), "X'" + fact['hexadecimal'] + "'"]:
            raise ValueError('MQ inquiry numeric source reproduction differs')


def render(root):
    value = load(root)
    out = ['// @generated by tools/generate_mq_mqi_registry.py; do not edit.\n',
           'pub(super) const PROJECTION_SHA256: &str =\n',
           f'    "{PROJECTION_SHA}";\n']
    for fact in value['facts']:
        out.append(f"pub(super) const {fact['symbol']}: i32 = {fact['decimal']};\n")
    out.append(f"pub(super) const MAX_INTEGER_SLOTS: usize = {value['owned_limits']['integer_slots']};\n")
    return ''.join(out)
