"""Independent private property projection in the ONE MQ structure catalog."""
import hashlib
import json
from pathlib import Path
import re
import sys

import mq_raw_layout as raw
import mq_wire_options as wire

OUTPUT = Path('crates/contracts/mainframe-env-host-api/src/mq_mqi/property/generated.rs')
PROJECTION_SHA = '163cbc407141a7a896d43edf60b549c1ad1b42e272ff02f91334e3961f4f6448'
SCOPES = ('mq-property-sources', 'mq-programming-supplements', 'ibm-mq-9.4-mqi-2026-08-31')

def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(',', ':')).encode()).hexdigest()

def load(root):
    layouts = raw.load(root)  # preserves all historical/raw/wire identities
    value = wire.read_json(root / wire.CATALOG).get('property_profile')
    if not isinstance(value, dict):
        raise ValueError('missing MQ property projection')
    if (digest(value) != PROJECTION_SHA
            or value['schema_version'] != 'mainframe-env.mq-property-profile@1'
            or value['semantic_execution_credit'] != 0
            or value['historical_catalog_sha256'] != wire.HISTORICAL_SHA
            or value['raw_layout_projection_sha256'] != raw.PROJECTION_SHA):
        raise ValueError('MQ property projection identity/credit differs')
    topics = {}
    for source, scope in zip(value['sources'], SCOPES, strict=True):
        path = root / source['topic_manifest']['path']; manifest = wire.read_json(path)
        if (source['scope_id'] != scope or source['baseline_id'] != manifest['baseline_id']
                or source['topic_manifest']['sha256'] != hashlib.sha256(path.read_bytes()).hexdigest()
                or manifest['product'] != 'SSFKSJ_9.4.0'):
            raise ValueError('MQ property manifest binding differs')
        for topic in manifest['topics']:
            topics[topic['topic_path']] = topic['sha256']
    for locator in raw.locators(value):
        if (topics.get(locator['topic_path']) != locator['topic_sha256']
                or not 1 <= locator['first_line'] <= locator['last_line'] <= 4000):
            raise ValueError('MQ property source locator differs')
    facts = value['facts']
    if len(facts) != 77 or [f['symbol'] for f in facts] != sorted({f['symbol'] for f in facts}):
        raise ValueError('MQ property numeric count/order/duplicate differs')
    for fact in facts:
        if (type(fact['decimal']) is not int or not -2147483648 <= fact['decimal'] <= 2147483647
                or int(fact['hexadecimal'],16) != fact['decimal'] & 0xffffffff):
            raise ValueError('MQ property numeric identity differs')
    if (value['descriptor_layout'] != 'Md1'
            or value['descriptor_excluded_fields'] != ['StrucId','Version']):
        raise ValueError('MQ property descriptor applicability differs')
    return value, next(l for l in layouts['layouts'] if l['kind'] == 'Md1')

def verify_source(root, caches):
    value, _ = load(root)
    sys.path.insert(0,str(root/'conformance/tools')); import ibm_docs
    all_pins, all_tocs = ibm_docs.load_pins(); contents = {}
    needed = {s['topic_path'] for s in raw.locators(value)}
    for source in value['sources']:
        scope = source['scope_id']; pins, tocs = ibm_docs.select(all_pins, all_tocs, scope, None)
        for toc in tocs: ibm_docs.cached_toc(caches[scope],toc)
        for pin in pins:
            if pin.topic in needed:
                contents[pin.topic] = ibm_docs.plain_text(ibm_docs.cached_body(caches[scope],pin))
    for s in raw.locators(value):
        fragment = contents[s['topic_path']][s['first_line']-1:s['last_line']]
        if hashlib.sha256('\n'.join(fragment).encode()).hexdigest() != s['fragment_sha256']:
            raise ValueError('MQ property fragment differs')
    for fact in value['facts']:
        s=fact['source']; fragment=contents[s['topic_path']][s['first_line']-1:s['last_line']]
        expected=[fact['symbol'], str(fact['decimal']), "X'"+fact['hexadecimal']+"'"]
        if 'platform' in fact: expected[0]=fact['platform']+'®'
        if [line.removesuffix(' |') for line in fragment] != expected:
            raise ValueError('MQ property numeric fact reproduction differs')
    for identity in value['identifiers']:
        s=identity['source']; fragment=contents[s['topic_path']][s['first_line']-1:s['last_line']]
        if [line.strip('“” |').replace('¬',' ') for line in fragment] != [identity['symbol'],identity['value']]:
            raise ValueError('MQ property identifier reproduction differs')

def rust_name(name):
    name = re.sub(r'([A-Z]+)([A-Z][a-z])',r'\1_\2',name)
    return re.sub(r'([a-z0-9])([A-Z])',r'\1_\2',name).lower()

def render(root):
    value, layout = load(root)
    out=['// @generated by tools/generate_mq_mqi_registry.py; do not edit.\n',
         f'/// Exact reviewed private property projection; no execution credit.\npub const MQ_PROPERTY_PROFILE_SHA256: &str = "{PROJECTION_SHA}";\n']
    for fact in value['facts']:
        name = fact['symbol'] + ('_ZOS' if 'platform' in fact else '')
        out.append(f'pub(super) const {name}: i32 = {fact["decimal"]};\n')
    out.append('pub(super) const NUMERIC_IDENTITIES: &[MqPropertyNumericFact] = &[\n')
    for fact in value['facts']:
        name = fact['symbol'] + ('_ZOS' if 'platform' in fact else '')
        out.append(f'    MqPropertyNumericFact {{ symbol: "{name}", value: {name} }},\n')
    out.append('];\n')
    out.append('pub(super) fn value_width(kind: MqPropertyType) -> Option<usize> {\n    match kind {\n')
    for width in value['value_widths']:
        expression='None' if width['bytes'] is None else f'Some({width["bytes"]})'
        out.append(f'        MqPropertyType::{width["kind"]} => {expression},\n')
    out.append('    }\n}\n')
    for identity in value['identifiers']:
        out.append(f'pub(super) const {identity["symbol"]}: [u8; {len(identity["value"])}] = *b{json.dumps(identity["value"])};\n')
    out.append(f'pub(super) const PROPERTY_UTF8_CCSID: i32 = {value["explicit_string_ccsid"]["decimal"]};\n')
    fields = [f for f in layout['fields'] if f['name'] not in value['descriptor_excluded_fields']]
    out.append('pub(super) const MD_FIELDS: &[MqPropertyMdField] = &[\n')
    for f in fields:
        kind = {'long':'Int32','bytes':'ByteString','characters':'String'}[f['kind']]
        out.append(f'    MqPropertyMdField {{ name: "{f["name"]}", kind: MqPropertyType::{kind}, width: {f["width"]} }},\n')
    out.append('];\n')
    out.append('pub(super) fn initial_md() -> crate::mq_md_value::MqMdValue {\n    crate::mq_md_value::MqMdValue::V1 {\n        characters: crate::mq_md_value::MqMdCharacterEncoding::AsciiCompatible,\n        fields: crate::mq_md_value::MqMdFields {\n')
    for f in layout['fields']:
        if f['name']=='Version': continue
        initial=f['initial']; name=rust_name(f['name'])
        if initial['kind']=='identifier': expression='*b'+json.dumps(layout['identifier'])
        elif initial['kind']=='long': expression=str(initial['value'])
        elif initial['kind']=='environment': expression='MQENC_NATIVE_ZOS'
        elif initial['kind']=='blanks': expression=f"[b' '; {f['width']}]"
        elif initial['kind']=='nulls': expression=f"[0; {f['width']}]"
        else: raise ValueError('unsupported MQ property MD initializer')
        out.append(f'            {name}: {expression},\n')
    out.append('        },\n    }\n}\n')
    out.append('pub(super) fn md_bytes(md: &crate::mq_md_value::MqMdValue, name: &str) -> Option<Vec<u8>> {\n    let fields=md.fields();\n    Some(match name {\n')
    for f in fields:
        expression=f'fields.{rust_name(f["name"])}'
        if f['kind']=='long': expression+='.to_be_bytes()'
        out.append(f'        "{f["name"]}" => {expression}.to_vec(),\n')
    out.append('        _ => return None,\n    })\n}\n')
    out.append('pub(super) fn set_md_bytes(md: &mut crate::mq_md_value::MqMdValue, name: &str, bytes: &[u8]) -> Result<(), MqPropertyProblem> {\n    let crate::mq_md_value::MqMdValue::V1 { fields, .. } = md else { return Err(MqPropertyProblem::Unsupported); };\n    match name {\n')
    for f in fields:
        field='fields.'+rust_name(f['name'])
        expression=(f'{field}=i32::from_be_bytes(bytes.try_into().map_err(|_| MqPropertyProblem::Value)?);'
                    if f['kind']=='long' else f'{field}.copy_from_slice(bytes);')
        out.append(f'        "{f["name"]}" if bytes.len()=={f["width"]} => {{ {expression} }},\n')
    out.append('        _ => return Err(MqPropertyProblem::Value),\n    }\n    Ok(())\n}\n')
    return ''.join(out)
