"""Reviewed RFH2 projection in the existing structure catalog, never execution credit."""
import hashlib
import json
from pathlib import Path
import sys

import mq_property_profile as property_profile
import mq_raw_layout as raw
import mq_wire_options as wire

OUTPUT = Path('crates/contracts/mainframe-env-host-api/src/mq_mqi/rfh2/generated.rs')
PROJECTION_SHA = '93269ee1143b5322d1fd611386608f84a4ff198ae2abdf0cb429b8b087baa378'
SCOPES = ('mq-rfh2-sources', 'mq-programming-supplements', 'mq-property-sources',
          'ibm-mq-9.4-mqi-2026-08-31')

def load(root):
    property_profile.load(root)
    value = wire.read_json(root / wire.CATALOG).get('rfh2_profile')
    if (not isinstance(value, dict) or property_profile.digest(value) != PROJECTION_SHA
            or value['schema_version'] != 'mainframe-env.mq-rfh2-profile@1'
            or value['semantic_execution_credit'] != 0
            or value['property_projection_sha256'] != property_profile.PROJECTION_SHA):
        raise ValueError('RFH2 reviewed projection identity differs')
    topics = {}
    for source, scope in zip(value['sources'], SCOPES, strict=True):
        path = root / source['topic_manifest']['path']; manifest = wire.read_json(path)
        if (source['scope_id'] != scope or source['baseline_id'] != manifest['baseline_id']
                or source['topic_manifest']['sha256'] != hashlib.sha256(path.read_bytes()).hexdigest()
                or manifest['product'] != 'SSFKSJ_9.4.0'):
            raise ValueError('RFH2 source manifest binding differs')
        topics.update({t['topic_path']: t['sha256'] for t in manifest['topics']})
    for loc in raw.locators(value):
        if (topics.get(loc['topic_path']) != loc['topic_sha256']
                or not 1 <= loc['first_line'] <= loc['last_line'] <= 4000):
            raise ValueError('RFH2 source locator differs')
    facts = value['facts']
    if len(facts) != 10 or [f['symbol'] for f in facts] != sorted({f['symbol'] for f in facts}):
        raise ValueError('RFH2 numeric membership differs')
    for f in facts:
        if type(f['decimal']) is not int or int(f['hexadecimal'], 16) != f['decimal']:
            raise ValueError('RFH2 numeric identity differs')
    offset = 0
    for f in value['fields']:
        if f['offset'] != offset or f['width'] not in (4, 8):
            raise ValueError('RFH2 declaration layout differs')
        offset += f['width']
    if offset != next(f['decimal'] for f in facts if f['symbol']=='MQRFH_STRUC_LENGTH_FIXED_2'):
        raise ValueError('RFH2 fixed declaration length differs')
    return value

def verify_source(root, caches):
    value = load(root)
    sys.path.insert(0, str(root / 'conformance/tools')); import ibm_docs
    contents = {}; needed = {loc['topic_path'] for loc in raw.locators(value)}
    for source in value['sources']:
        scope = source['scope_id']; pins, tocs = ibm_docs.select(*ibm_docs.load_pins(), scope, None)
        for toc in tocs: ibm_docs.cached_toc(caches[scope], toc)
        for pin in pins:
            if pin.topic in needed:
                contents[pin.topic] = ibm_docs.plain_text(ibm_docs.cached_body(caches[scope], pin))
    def fragment(loc):
        lines = contents[loc['topic_path']][loc['first_line']-1:loc['last_line']]
        if hashlib.sha256('\n'.join(lines).encode()).hexdigest() != loc['fragment_sha256']:
            raise ValueError('RFH2 source fragment differs')
        return lines
    for loc in raw.locators(value): fragment(loc)
    for fact in value['facts']:
        if [l.removesuffix(' |') for l in fragment(fact['source'])] != [
                fact['symbol'], str(fact['decimal']), "X'"+fact['hexadecimal']+"'"]:
            raise ValueError('RFH2 numeric source reproduction differs')
    for identity in value['identifiers']:
        if [l.strip('“” |').replace('¬', ' ') for l in fragment(identity['source'])] != [
                identity['symbol'], identity['value']]:
            raise ValueError('RFH2 identifier reproduction differs')
    for field in value['fields']:
        declaration = fragment(field['source'])[0]
        expected = ('PIC S9(9) BINARY.' if field['kind']=='long'
                    else f'PIC X({field["width"]}).')
        if field['name'] not in declaration or expected not in declaration:
            raise ValueError('RFH2 declaration reproduction differs')

def render(root):
    value = load(root)
    out = ['// @generated by tools/generate_mq_mqi_registry.py; do not edit.\n',
           '/// Frozen private RFH2 projection, with no execution credit.\n',
           f'pub const MQ_RFH2_PROFILE_SHA256: &str =\n    "{PROJECTION_SHA}";\n']
    for fact in value['facts']:
        out.append(f'pub(super) const {fact["symbol"]}: i32 = {fact["decimal"]};\n')
    for i in value['identifiers']:
        out.append(f'pub(super) const {i["symbol"]}: [u8; {len(i["value"])}] = *b{json.dumps(i["value"])};\n')
    for field in value['fields']:
        out.append(f'pub(super) const {field["name"]}_OFFSET: usize = {field["offset"]};\n')
    out.append(f'pub(super) const MQCCSI_INHERIT: i32 = {value["formatter"]["inherited_ccsid"]["decimal"]};\n')
    out.append(f'pub(super) const NAME_VALUE_CCSID: i32 = {value["formatter"]["name_value_ccsid"]["decimal"]};\n')
    for kind in ('reserved_names', 'reserved_prefixes'):
        out.append(f'pub(super) const {kind.upper()}: &[&str] = &[\n')
        out.extend('    '+json.dumps(name)+',\n' for name in value[kind]['names'])
        out.append('];\n')
    out.append('pub(super) fn lexical(kind: crate::MqPropertyType) -> Option<&\'static str> {\n    Some(match kind {\n')
    for t in value['types']:
        out.append(f'        crate::MqPropertyType::{t["kind"]} => "{t["lexical"]}",\n')
    out.append('        _ => return None,\n    })\n}\n')
    return ''.join(out)
