//! Literal independently assembled stdlib HMAC vectors; never generated by this codec.

use super::*;
use std::cell::Cell;

const IDENTITY: &str = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
const WIRE_0: &str = concat!(
    "0YRPogEFBEpyZXZpZXcta2V5oFhHc2hhMjU2OmUzYjBjNDQyOThmYzFjMTQ5YWZiZjRjODk5NmZiOTI0",
    "MjdhZTQxZTQ2NDliOTM0Y2E0OTU5OTFiNzg1MmI4NTVYIInc9L64UV87fn2kbI1Vc4PWZ1JF0/G+Fe9J",
    "LfxR84E8",
);
const MAC_STRUCTURE_0: &str = concat!(
    "84644d4143304fa20105044a7265766965772d6b6579581c6d61696e6672616d652d656e762e7061",
    "636b6167652d61757468403158477368613235363a65336230633434323938666331633134396166",
    "62663463383939366662393234323761653431653436343962393334636134393539393162373835",
    "3262383535",
);
const TAG_0: &str = "89dcf4beb8515f3b7e7da46c8d557383d6675245d3f1be15ef492dfc51f3813c";
const WIRE_1: &str = concat!(
    "0YRYRqIBBQRYQEtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tL",
    "S0tLS0tLS0tLS0tLS0ugWEdzaGEyNTY6ZTNiMGM0NDI5OGZjMWMxNDlhZmJmNGM4OTk2ZmI5MjQyN2Fl",
    "NDFlNDY0OWI5MzRjYTQ5NTk5MWI3ODUyYjg1NVggoRhiP8ijFqGdyp6Ya98Tr8SdLdgGDD6r8QdxHmVh",
    "fAs",
);
const MAC_STRUCTURE_1: &str = concat!(
    "84644d4143305846a201050458404b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b",
    "4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b581c",
    "6d61696e6672616d652d656e762e7061636b6167652d61757468403158477368613235363a653362",
    "30633434323938666331633134396166626634633839393666623932343237616534316534363439",
    "623933346361343935393931623738353262383535",
);
const TAG_1: &str = "a118623fc8a316a19dca9e986bdf13afc49d2dd8060c3eabf107711e65617c0b";
const WIRE_2: &str = concat!(
    "0YRYRqIBBQRYQM66zrrOus66zrrOus66zrrOus66zrrOus66zrrOus66zrrOus66zrrOus66zrrOus66",
    "zrrOus66zrrOus66zrqgWEdzaGEyNTY6ZTNiMGM0NDI5OGZjMWMxNDlhZmJmNGM4OTk2ZmI5MjQyN2Fl",
    "NDFlNDY0OWI5MzRjYTQ5NTk5MWI3ODUyYjg1NVggcYH57SHYTCtDl0xKSbdIHfuUZ/qYBeYJqCWvbhMM",
    "dt8",
);
const MAC_STRUCTURE_2: &str = concat!(
    "84644d4143305846a20105045840cebacebacebacebacebacebacebacebacebacebacebacebaceba",
    "cebacebacebacebacebacebacebacebacebacebacebacebacebacebacebacebacebacebaceba581c",
    "6d61696e6672616d652d656e762e7061636b6167652d61757468403158477368613235363a653362",
    "30633434323938666331633134396166626634633839393666623932343237616534316534363439",
    "623933346361343935393931623738353262383535",
);
const TAG_2: &str = "7181f9ed21d84c2b43974c4a49b7481dfb9467fa9805e609a825af6e130c76df";
const WIRE_3: &str = concat!(
    "0YRYUKIZAAEaAAAABRoAAAAEWEBLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tL",
    "S0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLoFhHc2hhMjU2OmUzYjBjNDQyOThmYzFjMTQ5YWZiZjRjODk5",
    "NmZiOTI0MjdhZTQxZTQ2NDliOTM0Y2E0OTU5OTFiNzg1MmI4NTVYIDVhwSE76Z+u3dwp+TICUGY/wrxC",
    "f/iu1Re2yAaeRm9+",
);
const MAC_STRUCTURE_3: &str = concat!(
    "84644d4143305850a21900011a000000051a0000000458404b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b",
    "4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b4b",
    "4b4b4b4b4b4b4b4b581c6d61696e6672616d652d656e762e7061636b6167652d6175746840315847",
    "7368613235363a653362306334343239386663316331343961666266346338393936666239323432",
    "37616534316534363439623933346361343935393931623738353262383535",
);
const TAG_3: &str = "3561c1213be99faedddc29f9320250663fc2bc427ff8aed517b6c8069e466f7e";

fn hex(value: &str) -> Vec<u8> {
    value
        .as_bytes()
        .as_chunks::<2>()
        .0
        .iter()
        .map(|pair| u8::from_str_radix(std::str::from_utf8(pair).unwrap(), 16).unwrap())
        .collect()
}

fn assert_refused(key_id: &str, identity: &str, value: &str) {
    let calls = Cell::new(0);
    assert!(!verify_package_authentication(
        key_id,
        PACKAGE_AUTHENTICATION_ALGORITHM,
        identity,
        value,
        |_, _| {
            calls.set(calls.get() + 1);
            true
        },
    ));
    assert_eq!(calls.get(), 0, "structural refusal must precede trust");
}

fn golden() -> CoseMac0 {
    CoseMac0::from_tagged_slice(&STANDARD_NO_PAD.decode(WIRE_0).unwrap()).unwrap()
}

fn wire(envelope: CoseMac0) -> String {
    STANDARD_NO_PAD.encode(envelope.to_tagged_vec().unwrap())
}

fn protected(bytes: &[u8]) -> String {
    let mut envelope = golden();
    envelope.protected.original_data = Some(bytes.to_vec());
    wire(envelope)
}

#[test]
fn package_authentication_literal_mac_structure_and_wire_controls() {
    for (kid, encoded, expected_mac, tag) in [
        ("review-key".to_owned(), WIRE_0, MAC_STRUCTURE_0, TAG_0),
        ("K".repeat(64), WIRE_1, MAC_STRUCTURE_1, TAG_1),
        ("κ".repeat(32), WIRE_2, MAC_STRUCTURE_2, TAG_2),
    ] {
        let calls = Cell::new(0);
        assert!(verify_package_authentication(
            &kid,
            PACKAGE_AUTHENTICATION_ALGORITHM,
            IDENTITY,
            encoded,
            |actual_tag, actual_mac| {
                calls.set(calls.get() + 1);
                actual_tag == hex(tag) && actual_mac == hex(expected_mac)
            },
        ));
        assert_eq!(calls.get(), 1);
        let signed = encode_package_authentication(&kid, IDENTITY, |actual_mac| {
            assert_eq!(actual_mac, hex(expected_mac));
            hex(tag).try_into().unwrap()
        })
        .unwrap();
        assert_eq!(signed.value, encoded);
        assert_eq!(signed.key_id, kid);
        assert_eq!(signed.algorithm, PACKAGE_AUTHENTICATION_ALGORITHM);
    }
    assert_eq!(STANDARD_NO_PAD.decode(WIRE_1).unwrap().len(), 182);
    assert_eq!(WIRE_1.len(), 243);
}

#[test]
fn package_authentication_byte_boundaries_and_noncanonical_protected_refuse() {
    assert_eq!(WIRE_3.len(), 256);
    assert_eq!(STANDARD_NO_PAD.decode(WIRE_3).unwrap().len(), 192);
    // A correct independent MAC over nonminimal protected bytes must still refuse before trust.
    assert_eq!(hex(TAG_3).len(), 32);
    assert_eq!(hex(MAC_STRUCTURE_3).len(), 191);
    assert_refused(&"K".repeat(64), IDENTITY, WIRE_3);
    assert_refused(&"K".repeat(65), IDENTITY, WIRE_1);
    assert_refused(&"κ".repeat(33), IDENTITY, WIRE_2);
    for value in ["A".repeat(257), "A".repeat(258), "A".repeat(1024 * 1024)] {
        assert_refused("review-key", IDENTITY, &value);
    }
    for length in [0, 1, 191, 192, 193] {
        assert_refused(
            "review-key",
            IDENTITY,
            &STANDARD_NO_PAD.encode(vec![0; length]),
        );
    }
    for value in [
        format!("{WIRE_0}="),
        format!(" {WIRE_0}"),
        format!("{WIRE_0}\n"),
        WIRE_0.replace('+', "-"),
        WIRE_0.replace('/', "_"),
        format!("{}t", &WIRE_1[..WIRE_1.len() - 1]),
    ] {
        assert_refused("review-key", IDENTITY, &value);
    }
    for identity in [
        "sha256:0".to_owned(),
        IDENTITY.to_uppercase(),
        IDENTITY.replace("e3b0", "f3b0"),
    ] {
        assert_refused("review-key", &identity, WIRE_0);
    }
    for kid in ["", "different", "review-key\n"] {
        assert_refused(kid, IDENTITY, WIRE_0);
    }
}

#[test]
fn package_authentication_duplicate_trailing_tag_and_nested_refusals() {
    let original = STANDARD_NO_PAD.decode(WIRE_0).unwrap();
    let mut trailing = original.clone();
    trailing.push(0);
    let mut double_tag = vec![0xd1];
    double_tag.extend_from_slice(&original);
    let mut wrong_tag = original.clone();
    wrong_tag[0] = 0xd2;
    let mut wide_tag = vec![0xd8, 17];
    wide_tag.extend_from_slice(&original[1..]);
    let mut deep = vec![0xd1];
    deep.extend_from_slice(&[0x81; 64]);
    deep.push(0);
    let mut indefinite = vec![0xd1, 0x9f];
    indefinite.extend_from_slice(&original[2..]);
    indefinite.push(0xff);
    for malformed in [
        original[1..].to_vec(),
        trailing,
        double_tag,
        wrong_tag,
        wide_tag,
        deep,
        indefinite,
        vec![0xd1, 0x83, 0x40, 0xa0, 0xf6],
        hex("d19bffffffffffffffff"),
        hex("d1845bffffffffffffffff"),
        hex("d18440bbffffffffffffffff"),
    ] {
        assert_refused("review-key", IDENTITY, &STANDARD_NO_PAD.encode(malformed));
    }
    for (index, replacement) in [
        (2, 0x6f),
        (18, 0x80),
        (19, 0x78),
        (original.len() - 34, 0x78),
    ] {
        let mut malformed = original.clone();
        malformed[index] = replacement;
        assert_refused("review-key", IDENTITY, &STANDARD_NO_PAD.encode(malformed));
    }
    for bytes in [
        // Duplicate alg, duplicate kid, semantically duplicate alternate-width alg label.
        hex("a301050105044a7265766965772d6b6579"),
        hex("a30105044a7265766965772d6b6579044a7265766965772d6b6579"),
        hex("a30105180105044a7265766965772d6b6579"),
        hex("a40105044a7265766965772d6b6579181800181800"),
        // Same permitted labels in reversed order are not the canonical profile.
        hex("a2044a7265766965772d6b65790105"),
        hex("a201051a000000044a7265766965772d6b6579"),
        hex("a20105044a7265766965772d6b657900"),
        hex("a30105044a7265766965772d6b6579028101"),
        hex("a30105044a7265766965772d6b657902811818"),
        hex("a30105044a7265766965772d6b65790280"),
        hex("a30105044a7265766965772d6b65790540"),
        hex("a30105044a7265766965772d6b65790640"),
        hex("a30105044a7265766965772d6b65790780"),
        hex("a201050441ff"),
    ] {
        assert_refused("review-key", IDENTITY, &protected(&bytes));
    }
    // Duplicate unprotected labels and a claimed-length protected header are independent bytes.
    let mut malformed = original.clone();
    malformed.splice(18..19, hex("a201050105"));
    assert_refused("review-key", IDENTITY, &STANDARD_NO_PAD.encode(malformed));
    let mut nested = hex("a30105044a7265766965772d6b65791818");
    nested.extend_from_slice(&[0x81; 32]);
    nested.push(0);
    assert_refused("review-key", IDENTITY, &protected(&nested));
}

#[test]
fn package_authentication_closed_headers_payload_and_tag_refuse_before_callback() {
    for mutation in 0..18 {
        let mut envelope = golden();
        envelope.protected.original_data = None;
        match mutation {
            0 => envelope.payload = None,
            1 => envelope.payload = Some(Vec::new()),
            2 => envelope.payload.as_mut().unwrap().truncate(70),
            3 => envelope.payload.as_mut().unwrap().push(0),
            4 => envelope.tag.clear(),
            5 => {
                envelope.tag.pop();
            }
            6 => envelope.tag.push(0),
            7 => envelope.unprotected.alg = envelope.protected.header.alg.take(),
            8 => envelope.unprotected.key_id = envelope.protected.header.key_id.clone(),
            9 => envelope.protected.header.alg = None,
            10 => {
                envelope.protected.header.alg =
                    Some(Algorithm::Assigned(iana::Algorithm::AES_MAC_128_64))
            }
            11 => envelope.protected.header.iv = vec![1],
            12 => envelope
                .protected
                .header
                .rest
                .push((coset::Label::Int(24), coset::cbor::value::Value::Null)),
            13 => envelope.protected.header.partial_iv = vec![1],
            14 => {
                envelope.protected.header.content_type =
                    Some(coset::ContentType::Text("text/plain".into()))
            }
            15 => envelope
                .protected
                .header
                .counter_signatures
                .push(coset::CoseSignature::default()),
            16 => envelope.protected.header.alg = Some(Algorithm::Text("HMAC_256_256".into())),
            17 => envelope
                .unprotected
                .rest
                .push((coset::Label::Int(24), coset::cbor::value::Value::Null)),
            _ => unreachable!(),
        }
        assert_refused("review-key", IDENTITY, &wire(envelope));
    }
    let mut envelope = golden();
    envelope.tag[0] ^= 1;
    let calls = Cell::new(0);
    assert!(!verify_package_authentication(
        "review-key",
        PACKAGE_AUTHENTICATION_ALGORITHM,
        IDENTITY,
        &wire(envelope),
        |tag, _| {
            calls.set(calls.get() + 1);
            tag == hex(TAG_0)
        },
    ));
    assert_eq!(calls.get(), 1);
    for kid in ["", "bad\n", &"K".repeat(65)] {
        assert_eq!(
            encode_package_authentication(kid, IDENTITY, |_| panic!("invalid inputs")),
            Err(InstallProblem::InvalidSignature)
        );
    }
    let calls = Cell::new(0);
    assert!(!verify_package_authentication(
        "review-key",
        "hmac-sha256@1",
        IDENTITY,
        WIRE_0,
        |_, _| {
            calls.set(1);
            true
        }
    ));
    assert_eq!(calls.get(), 0);
}
