[package]
name = "mainframe-env-racf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mainframe-env-execution-api.workspace = true
mainframe-env-host-api.workspace = true
mainframe-env-store-api.workspace = true
argon2.workspace = true
zeroize.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
mainframe-env-store = { path = "../../stores/mainframe-env-store" }
jsonschema.workspace = true
proptest.workspace = true
static_assertions.workspace = true
